# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Mon Jul 21 15:13:50 MYT 2014
# DO NOT MODIFY


# 
# altera_modular_adc_control "Altera Modular ADC Control core" v1.0
# Altera Corporation 2014.07.21.15:13:50
# Altera Modular ADC - Control core
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.0


# 
# module altera_modular_adc_control
# 
set_module_property DESCRIPTION "Altera Voltage Sensor - Control core"
set_module_property NAME altera_voltage_sensor_control
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Configuration and Programming"
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera Voltage Sensor Control core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set supported_device_families_list {"Arria 10"}
set_module_property   SUPPORTED_DEVICE_FAMILIES  $supported_device_families_list


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_voltage_sensor_control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_voltage_sensor_control.sv SYSTEM_VERILOG PATH altera_voltage_sensor_control.sv TOP_LEVEL_FILE
add_fileset_file voltage_sensor_avalon_control.sv SYSTEM_VERILOG PATH voltage_sensor_avalon_control.sv 
add_fileset_file voltage_sensor_wrapper.sv SYSTEM_VERILOG PATH voltage_sensor_wrapper.sv 

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_voltage_sensor_control
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_voltage_sensor_control.sv SYSTEM_VERILOG PATH altera_voltage_sensor_control.sv
add_fileset_file voltage_sensor_avalon_control.sv SYSTEM_VERILOG PATH voltage_sensor_avalon_control.sv 
add_fileset_file voltage_sensor_wrapper.sv SYSTEM_VERILOG PATH voltage_sensor_wrapper.sv 

add_fileset             vhdl_sim    SIM_VHDL    do_vhdl_sim
set_fileset_property    vhdl_sim    TOP_LEVEL   altera_voltage_sensor_control

proc do_vhdl_sim {output_name} {
    do_vhdl_sim_encrypt_file altera_voltage_sensor_control
}


# 
# parameters
# 

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point command
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset_sink
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 1
set_interface_property csr readWaitStates 0
set_interface_property csr readWaitTime 0
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr addr address Input 1
add_interface_port csr read read Input 1
add_interface_port csr write write Input 1
add_interface_port csr writedata writedata Input 32
add_interface_port csr readdata readdata Output 32



# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point response
# 
add_interface response avalon_streaming start
set_interface_property response associatedClock clock
set_interface_property response associatedReset reset_sink
set_interface_property response dataBitsPerSymbol 6
set_interface_property response errorDescriptor ""
set_interface_property response firstSymbolInHighOrderBits true
set_interface_property response readyLatency 0
set_interface_property response ENABLED true
set_interface_property response EXPORT_OF ""
set_interface_property response PORT_NAME_MAP ""
set_interface_property response CMSIS_SVD_VARIABLES ""
set_interface_property response SVD_ADDRESS_GROUP ""

add_interface_port response rsp_valid valid Output 1
add_interface_port response rsp_channel channel Output 3
add_interface_port response rsp_data data Output 6
add_interface_port response rsp_sop startofpacket Output 1
add_interface_port response rsp_eop endofpacket Output 1

proc do_vhdl_sim_encrypt_file {output_name} {

    if {1} {
        generate_vendor_encrypt_fileset_file mentor
    }
    if {1} {
        generate_vendor_encrypt_fileset_file aldec
    }
    if {1} {
        generate_vendor_encrypt_fileset_file cadence
    }
    if {1} {
        generate_vendor_encrypt_fileset_file synopsys
    }
}

proc generate_vendor_encrypt_fileset_file { vendor } {

    set vendor_uppercase "[ string toupper $vendor ]"
    add_fileset_file ${vendor}/altera_voltage_sensor_control.sv SYSTEM_VERILOG_ENCRYPT PATH "${vendor}/altera_voltage_sensor_control.sv"   "${vendor_uppercase}_SPECIFIC"
    add_fileset_file ${vendor}/voltage_sensor_avalon_controlr.sv SYSTEM_VERILOG_ENCRYPT PATH "${vendor}/voltage_sensor_avalon_control.sv" "${vendor_uppercase}_SPECIFIC"
    add_fileset_file ${vendor}/voltage_sensor_wrapper.sv SYSTEM_VERILOG_ENCRYPT PATH "${vendor}/voltage_sensor_wrapper.sv" "${vendor_uppercase}_SPECIFIC"
}

## Add documentation links for user guide and/or release notes
add_documentation_link "User Guide" https://documentation.altera.com/#/link/wtw1426059034681/wtw1425276826802
add_documentation_link "Release Notes" https://documentation.altera.com/#/link/hco1421698042087/hco1421698013408
