# Module name strings
HWTCL_MODULE_DISPLAY_NAME = EMIF Example Configurable Avalon Traffic Generator
HWTCL_MODULE_DESCRIPTION = Altera External Memory Interface Example Configurable Avalon Traffic Generator
