# Module name strings
HWTCL_MODULE_DISPLAY_NAME = Arria 10 External Memory Interfaces Calibration Debug Component
HWTCL_MODULE_DESCRIPTION = This component must be connected to one of the EMIF cores in an I/O column in order to debug EMIF calibration code. It is intended for internal use only.

# Clock Frequency
PARAM_SOFT_NIOS_CLOCK_FREQUENCY_NAME = Clock Frequency for Calibration Debug CPU
PARAM_SOFT_NIOS_CLOCK_FREQUENCY_DESCRIPTION = Specifies the frequency in Hz of the externally-supplied clock that drives the Debug CPU

# Enable/disable JTAG UART
PARAM_ENABLE_JTAG_UART_NAME = Enable JTAG UART for Debug Output
PARAM_ENABLE_JTAG_UART_DESCRIPTION = Enable JTAG UART for Debug Output of the Calibration Debug Component

# Enable/disable RS232 UART
PARAM_ENABLE_RS232_UART_NAME = Enable RS232 UART for Debug Output
PARAM_ENABLE_RS232_UART_DESCRIPTION = Enable RS232 UART for Debug Output of the Calibration Debug Component

# RS232 UART Baud Rate
PARAM_RS232_UART_BAUDRATE_NAME = Baud Rate for RS232 Debug UART
PARAM_RS232_UART_BAUDRATE_DESCRIPTION = Specifies the baud rate for RS232 Debug UART in bits per second. The CPU clock frequency parameter must be set correctly.


