# Module name strings
HWTCL_MODULE_DISPLAY_NAME = Dynamic Reconfiguration  Control Logic for Altera PHYLite Example Design
HWTCL_MODULE_DESCRIPTION = Altera PHYLite Dynamic Reconfiguration Control Logic for Example Design
