# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Mon Jul 21 13:16:49 MYT 2014
# DO NOT MODIFY


# 
# altera_modular_adc_sample_store "Altera Modular ADC Sample Storage core" v1.0
# Altera Corporation 2014.07.21.13:16:49
# Altera Modular ADC - Sample Storage core
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.0


# 
# module altera_modular_adc_sample_store
# 
set_module_property DESCRIPTION "Altera Modular ADC - Sample Storage core"
set_module_property NAME altera_modular_adc_sample_store
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Peripherals"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Modular ADC Sample Storage core Intel FPGA IP"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaboration



# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_modular_adc_sample_store
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_modular_adc_sample_store.v VERILOG PATH altera_modular_adc_sample_store.v TOP_LEVEL_FILE
add_fileset_file altera_modular_adc_sample_store_ram.v VERILOG PATH altera_modular_adc_sample_store_ram.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_modular_adc_sample_store
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_modular_adc_sample_store.v VERILOG PATH altera_modular_adc_sample_store.v
add_fileset_file altera_modular_adc_sample_store_ram.v VERILOG PATH altera_modular_adc_sample_store_ram.v


# 
# parameters
# 
add_parameter DUAL_ADC_MODE boolean false
set_parameter_property DUAL_ADC_MODE DISPLAY_NAME "Enable Dual ADC Mode"
set_parameter_property DUAL_ADC_MODE HDL_PARAMETER true

add_parameter RSP_DATA_WIDTH integer 12
set_parameter_property RSP_DATA_WIDTH DISPLAY_NAME "Data width of the response interface"
set_parameter_property RSP_DATA_WIDTH HDL_PARAMETER true
set_parameter_property RSP_DATA_WIDTH DERIVED true

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point response
# 
add_interface response avalon_streaming end
set_interface_property response associatedClock clock
set_interface_property response associatedReset reset_sink
set_interface_property response dataBitsPerSymbol 12
set_interface_property response errorDescriptor ""
set_interface_property response firstSymbolInHighOrderBits true
set_interface_property response maxChannel 31
set_interface_property response readyLatency 0
set_interface_property response ENABLED true
set_interface_property response EXPORT_OF ""
set_interface_property response PORT_NAME_MAP ""
set_interface_property response CMSIS_SVD_VARIABLES ""
set_interface_property response SVD_ADDRESS_GROUP ""

add_interface_port response rsp_valid valid Input 1
add_interface_port response rsp_channel channel Input 5
add_interface_port response rsp_data data Input 12
add_interface_port response rsp_sop startofpacket Input 1
add_interface_port response rsp_eop endofpacket Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset_sink
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 2
set_interface_property csr readWaitStates 0
set_interface_property csr readWaitTime 0
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr addr address Input 7
add_interface_port csr read read Input 1
add_interface_port csr write write Input 1
add_interface_port csr writedata writedata Input 32
add_interface_port csr readdata readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint "csr"
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

proc is_enabled {parameter} {
    if {[get_parameter_value $parameter] == "true"} {
	return 1
    } else {
	return 0
    }
}

# ------------------------------------------------------------------------------
# Elaboration Callback
# ------------------------------------------------------------------------------
proc elaboration {} {
    if { [is_enabled DUAL_ADC_MODE] } {
        set_parameter_value RSP_DATA_WIDTH 24
        set_interface_property response dataBitsPerSymbol 24
        add_interface_port response rsp_data data Input 24
    } else {
        set_parameter_value RSP_DATA_WIDTH 12
        set_interface_property response dataBitsPerSymbol 12
        add_interface_port response rsp_data data Input 12
    }
}
