# TCL File Generated by Component Editor 14.1
# Tue Apr 22 14:50:03 MYT 2014
# DO NOT MODIFY


# 
# altera_avalon_sld2mm "Altera Avalon SLD2MM" v1.0
# Altera 2014.04.22.14:50:03
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module altera_avalon_sld2mm
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_avalon_sld2mm
set_module_property VERSION {18.1}
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Altera
set_module_property DISPLAY_NAME "Altera Avalon SLD2MM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property VALIDATION_CALLBACK validation

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_avalon_sld2mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_sld2mm.v VERILOG PATH altera_avalon_sld2mm.v TOP_LEVEL_FILE
add_fileset_file altera_avalon_sld2mm_dr.v VERILOG PATH altera_avalon_sld2mm_dr.v
add_fileset_file altera_avalon_sld2mm_sys_domain.v VERILOG PATH altera_avalon_sld2mm_sys_domain.v
add_fileset_file altera_avalon_sld2mm_tck_domain.v VERILOG PATH altera_avalon_sld2mm_tck_domain.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_avalon_sld2mm
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_sld2mm.v VERILOG PATH altera_avalon_sld2mm.v
add_fileset_file altera_avalon_sld2mm_dr.v VERILOG PATH altera_avalon_sld2mm_dr.v
add_fileset_file altera_avalon_sld2mm_sys_domain.v VERILOG PATH altera_avalon_sld2mm_sys_domain.v
add_fileset_file altera_avalon_sld2mm_tck_domain.v VERILOG PATH altera_avalon_sld2mm_tck_domain.v


# 
# parameters
# 


add_parameter MANUAL_ADDR_WIDTH BOOLEAN false
set_parameter_property MANUAL_ADDR_WIDTH DEFAULT_VALUE false
set_parameter_property MANUAL_ADDR_WIDTH DISPLAY_NAME MANUAL_ADDR_WIDTH
set_parameter_property MANUAL_ADDR_WIDTH TYPE BOOLEAN
set_parameter_property MANUAL_ADDR_WIDTH UNITS None

add_parameter ADDR_WIDTH_GUI INTEGER 32
set_parameter_property ADDR_WIDTH_GUI DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH_GUI DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH_GUI TYPE INTEGER
set_parameter_property ADDR_WIDTH_GUI UNITS None




# system info
add_parameter SYSTEM_ADDR_WIDTH integer
set_parameter_property SYSTEM_ADDR_WIDTH DEFAULT_VALUE {0}
set_parameter_property SYSTEM_ADDR_WIDTH DISPLAY_NAME {SYSTEM_ADDR_WIDTH}
set_parameter_property SYSTEM_ADDR_WIDTH VISIBLE {0}
set_parameter_property SYSTEM_ADDR_WIDTH SYSTEM_INFO {ADDRESS_WIDTH avalon_master}
set_parameter_property SYSTEM_ADDR_WIDTH SYSTEM_INFO_TYPE {ADDRESS_WIDTH}
set_parameter_property SYSTEM_ADDR_WIDTH SYSTEM_INFO_ARG {avalon_master}


# derived parameter
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH ALLOWED_RANGES {3:32}
set_parameter_property ADDR_WIDTH VISIBLE {0}
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
set_parameter_property ADDR_WIDTH DERIVED true

# 
# display items
# 


# 
# connection point clock
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1

add_interface debug_reset reset start
set_interface_property debug_reset associatedClock clk
set_interface_property debug_reset synchronousEdges DEASSERT
set_interface_property debug_reset ENABLED true
set_interface_property debug_reset EXPORT_OF ""
set_interface_property debug_reset PORT_NAME_MAP ""
set_interface_property debug_reset CMSIS_SVD_VARIABLES ""
set_interface_property debug_reset SVD_ADDRESS_GROUP ""
set_interface_property debug_reset associatedResetSinks reset

add_interface_port debug_reset debug_reset reset Output 1

# 
# connection point sld_slave
# 
add_interface sld_slave conduit end
set_interface_property sld_slave associatedClock ""
set_interface_property sld_slave associatedReset ""
set_interface_property sld_slave ENABLED true
set_interface_property sld_slave EXPORT_OF ""
set_interface_property sld_slave PORT_NAME_MAP ""
set_interface_property sld_slave CMSIS_SVD_VARIABLES ""
set_interface_property sld_slave SVD_ADDRESS_GROUP ""

add_interface_port sld_slave tdi tdi Input 1
add_interface_port sld_slave tck tck Input 1
add_interface_port sld_slave tdo tdo Output 1
add_interface_port sld_slave virtual_state_cdr virtual_state_cdr Input 1
add_interface_port sld_slave virtual_state_sdr virtual_state_sdr Input 1
add_interface_port sld_slave virtual_state_udr virtual_state_udr Input 1
add_interface_port sld_slave virtual_state_uir virtual_state_uir Input 1
add_interface_port sld_slave ir_in ir_in Input 1
add_interface_port sld_slave jtag_state_rti jtag_state_rti Input 1

proc validation { } {
    set system_addr_width [ get_parameter_value SYSTEM_ADDR_WIDTH ]
    set manual_addr_width [ get_parameter_value MANUAL_ADDR_WIDTH ]
    set addr_width_gui    [ get_parameter_value ADDR_WIDTH_GUI    ]
    
    if { $manual_addr_width } {
        set_parameter_property ADDR_WIDTH_GUI ENABLED true
    } else {
        set_parameter_property ADDR_WIDTH_GUI ENABLED false
    }

    if { $manual_addr_width } {
        set_parameter_value  ADDR_WIDTH $addr_width_gui
    } else {
        set_parameter_value  ADDR_WIDTH $system_addr_width
    }   
}

proc elaborate { } {
# 
# connection point avalon_master
# 

    set addr_width [ get_parameter_value ADDR_WIDTH ]
    add_interface avalon_master avalon start
    set_interface_property avalon_master addressUnits SYMBOLS
    set_interface_property avalon_master associatedClock clk
    set_interface_property avalon_master associatedReset reset
    set_interface_property avalon_master bitsPerSymbol 8
    set_interface_property avalon_master burstOnBurstBoundariesOnly false
    set_interface_property avalon_master burstcountUnits WORDS
    set_interface_property avalon_master doStreamReads false
    set_interface_property avalon_master doStreamWrites false
    set_interface_property avalon_master holdTime 0
    set_interface_property avalon_master linewrapBursts false
    set_interface_property avalon_master maximumPendingReadTransactions 0
    set_interface_property avalon_master maximumPendingWriteTransactions 0
    set_interface_property avalon_master readLatency 0
    set_interface_property avalon_master readWaitTime 1
    set_interface_property avalon_master setupTime 0
    set_interface_property avalon_master timingUnits Cycles
    set_interface_property avalon_master writeWaitTime 0
    set_interface_property avalon_master ENABLED true
    set_interface_property avalon_master EXPORT_OF ""
    set_interface_property avalon_master PORT_NAME_MAP ""
    set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
    set_interface_property avalon_master SVD_ADDRESS_GROUP ""
    
    add_interface_port avalon_master av_writedata writedata Output 32
    add_interface_port avalon_master av_write write Output 1
    add_interface_port avalon_master av_waitrequest waitrequest Input 1
    add_interface_port avalon_master av_address address Output addr_width
    add_interface_port avalon_master av_read read Output 1
    add_interface_port avalon_master av_readdata readdata Input 32

}

# 
# connection point avalon_streaming_source
# 
add_interface debug_extra avalon_streaming start
set_interface_property debug_extra associatedClock clk
set_interface_property debug_extra associatedReset reset
set_interface_property debug_extra dataBitsPerSymbol 2
set_interface_property debug_extra errorDescriptor ""
set_interface_property debug_extra firstSymbolInHighOrderBits true
set_interface_property debug_extra maxChannel 0
set_interface_property debug_extra readyLatency 0
set_interface_property debug_extra ENABLED true
set_interface_property debug_extra EXPORT_OF ""
set_interface_property debug_extra PORT_NAME_MAP ""
set_interface_property debug_extra CMSIS_SVD_VARIABLES ""
set_interface_property debug_extra SVD_ADDRESS_GROUP ""

add_interface_port debug_extra debug_extra data Output 2

