#DISPLAY_NAME = ALTFP_INV
DESCRIPTION  = Altera Floating Point Matrix Invert
GROUP = Basic Functions/Arithmetic
AUTHOR = Altera Corporation
DATASHEET_URL = http://www.altera.com/literature/ug/ug_altfp_mfug.pdf

#Section names
FLOATING_PT_DATA_GROUP = Floating Point Data
OPTIONAL_PORTS_GROUP = Ports


#parameter strings that appear in Documentation page
MATRIX_SIZE_NAME = Dimension
BLOCK_SIZE_NAME = Blocks
RESET_PORT_DISPLAY_NAME = Create a Reset Port
ENABLE_PORT_DISPLAY_NAME = Create An Enable Port

MATRIX_SIZE_PARAMETER =  4 6 8 16 32 64


BLOCK_ERROR =  <b>Blocks</b> ($block_size) must be $range when <b>Dimension</b> is $matrix_size

#memory
MATRIX_SIZE_DESCRIPTION = The number of rows in the matrix. As the matrix is square, this is also the
number of columns in the matrix. The supported dimensions are 4 x 4, 6 x
6, 8 x 8, 16 x 16, 32 x 32, and 64 x 64. The maximum supported input
dimension is 64 × 64.
BLOCK_SIZE_DESCRIPTION = The number of memory blocks for the double-buffered storage of matrix
multiplication. The allowable range is from 2 to 16.
RESET_PORT_DESCRIPTION = Create a port to reset the core
ENABLE_PORT_DESCRIPTION = Create a port to control when the core is enabled
