# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 16.0
# Wed Nov 25 14:28:47 MYT 2015
# DO NOT MODIFY


# 
# altera_sdm_gpo "Altera SDM GPO " v1.0
#  2015.11.25.14:28:47
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module altera_sdm_gpo
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_sdm_fpga_core_rst
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Configuration and Programming"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Altera SDM FPGA Core Reset"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate
set all_supported_device_families_list {"Stratix 10"}
set_module_property SUPPORTED_DEVICE_FAMILIES       $all_supported_device_families_list
# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_sdm_fpga_core_rst
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file altera_sdm_fpga_core_rst.sv SYSTEM_VERILOG PATH altera_sdm_fpga_core_rst.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_sdm_fpga_core_rst
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file altera_sdm_fpga_core_rst.sv SYSTEM_VERILOG PATH altera_sdm_fpga_core_rst.sv




# 
# display items
# 


# 
# connection point gpo
# 

#+-------------------------------------------------------
#| Constant Interfaces
#+-------------------------------------------------------
#add_interface clk clock end
#add_interface_port clk clk clk Input 1

add_interface out_reset reset start

#+-------------------------------------------------------
#| Elaboration callback
#+-------------------------------------------------------
proc elaborate {} {
    add_interface_port out_reset out_reset reset Output 1
    #set_interface_property out_reset associatedClock "clk"
    #set_port_property clk TERMINATION false
   
    set_interface_property out_reset synchronousEdges NONE
}

