# TCL File Generated by Component Editor 14.1
# Wed May 28 10:52:53 MYT 2014
# DO NOT MODIFY


# 
# altera_avalon_sld2mm_sld_node "Altera Avalon SLD2MM SLD Node" v1.0
#  2014.05.28.10:52:53
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module altera_avalon_sld2mm_sld_node
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_avalon_sld2mm_sld_node
set_module_property VERSION {18.1}
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Altera Avalon SLD2MM SLD Node"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validation
set_module_property ELABORATION_CALLBACK elaboration

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_avalon_sld2mm_sld_node
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_sld2mm_sld_node.v VERILOG PATH altera_avalon_sld2mm_sld_node.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_avalon_sld2mm_sld_node
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_sld2mm_sld_node.v VERILOG PATH altera_avalon_sld2mm_sld_node.v


# 
# parameters
# 

add_parameter NIOS_DEBUG BOOLEAN false
set_parameter_property NIOS_DEBUG DEFAULT_VALUE false
set_parameter_property NIOS_DEBUG DISPLAY_NAME "NIOS II DEBUG"
set_parameter_property NIOS_DEBUG TYPE BOOLEAN
set_parameter_property NIOS_DEBUG UNITS None
set_parameter_property NIOS_DEBUG VISIBLE true

add_parameter MANUAL_INSTANCE_INDEX BOOLEAN false
set_parameter_property MANUAL_INSTANCE_INDEX DEFAULT_VALUE false
set_parameter_property MANUAL_INSTANCE_INDEX DISPLAY_NAME "MANUAL INSTANCE INDEX"
set_parameter_property MANUAL_INSTANCE_INDEX TYPE BOOLEAN
set_parameter_property MANUAL_INSTANCE_INDEX UNITS None

add_parameter SLD_AUTO_INSTANCE_INDEX STRING YES
set_parameter_property SLD_AUTO_INSTANCE_INDEX DEFAULT_VALUE YES
set_parameter_property SLD_AUTO_INSTANCE_INDEX DISPLAY_NAME SLD_AUTO_INSTANCE_INDEX
set_parameter_property SLD_AUTO_INSTANCE_INDEX TYPE STRING
set_parameter_property SLD_AUTO_INSTANCE_INDEX UNITS None
set_parameter_property SLD_AUTO_INSTANCE_INDEX HDL_PARAMETER true
set_parameter_property SLD_AUTO_INSTANCE_INDEX DERIVED true
set_parameter_property SLD_AUTO_INSTANCE_INDEX VISIBLE true

add_parameter SLD_INSTANCE_INDEX INTEGER 0
set_parameter_property SLD_INSTANCE_INDEX DEFAULT_VALUE 0
set_parameter_property SLD_INSTANCE_INDEX DISPLAY_NAME "INSTANCE INDEX"
set_parameter_property SLD_INSTANCE_INDEX TYPE INTEGER
set_parameter_property SLD_INSTANCE_INDEX UNITS None
set_parameter_property SLD_INSTANCE_INDEX HDL_PARAMETER true

add_parameter SLD_TYPE_ID INTEGER 17
set_parameter_property SLD_TYPE_ID DEFAULT_VALUE 17
set_parameter_property SLD_TYPE_ID DISPLAY_NAME SLD_TYPE_ID
set_parameter_property SLD_TYPE_ID TYPE INTEGER
set_parameter_property SLD_TYPE_ID UNITS None
set_parameter_property SLD_TYPE_ID HDL_PARAMETER true
set_parameter_property SLD_TYPE_ID DERIVED true
set_parameter_property SLD_TYPE_ID VISIBLE true


# 
# display items
# 

proc validation { } {
    set MANUAL_INSTANCE_INDEX [ get_parameter_value MANUAL_INSTANCE_INDEX ]
    set NIOS_DEBUG [ get_parameter_value NIOS_DEBUG ]
    
    if { $NIOS_DEBUG } {
        set_parameter_value SLD_TYPE_ID 17
    } else {
        set_parameter_value SLD_TYPE_ID 16
    }
    
    if { $MANUAL_INSTANCE_INDEX } {
        set_parameter_property SLD_INSTANCE_INDEX ENABLED true
        set_parameter_value SLD_AUTO_INSTANCE_INDEX "NO"
    } else {
        set_parameter_property SLD_INSTANCE_INDEX ENABLED false
    }
}

proc elaboration { } {
    # 
    # connection point sld_master
    # 
    add_interface sld_master conduit end
    set_interface_property sld_master associatedClock ""
    set_interface_property sld_master associatedReset ""
    set_interface_property sld_master ENABLED true
    set_interface_property sld_master EXPORT_OF ""
    set_interface_property sld_master PORT_NAME_MAP ""
    set_interface_property sld_master CMSIS_SVD_VARIABLES ""
    set_interface_property sld_master SVD_ADDRESS_GROUP ""
    
    add_interface_port sld_master tck tck Output 1
    add_interface_port sld_master tdi tdi Output 1
    add_interface_port sld_master tdo tdo Input 1
    add_interface_port sld_master virtual_state_sdr virtual_state_sdr Output 1
    add_interface_port sld_master virtual_state_cdr virtual_state_cdr Output 1
    add_interface_port sld_master jtag_state_rti    jtag_state_rti Output 1
    add_interface_port sld_master virtual_state_uir virtual_state_uir Output 1
    add_interface_port sld_master virtual_state_udr virtual_state_udr Output 1
    add_interface_port sld_master ir_in ir_in Output 1
    
    # we need a dummy clock and reset for driving the debug reset for FPGA/nios
    set NIOS_DEBUG [ get_parameter_value NIOS_DEBUG ]
    add_interface clk clock end
    add_interface_port clk clk clk Input 1

    add_interface reset reset start
    add_interface_port reset reset_n reset_n Output 1
    set_interface_property reset associatedclock clk
    if { !$NIOS_DEBUG } {
        set_port_property reset_n TERMINATION true
        set_port_property clk TERMINATION true
    }
}


