// (C) 2001-2018 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.




`timescale 1ps/1ps

// DESCRIPTION
// SERDES lane.
// Generated by one of Gregg's toys.   Share And Enjoy.

module alt_e2550_serdes_a10_25g #(
    parameter SYNOPT_ENABLE_PTP = 1'b0
)(
    input  wire         reconfig_write,       //      reconfig_avmm.write
    input  wire         reconfig_read,        //                   .read
    input  wire [9:0]   reconfig_address,     //                   .address
    input  wire [31:0]  reconfig_writedata,   //                   .writedata
    output wire [31:0]  reconfig_readdata,    //                   .readdata
    output wire         reconfig_waitrequest, //                   .waitrequest
    input  wire [0:0]   reconfig_clk,         //       reconfig_clk.clk
    input  wire         reconfig_reset,       //     reconfig_reset.reset

    input   tx_analogreset,   
    input   tx_digitalreset,
    input   rx_analogreset,   
    input   rx_digitalreset,  
    input   tx_serial_clk,
    input   rx_cdr_refclk,
    input   [63:0] tx_parallel_data,
    input   [9:0]  tx_control,
    input   tvalid,
    output  [63:0] rx_parallel_data,
    output  [9:0]  rx_control,
    input   rx_bitslip,
    input   rx_rden,
    input   rx_serial_data,
    output  tx_serial_data,
    input   tx_clkin,
    output  tx_clkout,
    output  tx_pma_div_clkout,
    input   rx_clkin,
    output  rx_clkout,
    output  rx_pma_div_clkout,
    input   rx_seriallpbken,
    output  rx_is_lockedtodata,

    input   rx_set_locktodata,
    input   rx_set_locktoref,

    output  tx_empty,
    output  tx_pempty,
    output  tx_pfull,
    output  tx_full,
    output  rx_empty,
    output  rx_pempty,
    output  rx_pfull,
    output  rx_full,
    output  tx_cal_busy,
    output  rx_cal_busy,

    output  [21:0] tx_path_delay_data,
    output  [21:0] rx_path_delay_data
);
wire rvalid;
wire [63:0] tx_parallel_data_phy;
wire [9:0] tx_control_phy;
wire tvalid_phy;
wire [63:0] unused_rx_parallel_data_phy;
wire [63:0] rx_parallel_data_phy;
wire [9:0] unused_rx_control_phy;
wire [9:0] rx_control_phy;
wire tx_empty_phy;
wire tx_pempty_phy;
wire tx_pfull_phy;
wire tx_full_phy;
wire rx_empty_phy;
wire rx_pempty_phy;
wire rx_pfull_phy;
wire rx_full_phy;

a10_xcvr_25g
 xcvr (
    .reconfig_write         (reconfig_write),       //      reconfig_avmm.write
    .reconfig_read          (reconfig_read),        //                   .read
    .reconfig_address       (reconfig_address),     //                   .address
    .reconfig_writedata     (reconfig_writedata),   //                   .writedata
    .reconfig_readdata      (reconfig_readdata),    //                   .readdata
    .reconfig_waitrequest   (reconfig_waitrequest), //                   .waitrequest
    .reconfig_clk           (reconfig_clk),         //       reconfig_clk.clk
    .reconfig_reset         (reconfig_reset),       //     reconfig_reset.reset


    .tx_analogreset         (tx_analogreset),
    .tx_digitalreset        (tx_digitalreset),
    .rx_analogreset         (rx_analogreset),
    .rx_digitalreset        (rx_digitalreset),
    .tx_cal_busy            (tx_cal_busy),
    .rx_cal_busy            (rx_cal_busy),
    .tx_serial_clk0         (tx_serial_clk),
    .rx_cdr_refclk0         (rx_cdr_refclk),
    .tx_serial_data         (tx_serial_data),
    .rx_serial_data         (rx_serial_data),
    .rx_is_lockedtoref      (),
    .rx_is_lockedtodata     (rx_is_lockedtodata),
    .rx_set_locktoref       (rx_set_locktoref),
    .rx_set_locktodata      (rx_set_locktodata),
    .tx_coreclkin           (tx_clkin),
    .rx_coreclkin           (rx_clkin),
    .rx_bitslip             (rx_bitslip),

    .tx_clkout              (tx_clkout),
    .rx_clkout              (rx_clkout),
    .tx_pma_div_clkout      (tx_pma_div_clkout),
    .rx_pma_div_clkout      (rx_pma_div_clkout),
    .tx_parallel_data       ({64'b0, tx_parallel_data_phy}),
    .rx_parallel_data       ({unused_rx_parallel_data_phy, rx_parallel_data_phy}),
    .tx_control             ({8'b0, tx_control_phy}),
    .rx_control             ({unused_rx_control_phy, rx_control_phy}),
    .tx_enh_data_valid      (tvalid_phy),
    .rx_enh_data_valid      (rvalid),
    .rx_enh_fifo_rd_en      (rx_rden),
    .tx_enh_fifo_empty      (tx_empty_phy),
    .tx_enh_fifo_pempty     (tx_pempty_phy),
    .tx_enh_fifo_pfull      (tx_pfull_phy),
    .tx_enh_fifo_full       (tx_full_phy),
    .rx_enh_fifo_empty      (rx_empty_phy),
    .rx_enh_fifo_pempty     (rx_pempty_phy),
    .rx_enh_fifo_pfull      (rx_pfull_phy),
    .rx_enh_fifo_full       (rx_full_phy),

    .rx_seriallpbken        (rx_seriallpbken)
);

generate if (SYNOPT_ENABLE_PTP) begin:ptp_top
    alt_e2550_ptp_fifo_top ptp_fifo (
        .tx_digitalreset(tx_digitalreset),
        .rx_digitalreset(rx_digitalreset),
        .tx_wr_clk(tx_pma_div_clkout),
        .tx_rd_clk(tx_clkout),
        .rx_wr_clk(rx_clkout),
        .rx_rd_clk(rx_pma_div_clkout),
        .tx_wr_en(tvalid),
        .tx_wr_data({tx_control,tx_parallel_data}),
        .tx_rd_valid(tvalid_phy),
        .tx_rd_data({tx_control_phy,tx_parallel_data_phy}),
        .rx_wr_valid(rvalid),
        .rx_wr_data({rx_control_phy,rx_parallel_data_phy}),
        .rx_rd_en(rx_rden),
        .rx_rd_data({rx_control,rx_parallel_data}),
        .tx_empty(tx_empty),
        .tx_pempty(tx_pempty),
        .tx_full(tx_full),
        .tx_pfull(tx_pfull),
        .rx_empty(rx_empty),
        .rx_pempty(rx_pempty),
        .rx_full(rx_full),
        .rx_pfull(rx_pfull),
        .tx_latency_adj(tx_path_delay_data),
        .rx_latency_adj(rx_path_delay_data),
        .rx_bit_slip(rx_bitslip)
    );
end else begin
    assign tx_path_delay_data = 22'h0;
    assign rx_path_delay_data = 22'h0;
    assign tx_parallel_data_phy = tx_parallel_data;
    assign tx_control_phy = tx_control;
    assign tvalid_phy = tvalid;
    assign rx_parallel_data = rx_parallel_data_phy;
    assign rx_control = rx_control_phy;
    assign tx_empty = tx_empty_phy;
    assign tx_pempty = tx_pempty_phy;
    assign tx_pfull = tx_pfull_phy;
    assign tx_full = tx_full_phy;
    assign rx_empty = rx_empty_phy;
    assign rx_pempty = rx_pempty_phy;
    assign rx_pfull = rx_pfull_phy;
    assign rx_full = rx_full_phy;
end
endgenerate

endmodule

