# Module name strings
HWTCL_MODULE_DISPLAY_NAME = Arria 10 External Memory Interfaces Calibration Slave/Helper component
HWTCL_MODULE_DESCRIPTION = This component instantiates components that serve as slaves to the EMIF calibration processor. It is intended for internal use only.

# Clock Frequency
PARAM_ENABLE_SOFT_RAM_NAME = Enable soft RAM for calibration code expansion
PARAM_ENABLE_SOFT_RAM_DESCRIPTION = Enable soft RAM for calibration code expansion

# Enable/disable JTAG UART
PARAM_ENABLE_JTAG_UART_NAME = Enable JTAG UART for Debug Output
PARAM_ENABLE_JTAG_UART_DESCRIPTION = Enable JTAG UART for Debug Output of Calibration

