# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Mon Jul 21 13:16:49 MYT 2014
# DO NOT MODIFY


# 
# altera_modular_adc_sample_store "Altera Modular ADC Sample Storage core" v1.0
# Altera Corporation 2014.07.21.13:16:49
# Altera Modular ADC - Sample Storage core
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.0


# 
# module altera_modular_adc_dual_sync
# 
set_module_property DESCRIPTION "Altera Modular ADC - Dual ADC Synchronizer core"
set_module_property NAME altera_modular_adc_dual_sync
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Peripherals"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Modular ADC Dual Sync core Intel FPGA IP"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_modular_adc_dual_sync
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_modular_adc_dual_sync.v VERILOG PATH altera_modular_adc_dual_sync.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_modular_adc_dual_sync
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_modular_adc_dual_sync.v VERILOG PATH altera_modular_adc_dual_sync.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1

# 
# connection point sync_handshake 1
# 
add_interface sync_handshake_1 avalon_streaming end
set_interface_property sync_handshake_1 associatedClock clock
set_interface_property sync_handshake_1 associatedReset reset_sink
set_interface_property sync_handshake_1 dataBitsPerSymbol 8
set_interface_property sync_handshake_1 errorDescriptor ""
set_interface_property sync_handshake_1 firstSymbolInHighOrderBits true
set_interface_property sync_handshake_1 maxChannel 0
set_interface_property sync_handshake_1 readyLatency 0
set_interface_property sync_handshake_1 ENABLED true
set_interface_property sync_handshake_1 EXPORT_OF ""
set_interface_property sync_handshake_1 PORT_NAME_MAP ""
set_interface_property sync_handshake_1 CMSIS_SVD_VARIABLES ""
set_interface_property sync_handshake_1 SVD_ADDRESS_GROUP ""

add_interface_port sync_handshake_1 sync_1_valid valid Input 1
add_interface_port sync_handshake_1 sync_1_ready ready Output 1


# 
# connection point sync_handshake 2
# 
add_interface sync_handshake_2 avalon_streaming end
set_interface_property sync_handshake_2 associatedClock clock
set_interface_property sync_handshake_2 associatedReset reset_sink
set_interface_property sync_handshake_2 dataBitsPerSymbol 8
set_interface_property sync_handshake_2 errorDescriptor ""
set_interface_property sync_handshake_2 firstSymbolInHighOrderBits true
set_interface_property sync_handshake_2 maxChannel 0
set_interface_property sync_handshake_2 readyLatency 0
set_interface_property sync_handshake_2 ENABLED true
set_interface_property sync_handshake_2 EXPORT_OF ""
set_interface_property sync_handshake_2 PORT_NAME_MAP ""
set_interface_property sync_handshake_2 CMSIS_SVD_VARIABLES ""
set_interface_property sync_handshake_2 SVD_ADDRESS_GROUP ""

add_interface_port sync_handshake_2 sync_2_valid valid Input 1
add_interface_port sync_handshake_2 sync_2_ready ready Output 1

