# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.0
# Thu Jan 23 14:18:14 MYT 2014
# DO NOT MODIFY


# 
# altera_hps_emac_interface_splitter "Altera HPS Emac Interface Splitter" v1.0
# Altera Corporation 2014.01.23.14:18:14
# Altera HPS Emac Interface Splitter core
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module altera_hps_emac_interface_splitter
# 
set_module_property DESCRIPTION "Altera HPS Emac Interface Splitter core"
set_module_property NAME altera_hps_emac_interface_splitter
set_module_property VERSION 18.1
set_module_property INTERNAL false
set_module_property GROUP "Processors and Peripherals/Hard Processor Components"
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera HPS Emac Interface Splitter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaboration
set_module_property VALIDATION_CALLBACK "validate"
set_module_property supported_device_families {{Stratix 10} {Arria 10} {Arria V} {Cyclone V}}


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_hps_emac_interface_splitter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_hps_emac_interface_splitter.v VERILOG PATH altera_hps_emac_interface_splitter.v TOP_LEVEL_FILE
add_fileset_file altera_hps_emac_interface_splitter_csr.v VERILOG PATH altera_hps_emac_interface_splitter_csr.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_hps_emac_interface_splitter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_hps_emac_interface_splitter.v VERILOG PATH altera_hps_emac_interface_splitter.v
add_fileset_file altera_hps_emac_interface_splitter_csr.v VERILOG PATH altera_hps_emac_interface_splitter_csr.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL altera_hps_emac_interface_splitter
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_hps_emac_interface_splitter.v VERILOG PATH altera_hps_emac_interface_splitter.v
add_fileset_file altera_hps_emac_interface_splitter_csr.v VERILOG PATH altera_hps_emac_interface_splitter_csr.v

#
# link to datasheet of component -- documentation of this component to be updated as part of embedded IP user guide 
#
add_documentation_link {Data Sheet } {http://www.altera.com/literature/ug/ug_embedded_ip.pdf}


# 
# parameters
# 
add_parameter MAC_SPEED_CSR_ENABLE INTEGER 1
set_parameter_property MAC_SPEED_CSR_ENABLE DEFAULT_VALUE 1
set_parameter_property MAC_SPEED_CSR_ENABLE DISPLAY_NAME MAC_SPEED_CSR_ENABLE
set_parameter_property MAC_SPEED_CSR_ENABLE TYPE INTEGER
set_parameter_property MAC_SPEED_CSR_ENABLE DERIVED true
set_parameter_property MAC_SPEED_CSR_ENABLE VISIBLE true
set_parameter_property MAC_SPEED_CSR_ENABLE UNITS None
set_parameter_property MAC_SPEED_CSR_ENABLE HDL_PARAMETER true

# SYSTEM_INFO parameter to obtain device_family
add_parameter DEVICE_FAMILY string ""
set_parameter_property DEVICE_FAMILY SYSTEM_INFO {DEVICE_FAMILY}
set_parameter_property DEVICE_FAMILY VISIBLE false

# 
# display items
# 

proc is_arriav_cyclonev {parameter} {
    if {[get_parameter_value $parameter] == "Arria V"} {
        return 1
    } elseif {[get_parameter_value $parameter] == "Cyclone V"} {
        return 1
    } else {
        return 0
    }
}

proc elaboration {} {
    if { [is_arriav_cyclonev DEVICE_FAMILY] } {
        
        set_parameter_value MAC_SPEED_CSR_ENABLE 1

        # connection point peri_clock
        add_interface peri_clock clock end
        add_interface_port peri_clock clk clk Input 1
        set_interface_property peri_clock ENABLED true

        # connection point peri_reset
        add_interface peri_reset reset end
        add_interface_port peri_reset rst_n reset_n Input 1
        set_interface_property peri_reset associatedClock peri_clock
        set_interface_property peri_reset synchronousEdges DEASSERT
        set_interface_property peri_reset ENABLED true

        # connection point avalon_slave
        add_interface avalon_slave avalon end
        set_interface_property avalon_slave addressUnits WORDS
        set_interface_property avalon_slave associatedClock peri_clock
        set_interface_property avalon_slave associatedReset peri_reset
        set_interface_property avalon_slave bitsPerSymbol 8
        set_interface_property avalon_slave burstOnBurstBoundariesOnly false
        set_interface_property avalon_slave burstcountUnits WORDS
        set_interface_property avalon_slave explicitAddressSpan 0
        set_interface_property avalon_slave holdTime 0
        set_interface_property avalon_slave linewrapBursts false
        set_interface_property avalon_slave maximumPendingReadTransactions 0
        set_interface_property avalon_slave maximumPendingWriteTransactions 0
        set_interface_property avalon_slave readLatency 1
        set_interface_property avalon_slave readWaitStates 0
        set_interface_property avalon_slave readWaitTime 0
        set_interface_property avalon_slave setupTime 0
        set_interface_property avalon_slave timingUnits Cycles
        set_interface_property avalon_slave writeWaitTime 0
        set_interface_property avalon_slave ENABLED true

        add_interface_port avalon_slave read read Input 1
        add_interface_port avalon_slave write write Input 1
        add_interface_port avalon_slave writedata writedata Input 32
        add_interface_port avalon_slave readdata readdata Output 32
        add_interface_port avalon_slave addr address Input 1
        set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
        set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
        set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
        set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

        # connection point emac
        add_interface emac conduit end
        set_interface_property emac associatedClock ""
        set_interface_property emac associatedReset ""
        set_interface_property emac ENABLED true
        set_interface_property emac EXPORT_OF ""
        set_interface_property emac PORT_NAME_MAP ""
        set_interface_property emac CMSIS_SVD_VARIABLES ""
        set_interface_property emac SVD_ADDRESS_GROUP ""

        add_interface_port emac phy_txd_o phy_txd_o Input 8
        add_interface_port emac phy_txen_o phy_txen_o Input 1
        add_interface_port emac phy_txer_o phy_txer_o Input 1
        add_interface_port emac phy_mac_speed_o phy_mac_speed_o Input 2
        add_interface_port emac mdo_o gmii_mdo_o Input 1
        add_interface_port emac mdo_o_e gmii_mdo_o_e Input 1
        add_interface_port emac ptp_pps_o ptp_pps_o Input 1
        add_interface_port emac phy_rxdv_i phy_rxdv_i Output 1
        add_interface_port emac phy_rxer_i phy_rxer_i Output 1
        add_interface_port emac phy_rxd_i phy_rxd_i Output 8
        add_interface_port emac phy_col_i phy_col_i Output 1
        add_interface_port emac phy_crs_i phy_crs_i Output 1
        add_interface_port emac mdi_i gmii_mdi_i Output 1
        add_interface_port emac ptp_aux_ts_trig_i ptp_aux_ts_trig_i Output 1
        add_interface_port emac ptp_tstmp_data ptp_tstmp_data Input 1
        add_interface_port emac ptp_tstmp_en ptp_tstmp_en Input 1

        set_port_property phy_mac_speed_o termination true
        set_port_property phy_mac_speed_o termination_value 0
        set_port_property ptp_tstmp_data termination true 
        set_port_property ptp_tstmp_data termination_value 0 
        set_port_property ptp_tstmp_en termination true
        set_port_property ptp_tstmp_en termination_value 0


        # 
        # connection point ptp
        # 
        add_interface ptp conduit end
        set_interface_property ptp associatedClock ""
        set_interface_property ptp associatedReset ""
        set_interface_property ptp ENABLED true
        set_interface_property ptp EXPORT_OF ""
        set_interface_property ptp PORT_NAME_MAP ""
        set_interface_property ptp CMSIS_SVD_VARIABLES ""
        set_interface_property ptp SVD_ADDRESS_GROUP ""

        add_interface_port ptp ptp_aux_ts_trig_in ptp_aux_ts_trig_i Input 1
        add_interface_port ptp ptp_pps_out ptp_pps_o Output 1

    } else {

        set_parameter_value MAC_SPEED_CSR_ENABLE 0
       
        # connection point peri_clock
        add_interface peri_clock clock end
        add_interface_port peri_clock clk clk Input 1
        set_interface_property peri_clock ENABLED true
        set_port_property clk termination true
        set_port_property clk termination_value 0

        # connection point peri_reset
        add_interface peri_reset reset end
        add_interface_port peri_reset rst_n reset_n Input 1
        set_interface_property peri_reset associatedClock peri_clock
        set_interface_property peri_reset synchronousEdges DEASSERT
        set_interface_property peri_reset ENABLED true
        set_port_property rst_n termination true
        set_port_property rst_n termination_value 0

        # connection point avalon_slave
        add_interface avalon_slave avalon end
        set_interface_property avalon_slave addressUnits WORDS
        set_interface_property avalon_slave associatedClock peri_clock
        set_interface_property avalon_slave associatedReset peri_reset
        set_interface_property avalon_slave bitsPerSymbol 8
        set_interface_property avalon_slave burstOnBurstBoundariesOnly false
        set_interface_property avalon_slave burstcountUnits WORDS
        set_interface_property avalon_slave explicitAddressSpan 0
        set_interface_property avalon_slave holdTime 0
        set_interface_property avalon_slave linewrapBursts false
        set_interface_property avalon_slave maximumPendingReadTransactions 0
        set_interface_property avalon_slave maximumPendingWriteTransactions 0
        set_interface_property avalon_slave readLatency 1
        set_interface_property avalon_slave readWaitStates 0
        set_interface_property avalon_slave readWaitTime 0
        set_interface_property avalon_slave setupTime 0
        set_interface_property avalon_slave timingUnits Cycles
        set_interface_property avalon_slave writeWaitTime 0
        set_interface_property avalon_slave ENABLED true

        add_interface_port avalon_slave read read Input 1
        add_interface_port avalon_slave write write Input 1
        add_interface_port avalon_slave writedata writedata Input 32
        add_interface_port avalon_slave readdata readdata Output 32
        add_interface_port avalon_slave addr address Input 1
        set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
        set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
        set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
        set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0
        set_port_property read      termination true
        set_port_property write     termination true
        set_port_property writedata termination true
        set_port_property addr      termination true
        set_port_property readdata  termination true
        set_port_property read      termination_value 0
        set_port_property write     termination_value 0
        set_port_property writedata termination_value 0
        set_port_property addr      termination_value 0
        
        # connection point emac
        add_interface emac conduit end
        set_interface_property emac associatedClock ""
        set_interface_property emac associatedReset ""
        set_interface_property emac ENABLED true
        set_interface_property emac EXPORT_OF ""
        set_interface_property emac PORT_NAME_MAP ""
        set_interface_property emac CMSIS_SVD_VARIABLES ""
        set_interface_property emac SVD_ADDRESS_GROUP ""

        add_interface_port emac phy_txd_o phy_txd_o Input 8
        add_interface_port emac phy_txen_o phy_txen_o Input 1
        add_interface_port emac phy_txer_o phy_txer_o Input 1
        add_interface_port emac phy_mac_speed_o phy_mac_speed_o Input 2
        add_interface_port emac mdo_o gmii_mdo_o Input 1
        add_interface_port emac mdo_o_e gmii_mdo_o_e Input 1
        add_interface_port emac ptp_pps_o ptp_pps_o Input 1
        add_interface_port emac phy_rxdv_i phy_rxdv_i Output 1
        add_interface_port emac phy_rxer_i phy_rxer_i Output 1
        add_interface_port emac phy_rxd_i phy_rxd_i Output 8
        add_interface_port emac phy_col_i phy_col_i Output 1
        add_interface_port emac phy_crs_i phy_crs_i Output 1
        add_interface_port emac mdi_i gmii_mdi_i Output 1
        add_interface_port emac ptp_aux_ts_trig_i ptp_aux_ts_trig_i Output 1
        add_interface_port emac ptp_tstmp_data ptp_tstmp_data Input 1
        add_interface_port emac ptp_tstmp_en ptp_tstmp_en Input 1

        # 
        # connection point ptp
        # 
        add_interface ptp conduit end
        set_interface_property ptp associatedClock ""
        set_interface_property ptp associatedReset ""
        set_interface_property ptp ENABLED true
        set_interface_property ptp EXPORT_OF ""
        set_interface_property ptp PORT_NAME_MAP ""
        set_interface_property ptp CMSIS_SVD_VARIABLES ""
        set_interface_property ptp SVD_ADDRESS_GROUP ""

        add_interface_port ptp ptp_aux_ts_trig_in ptp_aux_ts_trig_i Input 1
        add_interface_port ptp ptp_pps_out ptp_pps_o Output 1
        add_interface_port ptp ptp_tstmp_data_out ptp_tstmp_data Output 1
        add_interface_port ptp ptp_tstmp_en_out ptp_tstmp_en Output 1
    }
}






# 
# connection point emac_gtx_clk
# 
add_interface emac_gtx_clk clock end
add_interface_port emac_gtx_clk phy_txclk_o clk Input 1
set_interface_property emac_gtx_clk ENABLED true



# 
# connection point emac_tx_clk_in
# 
add_interface emac_tx_clk_in clock start
set_interface_property emac_tx_clk_in associatedDirectClock ""
set_interface_property emac_tx_clk_in clockRate 0
set_interface_property emac_tx_clk_in clockRateKnown false
set_interface_property emac_tx_clk_in ENABLED true
set_interface_property emac_tx_clk_in EXPORT_OF ""
set_interface_property emac_tx_clk_in PORT_NAME_MAP ""
set_interface_property emac_tx_clk_in CMSIS_SVD_VARIABLES ""
set_interface_property emac_tx_clk_in SVD_ADDRESS_GROUP ""

add_interface_port emac_tx_clk_in clk_tx_i clk Output 1


# 
# connection point emac_rx_clk_in
# 
add_interface emac_rx_clk_in clock start
set_interface_property emac_rx_clk_in associatedDirectClock ""
set_interface_property emac_rx_clk_in clockRate 0
set_interface_property emac_rx_clk_in clockRateKnown false
set_interface_property emac_rx_clk_in ENABLED true
set_interface_property emac_rx_clk_in EXPORT_OF ""
set_interface_property emac_rx_clk_in PORT_NAME_MAP ""
set_interface_property emac_rx_clk_in CMSIS_SVD_VARIABLES ""
set_interface_property emac_rx_clk_in SVD_ADDRESS_GROUP ""

add_interface_port emac_rx_clk_in clk_rx_i clk Output 1


# 
# connection point emac_tx_reset
# 
add_interface emac_tx_reset reset end
set_interface_property emac_tx_reset associatedClock emac_gtx_clk
set_interface_property emac_tx_reset synchronousEdges DEASSERT
set_interface_property emac_tx_reset ENABLED true

add_interface_port emac_tx_reset rst_tx_n_o reset_n Input 1


# 
# connection point emac_rx_reset
# 
add_interface emac_rx_reset reset end
set_interface_property emac_rx_reset associatedClock emac_rx_clk_in
set_interface_property emac_rx_reset synchronousEdges DEASSERT
set_interface_property emac_rx_reset ENABLED true

add_interface_port emac_rx_reset rst_rx_n_o reset_n Input 1


# 
# connection point hps_gmii
# 
add_interface hps_gmii conduit end
set_interface_property hps_gmii associatedClock ""
set_interface_property hps_gmii associatedReset ""
set_interface_property hps_gmii ENABLED true
set_interface_property hps_gmii EXPORT_OF ""
set_interface_property hps_gmii PORT_NAME_MAP ""
set_interface_property hps_gmii CMSIS_SVD_VARIABLES ""
set_interface_property hps_gmii SVD_ADDRESS_GROUP ""

add_interface_port hps_gmii mac_tx_clk_i phy_tx_clk_i Input 1
add_interface_port hps_gmii mac_rx_clk phy_rx_clk_i Input 1
add_interface_port hps_gmii mac_rxdv phy_rxdv_i Input 1
add_interface_port hps_gmii mac_rxer phy_rxer_i Input 1
add_interface_port hps_gmii mac_rxd phy_rxd_i Input 8
add_interface_port hps_gmii mac_col phy_col_i Input 1
add_interface_port hps_gmii mac_crs phy_crs_i Input 1
add_interface_port hps_gmii mac_tx_clk_o phy_tx_clk_o Output 1
add_interface_port hps_gmii mac_rst_tx_n rst_tx_n Output 1
add_interface_port hps_gmii mac_rst_rx_n rst_rx_n Output 1
add_interface_port hps_gmii mac_txd phy_txd_o Output 8
add_interface_port hps_gmii mac_txen phy_txen_o Output 1
add_interface_port hps_gmii mac_txer phy_txer_o Output 1
add_interface_port hps_gmii mac_speed phy_mac_speed_o Output 2


# 
# connection point mdio
# 
add_interface mdio conduit end
set_interface_property mdio associatedClock ""
set_interface_property mdio associatedReset ""
set_interface_property mdio ENABLED true
set_interface_property mdio EXPORT_OF ""
set_interface_property mdio PORT_NAME_MAP ""
set_interface_property mdio CMSIS_SVD_VARIABLES ""
set_interface_property mdio SVD_ADDRESS_GROUP ""

add_interface_port mdio mdi_in gmii_mdi_i Input 1
add_interface_port mdio mdo_out gmii_mdo_o Output 1
add_interface_port mdio mdo_out_en gmii_mdo_o_e Output 1



proc validate {} {

    if {[get_parameter_value MAC_SPEED_CSR_ENABLE] == 1} {
		set_module_assignment embeddedsw.dts.vendor "altr"
  		set_module_assignment embeddedsw.dts.group "splitter"
		set_module_assignment embeddedsw.dts.name "splitter"
  		set_module_assignment embeddedsw.dts.compatible "altr,emac-splitter-1.0"
	}
}


## Add documentation links for user guide and/or release notes
add_documentation_link "User Guide" https://documentation.altera.com/#/link/sfo1400787952932/iga1434499254579
