# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# $Id: //acds/rel/18.1std/ip/sld/mm/altera_avalon_transacto/altera_avalon_transacto_hw.tcl#1 $
# $Revision: #1 $
# $Date: 2018/07/18 $

# TCL File Generated by Component Editor 14.0
# Mon Jan 27 17:35:07 PST 2014
# DO NOT MODIFY


# 
# altera_avalon_transacto "Altera Avalon Transacto" v1.0
#  2014.01.27.17:35:07
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module altera_avalon_transacto
# 
set_module_property DESCRIPTION "Altera Avalon Transacto"
set_module_property NAME altera_avalon_transacto
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Altera Corporation"
set_module_property GROUP "Bridges and Adapters/Streaming"
set_module_property DISPLAY_NAME "Altera Avalon Transacto"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_avalon_transacto
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_transacto.sv SYSTEM_VERILOG PATH altera_avalon_transacto.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_avalon_transacto
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_transacto.sv SYSTEM_VERILOG PATH altera_avalon_transacto.sv

# To do: add SIM_VHDL fileset.

# 
# parameters
# 
add_parameter DATA_W INTEGER 32
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W ENABLED false
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W HDL_PARAMETER true
add_parameter MM_ADDR_WIDTH INTEGER 32
set_parameter_property MM_ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property MM_ADDR_WIDTH DISPLAY_NAME MM_ADDR_WIDTH
set_parameter_property MM_ADDR_WIDTH TYPE INTEGER
set_parameter_property MM_ADDR_WIDTH ENABLED false
set_parameter_property MM_ADDR_WIDTH UNITS None
set_parameter_property MM_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset user_reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 read read Output 1
add_interface_port m0 write write Output 1
add_interface_port m0 writedata writedata Output DATA_W
add_interface_port m0 readdata readdata Input DATA_W
add_interface_port m0 address address Output MM_ADDR_WIDTH
add_interface_port m0 byteenable byteenable Output DATA_W/8
add_interface_port m0 waitrequest waitrequest Input 1
add_interface_port m0 readdatavalid readdatavalid Input 1

set_interface_assignment m0 debug.controlledBy h2t 
set_interface_assignment m0 debug.providesServices master
set_interface_assignment m0 debug.typeName altera_jtag_avalon_master.master

# 
# connection point h2t
# 
add_interface h2t avalon_streaming end
set_interface_property h2t associatedClock clock
set_interface_property h2t associatedReset debug_reset
set_interface_property h2t dataBitsPerSymbol 8
set_interface_property h2t errorDescriptor ""
set_interface_property h2t firstSymbolInHighOrderBits true
set_interface_property h2t maxChannel 0
set_interface_property h2t readyLatency 0
set_interface_property h2t ENABLED true
set_interface_property h2t EXPORT_OF ""
set_interface_property h2t PORT_NAME_MAP ""
set_interface_property h2t CMSIS_SVD_VARIABLES ""
set_interface_property h2t SVD_ADDRESS_GROUP ""

add_interface_port h2t h2t_valid valid Input 1
add_interface_port h2t h2t_sop startofpacket Input 1
add_interface_port h2t h2t_eop endofpacket Input 1
add_interface_port h2t h2t_data data Input DATA_W
add_interface_port h2t h2t_ready ready Output 1


# 
# connection point debug_reset
# 
add_interface debug_reset reset end
set_interface_property debug_reset associatedClock clock
set_interface_property debug_reset synchronousEdges DEASSERT
set_interface_property debug_reset ENABLED true
set_interface_property debug_reset EXPORT_OF ""
set_interface_property debug_reset PORT_NAME_MAP ""
set_interface_property debug_reset CMSIS_SVD_VARIABLES ""
set_interface_property debug_reset SVD_ADDRESS_GROUP ""

add_interface_port debug_reset debug_reset reset Input 1


# 
# connection point user_reset
# 
add_interface user_reset reset end
set_interface_property user_reset associatedClock clock
set_interface_property user_reset synchronousEdges DEASSERT
set_interface_property user_reset ENABLED true
set_interface_property user_reset EXPORT_OF ""
set_interface_property user_reset PORT_NAME_MAP ""
set_interface_property user_reset CMSIS_SVD_VARIABLES ""
set_interface_property user_reset SVD_ADDRESS_GROUP ""

add_interface_port user_reset user_reset reset Input 1


# 
# connection point t2h
# 
add_interface t2h avalon_streaming start
set_interface_property t2h associatedClock clock
set_interface_property t2h associatedReset debug_reset
set_interface_property t2h dataBitsPerSymbol 8
set_interface_property t2h errorDescriptor ""
set_interface_property t2h firstSymbolInHighOrderBits true
set_interface_property t2h maxChannel 0
set_interface_property t2h readyLatency 0
set_interface_property t2h ENABLED true
set_interface_property t2h EXPORT_OF ""
set_interface_property t2h PORT_NAME_MAP ""
set_interface_property t2h CMSIS_SVD_VARIABLES ""
set_interface_property t2h SVD_ADDRESS_GROUP ""

add_interface_port t2h t2h_valid valid Output 1
add_interface_port t2h t2h_sop startofpacket Output 1
add_interface_port t2h t2h_eop endofpacket Output 1
add_interface_port t2h t2h_data data Output DATA_W
add_interface_port t2h t2h_ready ready Input 1

set_interface_assignment h2t debug.interfaceGroup {associatedT2h t2h}

