
#Groups
ALL_GRP =   All



#Function display names
SINCOS_DISPLAY_NAME    =   Sin Cos
ATAN2_DISPLAY_NAME    =   ATan2
VECTRANSLATE_DISPLAY_NAME    =   Vector Translate
VECROTATE_DISPLAY_NAME        =   Vector Rotate

#Other display name strings
SINGLE_REP_NAME = Single
DOUBLE_REP_NAME = Double
CUSTOM_REP_NAME = Custom

FREQUENCY_REP_NAME = Frequency
MANUAL_DSPS_NAME = Manually Specify DSP Registers
LATENCY_REP_NAME = Latency
COMBINED_REP_NAME = Combined


# ADD_DISPLAY_NAME        =   a + b  
# SUB_DISPLAY_NAME        =   a - b    
# MUL_DISPLAY_NAME        =   a \u00d7 b
# DIV_DISPLAY_NAME        =   a / b  
# INV_DISPLAY_NAME        =   1 / a    
# ABS_DISPLAY_NAME        =   |a|       
# MIN_DISPLAY_NAME        =   min(a,b)       
# MAX_DISPLAY_NAME        =   max(ab,b)   
# LT_DISPLAY_NAME         =   a < b     
# LE_DISPLAY_NAME         =   a <= b     
# EQ_DISPLAY_NAME         =   a = b     
# NEQ_DISPLAY_NAME        =   a != b        
# GT_DISPLAY_NAME         =   a > b     
# GE_DISPLAY_NAME         =   a >= b     
# SQRT_DISPLAY_NAME       =   \u221a a       
# INV_SQRT_DISPLAY_NAME   =   1 / \u221a a       
# EXP_DISPLAY_NAME        =   e \u2090      
# LOG_DISPLAY_NAME        =   LOG        
# LN_DISPLAY_NAME         =   LN     
# SIN_DISPLAY_NAME        =   SIN        
# COS_DISPLAY_NAME        =   COS        
# TAN_DISPLAY_NAME        =   TAN        
# ASIN_DISPLAY_NAME       =   ASIN       
# ACOS_DISPLAY_NAME       =   ACOS       
# ATAN_DISPLAY_NAME       =   ATAN       
# FXP_FP_DISPLAY_NAME     =   FXP_FP     
# FP_FXP_DISPLAY_NAME     =   FP_FXP     