# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.



proc HDL_autogenerated_files_for_decoder {entity} {
    
    set list_of_generated_files [list ]

    set m                   [ get_parameter_value BITSPERSYMBOL ]   
    set check               [ get_parameter_value CHECK ]
    set channel             [ get_parameter_value CHANNEL ]
    set irrpol              [ get_parameter_value IRRPOL ]
    set n                   [ get_parameter_value N ]
    set par                 [ get_parameter_value PAR ]
    set bm_speed            [ get_parameter_value BMSPEED]
    set useram              [ get_parameter_value USERAM]
    set useeccforram        [ get_parameter_value USEECCFORRAM]
    set usetruedualportram  [ get_parameter_value USETRUEDUALRAM]
    set usebkpwithram       [ get_parameter_value USE_BKP]
    set usebypass           [ get_parameter_value USE_BYPASS]
    set usesync             [ get_parameter_value USE_SYNC]

    set k              [expr $n - $check]
    set t              [expr $check>>1]
    set max_n          [expr (1<<$m)-1]
    
    set decoder_clocks [expr $n/$par]
    if {$n > $decoder_clocks*$par} {incr decoder_clocks}


    if {$bm_speed<4} {
        set ite_per_core  [expr $decoder_clocks/$channel]
        set use_riBM  1
    } else {
        set ite_per_core  [expr $decoder_clocks/2/$channel]
        set use_riBM  0
    }
    
    if {$usebypass==1 || $channel>1} {
        set usesync 0
    }
    
    set nb_BMcores    [expr $check/$ite_per_core]
    if {$check > $nb_BMcores*$ite_per_core} {incr nb_BMcores}

    set hexa_charPerWord              [expr {($m - 1) / 4 + 1}]
    

    
    set AlphaToThePower                 [list ]
    for {set ii 0} {$ii < [expr $max_n+1]} {incr ii} {lappend AlphaToThePower 1}
    set AlphaToThePowerMinus           $AlphaToThePower
    set ExponentOf                     $AlphaToThePower
    set InverseOf                      $AlphaToThePower
    set InverseOf_hexa                 $AlphaToThePower
    

    
    lset AlphaToThePower       0 1
    lset AlphaToThePowerMinus  $max_n  1
   
    
    for {set ii 1} {$ii < [expr $max_n+1]} {incr ii} {
        set prevAlphato             [lindex $AlphaToThePower [expr $ii-1]]
        if {($prevAlphato>>($m-1))==1} {
            set newAlphato              [expr ($prevAlphato<<1) ^  $irrpol  ]
        } else {
            set newAlphato              [expr ($prevAlphato<<1) ]
        }
        
        lset AlphaToThePower      $ii                $newAlphato
        lset AlphaToThePowerMinus [expr $max_n-$ii]  $newAlphato
        lset ExponentOf           $newAlphato        $ii
    }

    
    lset InverseOf 0 0
    lset InverseOf_hexa 0 [format "%0[expr $hexa_charPerWord]X"  0]
    for {set ii 1} {$ii < [expr $max_n+1]} {incr ii} {
        set inv  [lindex $AlphaToThePower [expr $max_n-[lindex $ExponentOf $ii]]]
        lset InverseOf $ii $inv
        
        set inv_hexa [format "%0[expr $hexa_charPerWord]X"  $inv]
        lset InverseOf_hexa $ii $inv_hexa
    }    
    
    
    set cwd [pwd]
    set temp_dir  [create_temp_file ""] 
    file mkdir $temp_dir
    cd $temp_dir
    
    
    #----------------------------------------------------------------------------------------------------------------------------
    send_message info "----Writing rsx_bm_auto.vhd"
    set file_name "$temp_dir/rsx_bm_auto.vhd"
    lappend list_of_generated_files $file_name
    set f_handle [open $file_name w+]
    set text ""

    if {$use_riBM == 1} {
        set delta theta
    } else {
        set delta delta
    }
    
    
    append text     "\nLIBRARY ieee;\nUSE ieee.std_logic_1164.all;\nUSE ieee.std_logic_unsigned.all;\nUSE ieee.std_logic_arith.all;\n\n"
    append text     "USE work.rsx_parameters.all;\nUSE work.rsx_package.all;\nUSE work.rsx_roots.all;\n\n"
    append text     "ENTITY rsx_bm_auto IS\n  PORT (\n         sysclk, reset, enable : IN STD_LOGIC;\n         start : IN STD_LOGIC;\n"
    append text     "         bm_ready : OUT STD_LOGIC;\n"
    append text     "         syndromes : IN syndromevector;\n"
    append text     "         error_locator : OUT chien_in_vector;\n         error_evaluator : OUT chien_in_vector;\n"
    append text     "         number_errors : OUT nb_errors_type;\n         done : OUT STD_LOGIC\n"
    append text     "        );\nEND rsx_bm_auto;\n\n"
    append text     "ARCHITECTURE rtlauto OF rsx_bm_auto IS\n\n"
    append text     "    signal syndromes_ini : syndromevector;\n    signal bdsprev_ini : errorvector;\n    signal bds_ini : errorvector;\n"
    append text     "    signal zerocnt_ini : STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n    signal one${delta} : STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
    for {set ii 1} {$ii < [expr $nb_BMcores+1]} {incr ii} {
        if {$use_riBM == 0} {
            append text     "    signal syndromesnode_$ii : syndromevector;\n"
        } else {
            append text     "    signal deltaX_$ii, deltaXprev_$ii : syndromevector;\n"
        }
        append text     "    signal ${delta}_$ii : STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
        append text     "    signal bds_$ii, bdsprevnode_$ii : errorvector;\n"
        append text     "    signal llnumber_$ii : STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n"
    }
    append text     "    signal bdsout : errorvector;\n"
    append text     "    signal omegaout : errorvector;\n"
    append text     "    signal errorsout : STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n"
    append text     "    signal stage : STD_LOGIC_VECTOR ($nb_BMcores DOWNTO 1);\n"
    append text     "    signal stageout : STD_LOGIC;\n"
    append text     "    signal syndromesshift : errorvector;\n\n"
    append text     "    signal get_inv_of : inv_alpha_type := (others=>(others=>'0'));\n"
    append text     "    signal value_of_inv : inv_alpha_type := (others=>(others=>'0'));\n"
    append text     "    signal get_inv_of_valid : STD_LOGIC_VECTOR (nbinvmax DOWNTO 1) := (others=>'0');\n\n"
    
    append text     "  component rsx_bm_pe$bm_speed \n"
    append text     "  GENERIC (startloop : integer := 2;endloop : integer := 6);\n"
    append text     "  PORT (\n"
    append text     "        sysclk, reset, enable : IN STD_LOGIC;\n"
    append text     "        start : IN STD_LOGIC;\n"
    append text     "        bm_ready : OUT STD_LOGIC;\n"
    if {$use_riBM == 0} {
        append text     "        syndromesin : IN syndromevector;\n"
    } else {
        append text     "        deltaXin, deltaXprevin : IN syndromevector;\n"
    }
    append text     "        bdsin, bdsprevin : IN errorvector;\n"
    append text     "        llnumberin : IN STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n"
    append text     "        ${delta}in : IN STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
    if {$use_riBM == 0} {
        append text     "		 syndromesout : OUT syndromevector;\n"
        append text     "        get_inv_of : OUT STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
        append text     "        get_inv_of_valid : OUT STD_LOGIC;\n"
        append text     "        value_of_inv : IN STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
    } else {
        append text     "        deltaXout, deltaXprevout : OUT syndromevector;\n"
    }
    append text     "        bdsout, bdsprevout : OUT errorvector;\n"
    append text     "        llnumberout : OUT STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n"
    append text     "        ${delta}out : OUT STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
    append text     "        nextstage : OUT STD_LOGIC\n"
    append text     "        );\n"
    append text     "  end component;\n\n"

    if {$use_riBM == 0} {
        append text     "  component rsx_omega_pipe\n"
        append text     "  PORT (\n"
        append text     "        sysclk, reset, enable : IN STD_LOGIC;\n"
        append text     "        start : IN STD_LOGIC; -- start this stage\n"
        append text     "        syndromes : IN errorvector;\n"
        append text     "        bdsin : IN errorvector;\n"
        append text     "        errorsin : IN STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n"
        append text     "        bdsout : OUT errorvector;\n"
        append text     "        omegaout : OUT errorvector;\n"
        append text     "        errorsout : OUT STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n"
        append text     "        done : OUT STD_LOGIC -- start for next level\n"
        append text     "        );\n"
        append text     "  end component;\n\n"
 
        append text     "  component rsx_inverse_ROM\n"
        append text     "  GENERIC (\n"
        append text     "         nb_input : integer := 10\n"
        append text     "         );\n"
        append text     "  PORT (\n"
        append text     "          sysclk: IN STD_LOGIC;\n"
        append text     "          reset : IN STD_LOGIC;\n"
        append text     "          enable : IN STD_LOGIC;\n"
        append text     "          alpha : IN inv_alpha_type;\n"
        append text     "          read_enable : IN STD_LOGIC_VECTOR (nbinvmax DOWNTO 1);\n"
        append text     "          inverse_of_alpha : OUT inv_alpha_type\n"
        append text     "         );\n"
        append text     "   end component;\n\n"
    }
    if {$channel > 1} {
        append text     "  component rsx_bm_fifo\n"
        append text     "  PORT (\n"
        append text     "        sysclk, reset, enable : IN STD_LOGIC;\n"
        append text     "        start : IN STD_LOGIC; -- start this stage\n"
        append text     "        omegain : IN errorvector;\n"
        append text     "        bdsin : IN errorvector;\n"
        append text     "        errorsin : IN STD_LOGIC_VECTOR (errorcnt_width DOWNTO 1);\n\n"
        append text     "        bdsout : OUT chien_in_vector;\n"
        append text     "        omegaout : OUT chien_in_vector;\n"
        append text     "        errorsout : OUT nb_errors_type;\n"
        append text     "        done : OUT STD_LOGIC\n"
        append text     "        );\n"
        append text     "  end component;\n\n"
    }   
        
    append text     "BEGIN\n"
    append text     "  syndromes_ini(1)(m_bits DOWNTO 1) <= syndromes($check)(m_bits DOWNTO 1);\n"
    append text     "  gen_zerosyn: FOR k IN 1 TO [expr $check-1] GENERATE\n"
    append text     "  syndromes_ini(k+1)(m_bits DOWNTO 1) <= syndromes(k)(m_bits DOWNTO 1);\n  END GENERATE;\n"
    append text     "  bdsprev_ini(1)(m_bits DOWNTO 1) <= conv_std_logic_vector (1,m_bits);\n"
    append text     "  bds_ini(1)(m_bits DOWNTO 1) <= conv_std_logic_vector (ribm,m_bits);\n"
    append text     "  gen_bda: FOR k IN 2 TO bm_symbols GENERATE\n"
    append text     "  bdsprev_ini(k)(m_bits DOWNTO 1) <= conv_std_logic_vector (0,m_bits);\n"
    append text     "  bds_ini(k)(m_bits DOWNTO 1) <= conv_std_logic_vector (0,m_bits);\n  END GENERATE;"
    append text     "  zerocnt_ini <= conv_std_logic_vector(0,errorcnt_width);\n  one${delta} <= conv_std_logic_vector (1,m_bits);\n\n"

    append text     "  comp_round1: rsx_bm_pe$bm_speed\n"   
    if {$nb_BMcores==1} {
        append text     "  GENERIC MAP (startloop=>0,endloop=>[expr $check-1])\n"
    } else {
        append text     "  GENERIC MAP (startloop=>0,endloop=>[expr $ite_per_core-1])\n"
    }
    append text     "  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,\n"
    append text     "            start=>start,\n"
    append text     "            bm_ready=>bm_ready,\n"
    if {$use_riBM == 0} {
        append text     "            syndromesin=>syndromes_ini,\n"
    } else {
        append text     "            deltaXin=>syndromes_ini,\n"
        append text     "            deltaXprevin=>syndromes_ini,\n"
    }
    append text     "            bdsin=>bds_ini,\n"
    append text     "            bdsprevin=>bdsprev_ini,\n"
    append text     "            llnumberin=>zerocnt_ini,\n"
    append text     "            ${delta}in=>one${delta},\n"
    
    if {$use_riBM == 0} {
        append text     "            syndromesout=>syndromesnode_1,\n"
        append text     "            get_inv_of=>get_inv_of(1),\n"
        append text     "            get_inv_of_valid=>get_inv_of_valid(1),\n"
        append text     "            value_of_inv=>value_of_inv(1),\n"
    } else {
        append text     "            deltaXout=>deltaX_1,\n"
    }
    if {$nb_BMcores>1} {
        append text     "            ${delta}out=>${delta}_1,\n"
        append text     "            bdsprevout=>bdsprevnode_1,\n"
        if {$use_riBM == 1} {
            append text     "            deltaXprevout=>deltaXprev_1,\n"
        }
    }
    append text     "            bdsout=>bds_1,\n"
    append text     "            llnumberout=>llnumber_1,\n"
    append text     "            nextstage=>stage(1));\n\n"

    
    if {$nb_BMcores>2} {
        for {set ii 1} {$ii < [expr $nb_BMcores-1]} {incr ii} {
            append text     "  comp_round[expr $ii+1]: rsx_bm_pe$bm_speed\n"
            append text     "  GENERIC MAP (startloop=>[expr $ii*$ite_per_core],endloop=>[expr ($ii+1)*$ite_per_core-1])\n"
            append text     "  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,\n"
            append text     "            start=>stage($ii),\n"
            if {$use_riBM == 0} {
                append text     "            syndromesin=>syndromesnode_$ii,\n"
            } else {
                append text     "            deltaXin=>deltaX_$ii,\n"
                append text     "            deltaXprevin=>deltaXprev_$ii,\n"
            }
            append text     "            bdsin=>bds_$ii,\n"
            append text     "            bdsprevin=>bdsprevnode_$ii,\n"
            append text     "            llnumberin=>llnumber_$ii,\n"
            append text     "            ${delta}in=>${delta}_$ii,\n"
            
            if {$use_riBM == 0} {
                append text     "            syndromesout=>syndromesnode_[expr $ii+1],\n"
                append text     "            get_inv_of=>get_inv_of([expr $ii+1]),\n"
                append text     "            get_inv_of_valid=>get_inv_of_valid([expr $ii+1]),\n"
                append text     "            value_of_inv=>value_of_inv([expr $ii+1]),\n"
            } else {
                append text     "            deltaXout=>deltaX_[expr $ii+1],\n"
                append text     "            deltaXprevout=>deltaXprev_[expr $ii+1],\n"
            }
            append text     "            bdsout=>bds_[expr $ii+1],\n"
            append text     "            bdsprevout=>bdsprevnode_[expr $ii+1],\n"
            append text     "            llnumberout=>llnumber_[expr $ii+1],\n"
            append text     "            ${delta}out=>${delta}_[expr $ii+1],\n"
            append text     "            nextstage=>stage([expr $ii+1]));\n\n"
        }
    }
    
    if {$nb_BMcores>1} {
        append text     "  comp_round$nb_BMcores: rsx_bm_pe$bm_speed\n"
        append text     "  GENERIC MAP (startloop=>[expr ($nb_BMcores-1)*$ite_per_core],endloop=>[expr $check-1])\n"
        append text     "  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,\n"
        append text     "            start=>stage([expr $nb_BMcores-1]),\n"
        if {$use_riBM == 0} {
            append text     "            syndromesin=>syndromesnode_[expr $nb_BMcores-1],\n"
        } else {
            append text     "            deltaXin=>deltaX_[expr $nb_BMcores-1],\n"
            append text     "            deltaXprevin=>deltaXprev_[expr $nb_BMcores-1],\n"
        }
        append text     "            bdsin=>bds_[expr $nb_BMcores-1],\n"
        append text     "            bdsprevin=>bdsprevnode_[expr $nb_BMcores-1],\n"
        append text     "            llnumberin=>llnumber_[expr $nb_BMcores-1],\n"
        append text     "            ${delta}in=>${delta}_[expr $nb_BMcores-1],\n"
        if {$use_riBM == 0} {
            append text     "            syndromesout=>syndromesnode_$nb_BMcores,\n"
            append text     "            get_inv_of=>get_inv_of($nb_BMcores),\n"
            append text     "            get_inv_of_valid=>get_inv_of_valid($nb_BMcores),\n"
            append text     "            value_of_inv=>value_of_inv($nb_BMcores),\n"
            
        } else {
            append text     "            deltaXout=>deltaX_$nb_BMcores,\n"
        }
        append text     "            bdsout=>bds_$nb_BMcores,\n"
        append text     "            llnumberout=>llnumber_$nb_BMcores,\n"
        append text     "            nextstage=>stage($nb_BMcores));\n\n"
    }
    if {$use_riBM == 1} {
        append text     "  bdsout <= bds_$nb_BMcores;\n"
        if {$check>3} {
            append text     "  gen_omegaout: FOR k IN 1 TO bm_symbols GENERATE\n"
            append text     "    omegaout(k) <= deltaX_${nb_BMcores}(k+1);\n"
            append text     "  END GENERATE;\n"
        } else {
            append text     "  gen_omegaout: FOR k IN 1 TO 1 GENERATE\n"
            append text     "    omegaout(k) <= deltaX_${nb_BMcores}(k+1);\n"
            append text     "  END GENERATE;\n"   
            append text     "  omegaout(2) <= conv_std_logic_vector(0,m_bits);\n"
        }
        append text     "  errorsout <= llnumber_$nb_BMcores;\n"
        append text     "  stageout <= stage($nb_BMcores);\n\n"
    } else {
        append text     "  gen_synshift: FOR k IN 1 TO error_symbols GENERATE\n"
        append text     "    syndromesshift(k)(m_bits DOWNTO 1) <= syndromesnode_${nb_BMcores}(k+1)(m_bits DOWNTO 1);\n  END GENERATE;\n\n"
        append text     "  comp_omega: rsx_omega_pipe\n  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,\n"
        append text     "            start=>stage($nb_BMcores),\n           syndromes=>syndromesshift,\n            bdsin=>bds_$nb_BMcores,\n"
        append text     "            errorsin=>llnumber_$nb_BMcores,\n"  
        append text     "            bdsout=>bdsout,\n            omegaout=>omegaout,\n"
        append text     "            errorsout=>errorsout,\n            done=>stageout);\n\n"    
        
        append text     "  generate_inverses: rsx_inverse_ROM\n"  
        append text     "  GENERIC MAP (nb_input=>nb_bm_core)\n"  
        append text     "  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,\n"  
        append text     "      read_enable=>get_inv_of_valid,\n"  
        append text     "      alpha=>get_inv_of,\n"  
        append text     "       inverse_of_alpha=>value_of_inv); \n\n"  
    }
    
    if {$channel ==1} {
      append text     "  done <= stageout;\n"
      append text     "  number_errors(1) <= errorsout;\n"
      append text     "  error_evaluator(1) <= omegaout;\n"
      append text     "  error_locator(1) <= bdsout;\n\n"
    } else {
      append text     "  comp_bm_fifo: rsx_bm_fifo\n"
      append text     "  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,\n"
      append text     "            start=>stageout,\n"
      append text     "            omegain=>omegaout,\n            bdsin=>bdsout,\n            errorsin=>errorsout,\n"
      append text     "            bdsout=>error_locator,\n            omegaout=>error_evaluator,\n            errorsout=>number_errors,\n"
      append text     "            done=>done);\n\n"        
    }
    
    append text     "END rtlauto;\n\n"
    
    puts $f_handle $text
    close $f_handle
    
    
    #----------------------------------------------------------------------------------------------------------------------------
    send_message info "----Writing rsx_parameters_auto.vhd"
    set file_name "$temp_dir/rsx_parameters_auto.vhd"
    lappend list_of_generated_files $file_name
    set f_handle [open $file_name w+]
    set text ""
    
    append text     "\nLIBRARY ieee;\nUSE ieee.std_logic_1164.all;\n\n"
    append text     "PACKAGE rsx_parameters IS\n"
    append text     "         constant channel  : positive := $channel;\n"
    append text     "         constant n_symbols : positive := $n;\n"
    append text     "         constant k_symbols : positive := $k;\n"
    append text     "         constant m_bits    : positive := $m;\n"
    append text     "         constant polynomial : positive := $irrpol;\n"
    append text     "         constant parallel_symbols : positive := [expr $par*$channel];\n"
    append text     "         constant polynomial_speed : integer := $bm_speed; -- 4,5, or 6\n"
    append text     "         constant nb_bm_core : integer := $nb_BMcores;\n"
    append text     "         constant use_bypass : integer := $usebypass;\n"
    append text     "         constant use_sync : integer := $usesync;\n"
    append text     "         constant device_family : string := \"[get_parameter_value selected_device_family]\";\n"
    append text     "END rsx_parameters;\n"
    
    puts $f_handle $text
    close $f_handle

    #----------------------------------------------------------------------------------------------------------------------------
    send_message info "----Writing rsx_roots_auto.vhd"
    set file_name "$temp_dir/rsx_roots_auto.vhd"
    lappend list_of_generated_files $file_name
    set f_handle [open $file_name w+]
    set text ""
    
    
    append text     "LIBRARY ieee;\nUSE ieee.std_logic_1164.all;\n\n" 
    append text     "PACKAGE rsx_roots IS\n\n"
    append text     "type numarray IS ARRAY (0 TO $max_n) OF integer;\n\n"
    append text     "constant negenum : numarray := ("
    for {set ii 0} {$ii < [expr $max_n+1]} {incr ii} {
        append text     "[lindex $AlphaToThePowerMinus $ii]"
        if {$ii!=$max_n} {
            append text  ","
            if {$ii!=0 && ($ii%16)==0} {append text  "\n                                "}
        }
    }
    append text     ");\n\n"
    append text     "constant powernum : numarray := ("
    for {set ii 0} {$ii < [expr $max_n+1]} {incr ii} {
        append text     "[lindex $AlphaToThePower $ii]"
        if {$ii!=$max_n} {
            append text  ","
            if {$ii!=0 && ($ii%16)==0} {append text  "\n                                "}
        }
    }
    append text     ");\n\n"
    append text     "constant inverses : numarray := ("
    for {set ii 0} {$ii < [expr $max_n+1]} {incr ii} {
        append text     "[lindex $InverseOf $ii]"
        if {$ii!=$max_n} {
            append text  ","
            if {$ii!=0 && ($ii%16)==0} {append text  "\n                                "}
        }
    }
    append text     ");\n\n"
    append text     "END rsx_roots;\n"
    
    puts $f_handle $text
    close $f_handle
  
  
    #----------------------------------------------------------------------------------------------------------------------------

        send_message info "----Writing inverse_ROM.vhd"
        set file_name "$temp_dir/rsx_inverse_ROM_auto.vhd"
        lappend list_of_generated_files $file_name
        set f_handle [open $file_name w+]
        set text ""
      
        set device              [ get_parameter_value selected_device_family]
        if {[string match $device "Arria 10"] || [string match $device "Stratix 10"]} {
            set ram_modulename altera_syncram
            set new_device_family 1
        } else {
            set ram_modulename altsyncram
            set new_device_family 0
        }
        
        
        if {$usetruedualportram} {
            set ram_mode BIDIR_DUAL_PORT
        } else {
            if {$useeccforram} {set ram_mode DUAL_PORT} else {set ram_mode ROM}
        }

        append text     "\nLIBRARY ieee;\nUSE ieee.std_logic_1164.all;\nUSE ieee.std_logic_unsigned.all;\nUSE ieee.std_logic_arith.all;\n\n"
        if {$new_device_family==0} {
            append text     "\nLIBRARY altera_mf;\nUSE altera_mf.altera_mf_components.all;\n\n"
        } else {
            append text     "\nLIBRARY altera_lnsim;\nUSE altera_lnsim.altera_lnsim_components.all;\n\n"
        }
        append text     "USE work.rsx_parameters.all;\n\n"
        append text     "USE work.rsx_package.all;\n\n"
        append text     "ENTITY rsx_inverse_ROM IS\n  GENERIC (\n         nb_input : integer := 1\n );\n"
        append text     "  PORT (\n         sysclk: IN STD_LOGIC;\n"
        append text     "         reset : IN STD_LOGIC;\n"
        append text     "         enable : IN STD_LOGIC;\n"
        append text     "         alpha : IN inv_alpha_type;\n"
        append text     "         read_enable : IN STD_LOGIC_VECTOR (nbinvmax DOWNTO 1);\n"
        append text     "         inverse_of_alpha : OUT inv_alpha_type := (others=>(others=>'0'))\n"
        append text     "        );\nEND rsx_inverse_ROM;\n\n"
        append text     "ARCHITECTURE rtl OF rsx_inverse_ROM IS\n\n"
        
        if {$useram} {
            append text     "    signal inverse_of_alpha_from_ROM :inv_alpha_type := (others=>(others=>'0'));\n"
            append text     "    signal alpha_delay : inv_alpha_type;\n"
            if {$useeccforram} {
                append text     "    constant nb_counter : positive := 1;\n"
                append text     "    type ecc_cnt_type IS ARRAY (nb_counter DOWNTO 1)  OF STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
                append text     "    signal ecc_inv_ram_addr : ecc_cnt_type := (others=> (others=>'0'));\n"
                append text     "    signal ecc_inv_ram_data : ecc_cnt_type := (others=> (others=>'0'));\n\n"
            }
            if {$usetruedualportram} {
                append text     "    signal write_enable : STD_LOGIC_VECTOR (nbinvmax DOWNTO 1);\n"
                append text     "    signal address_a_node :inv_alpha_type;\n"
            }
        } else {
            append text     "    signal alphaff : inv_alpha_type;\n"
            append text     "    signal inverse : inv_alpha_type;\n\n"
            append text     "    signal inverseff :inv_alpha_type;\n"
        }
        if {$useram} {
            append text     "    component rsx_fit_counter\n"
            append text     "    GENERIC (\n          minus_one : positive := 1);\n"
            append text     "    PORT (\n"
            append text     "          sysclk, reset: IN STD_LOGIC;\n"
            append text     "          address, data : OUT STD_LOGIC_VECTOR (m_bits DOWNTO 1)\n"
            append text     "          );\n"
            append text     "      end component;\n\n "
            if {$usebkpwithram} {
                append text     "    component rsx_inverse_ROM_bkp\n"
                append text     "    PORT (\n"
                append text     "          sysclk,reset,enable: IN STD_LOGIC;\n"
                append text     "         in_data : IN STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
                append text     "          out_data : OUT STD_LOGIC_VECTOR (m_bits DOWNTO 1)\n"
                append text     "          );\n"
                append text     "      end component;\n\n "
            }
        } else {
            append text     "    component rsx_gf_inv\n"
            append text     "    PORT (\n"
            append text     "          aa: IN STD_LOGIC_VECTOR (m_bits DOWNTO 1);\n"
            append text     "          cc: OUT STD_LOGIC_VECTOR (m_bits DOWNTO 1)\n"
            append text     "          );\n"
            append text     "      end component;\n\n "
        }
        append text     "BEGIN\n\n"
        if {$useram} {
            if {$useeccforram} {
                append text     "    genecc: FOR k IN 1 TO nb_counter GENERATE\n"
                append text     "      ecc_for_GFinv: rsx_fit_counter\n"
                append text     "      GENERIC MAP (minus_one=>[lindex $AlphaToThePowerMinus 1])\n"
                append text     "      PORT MAP (sysclk=>sysclk,reset=>reset,\n"
                append text     "          address=>ecc_inv_ram_addr(k),\n"
                append text     "          data=>ecc_inv_ram_data(k));\n"
                append text     "    END GENERATE;\n\n"
            }
            append text     "    delay: FOR k IN 1 TO nb_input GENERATE\n"
            append text     "      delaying_address: PROCESS (alpha(k)) \n"
            append text     "      BEGIN\n"
            append text     "        alpha_delay(k) <= alpha(k) after 1 ps;\n"
            append text     "      END PROCESS;\n"
            append text     "    END GENERATE;\n\n" 
            
            append text     "    eccnode0: FOR k IN 1 TO nb_input GENERATE\n"
            if {$usetruedualportram & $useeccforram} {
                append text     "      eccnode1: PROCESS (write_enable(k),alpha_delay(k),ecc_inv_ram_addr(1+((k-1) mod nb_counter))) \n"
                append text     "        BEGIN\n"
                append text     "        IF (write_enable(k) = '1') THEN\n"
                append text     "          address_a_node(k) <= ecc_inv_ram_addr(1+((k-1) mod nb_counter));\n"
                append text     "        ELSE\n"
                append text     "          address_a_node(k) <= alpha_delay(k);\n"
                append text     "        END IF;\n"
                append text     "      END PROCESS; \n\n"
                append text     "      write_enable(k) <= NOT(read_enable(k));\n\n"
            }
            
           if {$usebkpwithram} {
                append text     "      module_bkp: rsx_inverse_ROM_bkp\n"
                append text     "      PORT MAP (sysclk=>sysclk, reset=>reset, enable=>enable, in_data=>inverse_of_alpha_from_ROM(k), out_data=>inverse_of_alpha(k));\n"
            } else {
                append text     "      inverse_of_alpha(k) <= inverse_of_alpha_from_ROM(k);\n"
            }  
            append text     "    END GENERATE;\n\n"
            
            if {$usetruedualportram} {
                append text     "    more_than_one_core: IF (nb_input>1) GENERATE\n"
                append text     "    ramb: FOR k IN 1 TO nb_input/2 GENERATE\n"
            } else {
                append text     "    ramb: FOR k IN 1 TO nb_input GENERATE\n"
            }
            append text     "    RAM: $ram_modulename\n    GENERIC MAP (\n"
            append text     "            operation_mode => \"$ram_mode\",\n"
            append text     "            numwords_a => [expr $max_n+1],\n"
            append text     "            width_a => m_bits,\n"
            append text     "            widthad_a => m_bits,\n"
            append text     "            outdata_reg_a => \"CLOCK0\",\n"
            if {$useeccforram | $usetruedualportram} {
                append text     "            numwords_b => [expr $max_n+1],\n"
                append text     "            width_b => m_bits,\n"
                append text     "            widthad_b => m_bits,\n"
                append text     "            address_reg_b => \"CLOCK0\",\n"
                append text     "            indata_reg_b => \"CLOCK0\",   \n"
                append text     "            outdata_reg_b => \"CLOCK0\",   \n"  
                #append text     "            read_during_write_mode_mixed_ports => \"OLD_DATA\",   \n"  
            }
            append text     "            lpm_type  => \"$ram_modulename\", \n"                       
            append text     "            power_up_uninitialized => \"FALSE\", \n"                       
            append text     "            ram_block_type => \"AUTO\",\n"
            append text     "            init_file => \"${entity}_rom_inverse.hex\",\n"
            if {$new_device_family==0} {
                append text     "            wrcontrol_wraddress_reg_b => \"CLOCK0\",\n"
            }
            append text     "            init_file_layout => \"PORT_A\"\n"
            append text     "            ) PORT MAP ( \n"
            append text     "            clock0 => sysclk,\n"
            
            if {$usetruedualportram} {
                if {$useeccforram} {
                    append text     "            wren_a    => write_enable(2*(k-1)+1),\n"
                    append text     "            address_a => address_a_node(2*(k-1)+1),\n"
                    append text     "            data_a    => ecc_inv_ram_data(1+((k-1) mod nb_counter)),\n"
                } else {
                    append text     "            wren_a    => \'0\',\n"
                    append text     "            address_a => alpha_delay(2*(k-1)+1),\n"
                }
                append text     "            q_a       => inverse_of_alpha_from_ROM(2*(k-1)+1),\n"
                append text     "            wren_b    => \'0\',\n"
                append text     "            address_b => alpha_delay(2*(k-1)+2),\n"
                append text     "            q_b       => inverse_of_alpha_from_ROM(2*(k-1)+2)\n"
            } else {
                if {$useeccforram} {
                    append text     "            address_a => ecc_inv_ram_addr(1+((k-1) mod nb_counter)),\n"
                    append text     "            data_a => ecc_inv_ram_data(1+((k-1) mod nb_counter)),\n"
                    append text     "            wren_a => \'1\',\n"
                    append text     "            address_b => alpha_delay(k),\n"
                    append text     "            q_b => inverse_of_alpha_from_ROM(k)\n"
                } else {
                    append text     "            address_a => alpha_delay(k),\n"
                    append text     "            q_a => inverse_of_alpha_from_ROM(k)\n"
                }
            }
            append text     "        );\n\n"
            append text     "    END GENERATE;\n"
            if {$usetruedualportram} {append text     "    END GENERATE;\n"}
            
            if {$usetruedualportram} {
                append text     "    ramEXTRA: IF ((nb_input mod 2) = 1) GENERATE\n"
                append text     "      RAM: $ram_modulename\n    GENERIC MAP (\n"
                append text     "            operation_mode => \"$ram_mode\",\n"
                append text     "            numwords_a => [expr $max_n+1],\n"
                append text     "            width_a => m_bits,\n"
                append text     "            widthad_a => m_bits,\n"
                append text     "            outdata_reg_a => \"CLOCK0\",\n"
                append text     "            numwords_b => [expr $max_n+1],\n"
                append text     "            width_b => m_bits,\n"
                append text     "            widthad_b => m_bits,\n"
                append text     "            address_reg_b => \"CLOCK0\",\n"
                append text     "            indata_reg_b => \"CLOCK0\",\n"
                append text     "            outdata_reg_b => \"CLOCK0\",   \n"
                #append text     "            read_during_write_mode_mixed_ports => \"OLD_DATA\",   \n"  
                append text     "            lpm_type  => \"$ram_modulename\", \n"                       
                append text     "            power_up_uninitialized => \"FALSE\", \n"                       
                append text     "            ram_block_type => \"AUTO\",\n"
                append text     "            init_file => \"${entity}_rom_inverse.hex\",\n"
                if {$new_device_family==0} {
                    append text     "            wrcontrol_wraddress_reg_b => \"CLOCK0\",\n"
                }
                append text     "            init_file_layout => \"PORT_A\"\n"
                append text     "            ) PORT MAP ( \n"
                append text     "            clock0 => sysclk,\n"
                if {$useeccforram} {
                    append text     "            wren_a    => write_enable(nb_input),\n"
                    append text     "            address_a => address_a_node(nb_input),\n"
                    append text     "            data_a    => ecc_inv_ram_data(1+((nb_input-1) mod nb_counter)),\n"
                } else {
                    append text     "            wren_a    => \'0\',\n"
                    append text     "            address_a => alpha_delay(nb_input),\n"
                }
                append text     "            q_a       => inverse_of_alpha_from_ROM(nb_input),\n"
                append text     "            wren_b    => \'0\',\n"
                append text     "            address_b => (others => '0')\n"
                
                
                append text     "      );\n\n"
                append text     "    END GENERATE;\n" 
            }

        } else {
            append text     "    LUT: FOR k IN 1 TO nb_input GENERATE\n"
            append text     "      LUT: PROCESS (sysclk,reset)\n      BEGIN\n"
            append text     "      IF (reset = '1') THEN\n"
            append text     "        alphaff(k) <= conv_std_logic_vector (0,m_bits);\n"
            append text     "        inverseff(k) <= conv_std_logic_vector (0,m_bits);\n"
            append text     "      ELSIF (rising_edge(sysclk)) THEN\n"
            append text     "        IF (enable = '1') THEN\n"
            append text     "          alphaff(k) <= alpha(k);\n"
            append text     "          inverseff(k) <= inverse(k);\n"
            append text     "        END IF;\n"
            append text     "      END IF;\n"
            append text     "      END PROCESS;\n"
            append text     "      cinv: rsx_gf_inv \n"
            append text     "      PORT MAP (aa=>alphaff(k),cc=>inverse(k));\n"
            append text     "      inverse_of_alpha(k) <= inverseff(k);\n"
            append text     "    END GENERATE;\n"
        }

        append text     "END rtl;\n\n"


        puts $f_handle $text
        close $f_handle
      
        #----------------------------------------------------------------------------------------------------------------------------
        send_message info "----Adding ${entity}_rom_inverse.hex"
        
        set text [convert_hexa_to_HEX $InverseOf_hexa]
        add_fileset_file "${entity}_rom_inverse.hex" HEX TEXT $text
        
        #----------------------------------------------------------------------------------------------------------------------------

    cd $cwd
    

    
    return $list_of_generated_files
}


proc convert_hexa_to_HEX {hexa_list} {
    # this function convert a list of hexadecimal number into a
    # Intel HEX format list used in ROM initialisation
    # 
    # 
    # 
    
    set HEX_list [list ]
    set length [llength $hexa_list]
    set HexacharPerWord     [llength [regexp -all -inline . [lindex $hexa_list 0]]]

    
    if {$HexacharPerWord%2!=0} {
        set append_char 0 
        incr HexacharPerWord
    } else {
        set append_char ""
    }
    
    
    for {set ii 0} {$ii<$length} {incr ii} {
        #
        set nb_byte [format %02X [expr $HexacharPerWord>>1] ]
        
        set address [format %04X [expr $ii] ] 
        set record_type "00"
        set data $append_char[lindex $hexa_list $ii]
        set crc [format %02X [ihex_crc  [regexp -all -inline .. $nb_byte$address$record_type$data]] ] 
        append HEX_list ":${nb_byte}${address}${record_type}${data}${crc}\n"
    
    }
    append HEX_list ":00000001FF"

    return $HEX_list

}


proc ihex_crc {bytes} {
    # Calculate Intel-hex CRC for list of bytes
    set sum 0
    foreach b $bytes {
        incr sum 0x$b
    }
    set sum [expr {(1 + ~$sum) & 0xFF}] ;# bcb
    return $sum
}

