#DISPLAY_NAME = ALTFP_INV
DESCRIPTION  = Altera Floating Point Matrix Multiply
GROUP = Basic Functions/Arithmetic
AUTHOR = Altera Corporation
DATASHEET_URL = http://www.altera.com/literature/ug/ug_altfp_mfug.pdf

#Section names
FLOATING_PT_DATA_GROUP = Floating Point Data
MATRIX_FORMAT_GROUP = Matrix Format
OPTIONAL_PORTS_GROUP = Ports


#parameter strings that appear in Documentation page
PRECISION_DISPLAY_NAME = Format
VECTOR_SIZE_NAME = Vector Size
BLOCK_SIZE_NAME = Blocks
AA_COLUMNS_NAME = Number of Columns in matrix AA
AA_ROWS_NAME = Number of Rows in matrix AA
BB_COLUMNS_NAME = Number of Columns in matrix BB



RESET_PORT_DISPLAY_NAME = Create a Reset Port
ENABLE_PORT_DISPLAY_NAME = Create An Enable Port


MATRIX_SIZE_PARAMETER =  4 6 8 16 32 64
PRECISION_FLOAT_NAME = Single (32 bit)
PRECISION_DOUBLE_NAME = Double (64 bit)

#memory
PRECISION_DESCRIPTION = Data format of the matrices. Single Floating Point or Double Floating Point data types are supported
VECTOR_SIZE_DESCRIPTION = The number of elements in the dot product core. The core library supports lengths of 8, 16, 32, 64, 96, and 128.
BLOCK_SIZE_DESCRIPTION = The number of memory blocks for the double buffered storage of matrix AA. The allowable range is from 2 to 48.
AA_COLUMNS_DESCRIPTION = Number of columns in matrix AA.
AA_ROWS_DESCRIPTION =  Number of rows in matrix AA.
BB_COLUMNS_DESCRIPTION = Number of columns in matrix BB.


RESET_PORT_DESCRIPTION = Create an asynchronous reset port
ENABLE_PORT_DESCRIPTION = Create a port to control when the core is enabled



#Messages
INCORRECT_MOD_VALUE_MSG = The number of columns in AA must be an even multiple of Vector size
INCORRECT_RATIO_MSG = The (Vector Size/(2 x Block Size)) must be a whole number between 2 and 6 it is currently $ratio
MATRIX_TOO_LARGE_MSG = The Matrix size cannot be greater than 2048 times the block size
COLUMNSAA_MOD_NOT_ZERO_MSG = The number of Columns in AA must be a multiple of 2 x block size
BLOCK_SIZE_INVALID_MSG = Block size must be an even integer between 2 and 48
MATRIX_BB_TOO_LARGE_MSG = Matrix BB must not be larger than 512 x Vector Size
MATRIX_DIMENSIONS_MSG = All Matrix dimensions must be greater than block size
