# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 16.1
# Mon Jun 20 17:30:22 MYT 2016
# DO NOT MODIFY


# 
# altera_asmi2_xip_controller "Altera ASMI2 XIP Controller" v1.0
#  2016.06.20.17:30:22
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0
package require -exact altera_terp 1.0


# 
# module altera_asmi2_xip_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_asmi2_xip_controller
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Configuration and Programming"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Altera ASMI2 XIP Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

set_module_property     ELABORATION_CALLBACK    elaboration

# ----------------------------------------------------------------------
# 
# parameters
# 

add_parameter           FLASH_VENDOR   STRING              "EPCQ128"
set_parameter_property  FLASH_VENDOR   DISPLAY_NAME        "FLASH_VENDOR"

# Data width
add_parameter           DATA_WIDTH  STRING              "STANDARD"
set_parameter_property  DATA_WIDTH  AFFECTS_GENERATION  true
set_parameter_property  DATA_WIDTH  VISIBLE             false
set_parameter_property  DATA_WIDTH  ALLOWED_RANGES      {"NORMAL" "STANDARD" "DUAL" "QUAD"}

# Show chip select conduit
add_parameter           CHIP_SELECT_EN  BOOLEAN             true
set_parameter_property  CHIP_SELECT_EN  AFFECTS_GENERATION  true
set_parameter_property  CHIP_SELECT_EN  AFFECTS_ELABORATION true
set_parameter_property  CHIP_SELECT_EN  VISIBLE             false

# write opcode from preset
add_parameter           WRITE_OP    STRING              0
set_parameter_property  WRITE_OP    AFFECTS_GENERATION  true
set_parameter_property  WRITE_OP    AFFECTS_ELABORATION true
set_parameter_property  WRITE_OP    VISIBLE             false
set_parameter_property  WRITE_OP    DERIVED             true

# poll opcode from preset
add_parameter           POLL_OP     STRING              0
set_parameter_property  POLL_OP     AFFECTS_GENERATION  true
set_parameter_property  POLL_OP     AFFECTS_ELABORATION true
set_parameter_property  POLL_OP     VISIBLE             false
set_parameter_property  POLL_OP     DERIVED             true

# read opcode from preset
add_parameter           READ_OP     STRING              0
set_parameter_property  READ_OP     AFFECTS_GENERATION  true
set_parameter_property  READ_OP     AFFECTS_ELABORATION true
set_parameter_property  READ_OP     VISIBLE             false
set_parameter_property  READ_OP     DERIVED             true

# read dummy clk cycle from preset
add_parameter           READ_DUMMY_NUM  STRING              0
set_parameter_property  READ_DUMMY_NUM  AFFECTS_GENERATION  true
set_parameter_property  READ_DUMMY_NUM  AFFECTS_ELABORATION true
set_parameter_property  READ_DUMMY_NUM  VISIBLE             false
set_parameter_property  READ_DUMMY_NUM  DERIVED             true

# byte addressing from preset
add_parameter           BYTE_ADDRESSING STRING              0
set_parameter_property  BYTE_ADDRESSING AFFECTS_GENERATION  true
set_parameter_property  BYTE_ADDRESSING AFFECTS_ELABORATION true
set_parameter_property  BYTE_ADDRESSING VISIBLE             false
set_parameter_property  BYTE_ADDRESSING DERIVED             true

# write has dummy
add_parameter           WR_HAS_DUMMY    STRING              0
set_parameter_property  WR_HAS_DUMMY    AFFECTS_GENERATION  true
set_parameter_property  WR_HAS_DUMMY    AFFECTS_ELABORATION true
set_parameter_property  WR_HAS_DUMMY    VISIBLE             false
set_parameter_property  WR_HAS_DUMMY    DERIVED             true

# read has dummy
add_parameter           RD_HAS_DUMMY    STRING              0
set_parameter_property  RD_HAS_DUMMY    AFFECTS_GENERATION  true
set_parameter_property  RD_HAS_DUMMY    AFFECTS_ELABORATION true
set_parameter_property  RD_HAS_DUMMY    VISIBLE             false
set_parameter_property  RD_HAS_DUMMY    DERIVED             true

# Fix Word addressing
add_parameter           ADDR_WIDTH  INTEGER             32
set_parameter_property  ADDR_WIDTH  AFFECTS_GENERATION  true
set_parameter_property  ADDR_WIDTH  VISIBLE             false
set_parameter_property  ADDR_WIDTH  HDL_PARAMETER       true
set_parameter_property  ADDR_WIDTH  DERIVED             true


#----------------------------------------------------------------------
add_parameter WR_ID STRING_LIST 1
set_parameter_property WR_ID DISPLAY_NAME {No}
set_parameter_property WR_ID AFFECTS_ELABORATION true
set_parameter_property WR_ID AFFECTS_GENERATION true
set_parameter_property WR_ID HDL_PARAMETER false
set_parameter_property WR_ID DERIVED true
#set_parameter_property WR_ID GROUP "Write_Table"
set_parameter_property WR_ID DESCRIPTION {List of IDs}

add_parameter WR_OPERATION STRING_LIST "01"
set_parameter_property WR_OPERATION DISPLAY_NAME {Operation} 
set_parameter_property WR_OPERATION AFFECTS_ELABORATION true
set_parameter_property WR_OPERATION AFFECTS_GENERATION true
set_parameter_property WR_OPERATION HDL_PARAMETER false
set_parameter_property WR_OPERATION DERIVED true
#set_parameter_property WR_OPERATION GROUP "Write_Table"
set_parameter_property WR_OPERATION DESCRIPTION {List of channel IDs}

add_parameter WR_OPCODE STRING_LIST 0
set_parameter_property WR_OPCODE DISPLAY_NAME {Opcode}
set_parameter_property WR_OPCODE AFFECTS_ELABORATION true
set_parameter_property WR_OPCODE AFFECTS_GENERATION true
set_parameter_property WR_OPCODE HDL_PARAMETER false
set_parameter_property WR_OPCODE DERIVED false
#set_parameter_property WR_OPCODE GROUP "Write_Table"
set_parameter_property WR_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property WR_OPCODE DESCRIPTION {List of opcode}

add_parameter WR_EXTEND STRING_LIST 0
set_parameter_property WR_EXTEND DISPLAY_NAME {Opcode}
set_parameter_property WR_EXTEND AFFECTS_ELABORATION true
set_parameter_property WR_EXTEND AFFECTS_GENERATION true
set_parameter_property WR_EXTEND HDL_PARAMETER false
set_parameter_property WR_EXTEND DERIVED false
set_parameter_property WR_EXTEND DISPLAY_HINT "hexadecimal"
set_parameter_property WR_EXTEND DESCRIPTION {List of opcode}

add_parameter POLL_OPCODE STRING 0
set_parameter_property POLL_OPCODE DISPLAY_NAME "Poll opcode"
set_parameter_property POLL_OPCODE AFFECTS_ELABORATION true
set_parameter_property POLL_OPCODE AFFECTS_GENERATION true
set_parameter_property POLL_OPCODE HDL_PARAMETER false
set_parameter_property POLL_OPCODE DERIVED false
set_parameter_property POLL_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property POLL_OPCODE DESCRIPTION "Opcode used for polling"

add_display_item "Write_Table" WR_ID parameter
add_display_item "Write_Table" WR_OPERATION parameter
add_display_item "Write_Table" WR_OPCODE parameter

#----------------------------------------------------------------------
add_parameter RD_ID STRING_LIST 1
set_parameter_property RD_ID DISPLAY_NAME {No}
set_parameter_property RD_ID AFFECTS_ELABORATION true
set_parameter_property RD_ID AFFECTS_GENERATION true
set_parameter_property RD_ID HDL_PARAMETER false
set_parameter_property RD_ID DERIVED true
set_parameter_property RD_ID GROUP "Read_Table"
set_parameter_property RD_ID DESCRIPTION {List of IDs}

add_parameter RD_OPERATION STRING_LIST "01"
set_parameter_property RD_OPERATION DISPLAY_NAME {Operation} 
set_parameter_property RD_OPERATION AFFECTS_ELABORATION true
set_parameter_property RD_OPERATION AFFECTS_GENERATION true
set_parameter_property RD_OPERATION HDL_PARAMETER false
set_parameter_property RD_OPERATION DERIVED true
set_parameter_property RD_OPERATION GROUP "Read_Table"
set_parameter_property RD_OPERATION DESCRIPTION {List of channel IDs}

add_parameter RD_OPCODE STRING_LIST 0
set_parameter_property RD_OPCODE DISPLAY_NAME {Opcode}
set_parameter_property RD_OPCODE AFFECTS_ELABORATION true
set_parameter_property RD_OPCODE AFFECTS_GENERATION true
set_parameter_property RD_OPCODE HDL_PARAMETER false
set_parameter_property RD_OPCODE DERIVED false
set_parameter_property RD_OPCODE GROUP "Read_Table"
set_parameter_property RD_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property RD_OPCODE DESCRIPTION {List of opcode}

add_parameter RD_EXTEND STRING_LIST 0
set_parameter_property RD_EXTEND DISPLAY_NAME {Opcode}
set_parameter_property RD_EXTEND AFFECTS_ELABORATION true
set_parameter_property RD_EXTEND AFFECTS_GENERATION true
set_parameter_property RD_EXTEND HDL_PARAMETER false
set_parameter_property RD_EXTEND DERIVED false
set_parameter_property RD_EXTEND GROUP "Read_Table"
set_parameter_property RD_EXTEND DISPLAY_HINT "hexadecimal"
set_parameter_property RD_EXTEND DESCRIPTION {List of opcode}

add_parameter RD_DUMMY_BYTES STRING_LIST 0
set_parameter_property RD_DUMMY_BYTES DISPLAY_NAME {Dummy bytes}
set_parameter_property RD_DUMMY_BYTES AFFECTS_ELABORATION true
set_parameter_property RD_DUMMY_BYTES AFFECTS_GENERATION true
set_parameter_property RD_DUMMY_BYTES HDL_PARAMETER false
set_parameter_property RD_DUMMY_BYTES DERIVED false
set_parameter_property RD_DUMMY_BYTES GROUP "Read_Table"
set_parameter_property RD_DUMMY_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property RD_DUMMY_BYTES DESCRIPTION {List of dummy bytes}

add_parameter RW_ADDR_BYTES STRING 0
set_parameter_property RW_ADDR_BYTES DISPLAY_NAME "Read/Write address bytes"
set_parameter_property RW_ADDR_BYTES AFFECTS_ELABORATION true
set_parameter_property RW_ADDR_BYTES AFFECTS_GENERATION true
set_parameter_property RW_ADDR_BYTES HDL_PARAMETER false
set_parameter_property RW_ADDR_BYTES DERIVED false
set_parameter_property RW_ADDR_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property RW_ADDR_BYTES DESCRIPTION "Byte addressing used for Read/Write operation"

# ----------------------------------------------------------------------
# 
# display items
# 
add_display_item "" "Settings" GROUP tab
add_display_item "Settings" "Common Operations"   GROUP
add_display_item "Settings" "Miscellaneous Operations"   GROUP
add_display_item "Settings" "Write Operations"   GROUP
add_display_item "Settings" "Read Operations"   GROUP
add_display_item "Common Operations" "Common_table" GROUP TABLE
add_display_item "Miscellaneous Operations" "Miscellaneous_table" GROUP TABLE
add_display_item "Write Operations" "Write_Table" GROUP TABLE
add_display_item "Write Operations"  POLL_OPCODE   parameter
add_display_item "Read Operations" "Read_Table" GROUP TABLE
set_display_item_property "Common_table" DISPLAY_HINT {table rows:10}
set_display_item_property "Miscellaneous_table" DISPLAY_HINT {table rows:13}
set_display_item_property "Write_Table" DISPLAY_HINT {table rows:4}
set_display_item_property "Read_Table" DISPLAY_HINT {table rows:4}


# ----------------------------------------------------------------------
# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH generate_synth
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_asmi2_xip_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true

add_fileset SIM_VERILOG SIM_VERILOG generate_synth
set_fileset_property SIM_VERILOG TOP_LEVEL altera_asmi2_xip_controller
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true

add_fileset SIM_VHDL SIM_VHDL generate_synth
set_fileset_property SIM_VHDL TOP_LEVEL altera_asmi2_xip_controller
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true

proc generate_synth {entity_name} {    
    set this_dir      [ get_module_property MODULE_DIRECTORY ]
    set template_file [ file join $this_dir "altera_asmi2_xip_controller.sv.terp" ]
    set template      [ read [ open $template_file r ] ]
    
    set params(data_width)      [get_parameter_value DATA_WIDTH]
    set params(en_chip_select)  [get_parameter_value CHIP_SELECT_EN]
    set params(write_op)        [get_parameter_value WRITE_OP]
    set params(poll_op)         [get_parameter_value POLL_OP]
    set params(read_op)         [get_parameter_value READ_OP]
    set params(read_dummy_num)  [get_parameter_value READ_DUMMY_NUM]
    set params(byte_addressing) [get_parameter_value BYTE_ADDRESSING]
    set params(wr_has_dummy)       [get_parameter_value WR_HAS_DUMMY]
    set params(rd_has_dummy)       [get_parameter_value RD_HAS_DUMMY]
    set params(flash_vendor)       [get_parameter_value FLASH_VENDOR]
    set result                  [ altera_terp $template params ]
    
    set output_file     [ create_temp_file altera_asmi2_xip_controller.sv ]
    set output_handle   [ open $output_file w ]
    puts $output_handle $result
    close $output_handle
    
    add_fileset_file altera_asmi2_xip_controller.sv SYSTEM_VERILOG PATH ${output_file}
}


# ----------------------------------------------------------------------
# 
# connection point clk
#
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mem
# 
add_interface mem avalon end
set_interface_property mem addressUnits WORDS
set_interface_property mem associatedClock clk
set_interface_property mem associatedReset reset
set_interface_property mem bitsPerSymbol 8
set_interface_property mem burstOnBurstBoundariesOnly false
set_interface_property mem burstcountUnits WORDS
set_interface_property mem explicitAddressSpan 0
set_interface_property mem holdTime 0
set_interface_property mem linewrapBursts false
set_interface_property mem maximumPendingReadTransactions 1
set_interface_property mem maximumPendingWriteTransactions 0
set_interface_property mem readLatency 0
set_interface_property mem readWaitTime 1
set_interface_property mem setupTime 0
set_interface_property mem timingUnits Cycles
set_interface_property mem writeWaitTime 0
set_interface_property mem ENABLED true
set_interface_property mem EXPORT_OF ""
set_interface_property mem PORT_NAME_MAP ""
set_interface_property mem CMSIS_SVD_VARIABLES ""
set_interface_property mem SVD_ADDRESS_GROUP ""

add_interface_port mem mem_addr address Input ADDR_WIDTH
add_interface_port mem mem_rd read Input 1
add_interface_port mem mem_rddata readdata Output 32
add_interface_port mem mem_wr write Input 1
add_interface_port mem mem_wrdata writedata Input 32
add_interface_port mem mem_byteenable byteenable Input 4
add_interface_port mem mem_burstcount burstcount Input 7
add_interface_port mem mem_waitrequest waitrequest Output 1
add_interface_port mem mem_rddatavalid readdatavalid Output 1
set_interface_assignment mem embeddedsw.configuration.isFlash 0
set_interface_assignment mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point addr
# 
add_interface addr_bytes_xip conduit end
set_interface_property addr_bytes_xip associatedClock clk
set_interface_property addr_bytes_xip associatedReset ""
set_interface_property addr_bytes_xip ENABLED true
set_interface_property addr_bytes_xip EXPORT_OF ""
set_interface_property addr_bytes_xip PORT_NAME_MAP ""
set_interface_property addr_bytes_xip CMSIS_SVD_VARIABLES ""
set_interface_property addr_bytes_xip SVD_ADDRESS_GROUP ""

add_interface_port addr_bytes_xip addr_bytes_xip addr_bytes_xip Output 32


# 
# connection point cmd_pck
# 
add_interface cmd_pck avalon_streaming start
set_interface_property cmd_pck associatedClock clk
set_interface_property cmd_pck associatedReset reset
set_interface_property cmd_pck dataBitsPerSymbol 32
set_interface_property cmd_pck errorDescriptor ""
set_interface_property cmd_pck firstSymbolInHighOrderBits true
set_interface_property cmd_pck maxChannel 0
set_interface_property cmd_pck readyLatency 0
set_interface_property cmd_pck ENABLED true
set_interface_property cmd_pck EXPORT_OF ""
set_interface_property cmd_pck PORT_NAME_MAP ""
set_interface_property cmd_pck CMSIS_SVD_VARIABLES ""
set_interface_property cmd_pck SVD_ADDRESS_GROUP ""

add_interface_port cmd_pck cmd_channel channel Output 2
add_interface_port cmd_pck cmd_eop endofpacket Output 1
add_interface_port cmd_pck cmd_ready ready Input 1
add_interface_port cmd_pck cmd_sop startofpacket Output 1
add_interface_port cmd_pck cmd_data data Output 32
add_interface_port cmd_pck cmd_valid valid Output 1


# 
# connection point rsp_pck
# 
add_interface rsp_pck avalon_streaming end
set_interface_property rsp_pck associatedClock clk
set_interface_property rsp_pck associatedReset reset
set_interface_property rsp_pck dataBitsPerSymbol 32
set_interface_property rsp_pck errorDescriptor ""
set_interface_property rsp_pck firstSymbolInHighOrderBits true
set_interface_property rsp_pck maxChannel 0
set_interface_property rsp_pck readyLatency 0
set_interface_property rsp_pck ENABLED true
set_interface_property rsp_pck EXPORT_OF ""
set_interface_property rsp_pck PORT_NAME_MAP ""
set_interface_property rsp_pck CMSIS_SVD_VARIABLES ""
set_interface_property rsp_pck SVD_ADDRESS_GROUP ""

add_interface_port rsp_pck rsp_channel channel Input 2
add_interface_port rsp_pck rsp_data data Input 32
add_interface_port rsp_pck rsp_eop endofpacket Input 1
add_interface_port rsp_pck rsp_ready ready Output 1
add_interface_port rsp_pck rsp_sop startofpacket Input 1
add_interface_port rsp_pck rsp_valid valid Input 1


# ----------------------------------------------------------------------
# 
# elaboration callback
#
proc elaboration {} {

    # instantiate avst fifo
    add_hdl_instance avst_fifo altera_avalon_sc_fifo
    set_instance_parameter_value avst_fifo {SYMBOLS_PER_BEAT} {1}
    set_instance_parameter_value avst_fifo {BITS_PER_SYMBOL} {32}
    set_instance_parameter_value avst_fifo {FIFO_DEPTH} {64}
    set_instance_parameter_value avst_fifo {CHANNEL_WIDTH} {0}
    set_instance_parameter_value avst_fifo {ERROR_WIDTH} {0}
    set_instance_parameter_value avst_fifo {USE_PACKETS} {1}
    set_instance_parameter_value avst_fifo {USE_FILL_LEVEL} {0}
    set_instance_parameter_value avst_fifo {EMPTY_LATENCY} {3}
    set_instance_parameter_value avst_fifo {USE_MEMORY_BLOCKS} {1}
    set_instance_parameter_value avst_fifo {USE_STORE_FORWARD} {0}
    set_instance_parameter_value avst_fifo {USE_ALMOST_FULL_IF} {0}
    set_instance_parameter_value avst_fifo {USE_ALMOST_EMPTY_IF} {0}
    
    set enable_chip_select  [get_parameter_value CHIP_SELECT_EN]
    set flash_vendor        [get_parameter_value FLASH_VENDOR]
    
    if { $enable_chip_select } {
        add_interface chip_select conduit end
        set_interface_property chip_select associatedClock clk
        set_interface_property chip_select associatedReset ""
        set_interface_property chip_select ENABLED true
        set_interface_property chip_select EXPORT_OF ""
        set_interface_property chip_select PORT_NAME_MAP ""
        set_interface_property chip_select CMSIS_SVD_VARIABLES ""
        set_interface_property chip_select SVD_ADDRESS_GROUP ""
        
        add_interface_port chip_select chip_select chip_select  Input   4
    }
    
    set write_op_opcode         [get_parameter_value WR_OPCODE]
    set write_extended_mode     [get_parameter_value WR_EXTEND]
    set poll_op_hex             [get_parameter_value POLL_OPCODE]
    set read_op_opcode          [get_parameter_value RD_OPCODE]
    set read_extended_mode      [get_parameter_value RD_EXTEND]
    set read_dummy_bytes        [get_parameter_value RD_DUMMY_BYTES]
    set rd_wr_byte_addressing   [get_parameter_value RW_ADDR_BYTES]
    set io_mode                 [get_parameter_value DATA_WIDTH]
    
    if {$flash_vendor eq "ALTERA_EPCQA"} {
        if {$io_mode == "QUAD"} {
            set write_index 0
            set read_index  3
        } elseif { $io_mode == "DUAL" } {
            set write_index 0       
            set read_index  2
        } elseif { $io_mode == "STANDARD" } {
            set write_index 0       
            set read_index  1
        } else {
            set write_index 0       
            set read_index  0
        }
    } else {
        if {$io_mode == "QUAD"} {
            set write_index 2       
            set read_index  3
        } elseif { $io_mode == "DUAL" } {
            set write_index 1       
            set read_index  2
        } elseif { $io_mode == "STANDARD" } {
            set write_index 0       
            set read_index  1
        } else {
            set write_index 0       
            set read_index  0
        }
    }
    
    set write_op_hex        [lindex $write_op_opcode $write_index]
    set wr_has_dummy_bin    [lindex $write_extended_mode $write_index]
    set read_op_hex         [lindex $read_op_opcode $read_index]
    set rd_has_dummy_bin    [lindex $read_extended_mode $read_index]
    set rd_dummy_bytes_hex  [lindex $read_dummy_bytes $read_index]
    
    if {$rd_wr_byte_addressing == 4} {
        set byte_addressing_bin 1
    } else {
        set byte_addressing_bin 0
    }
    
    set_parameter_value WRITE_OP        8'h$write_op_hex
    set_parameter_value POLL_OP         8'h$poll_op_hex
    set_parameter_value READ_OP         8'h$read_op_hex
    set_parameter_value READ_DUMMY_NUM  5'h$rd_dummy_bytes_hex
    set_parameter_value BYTE_ADDRESSING 1'b$byte_addressing_bin
    set_parameter_value WR_HAS_DUMMY    1'b$wr_has_dummy_bin
    set_parameter_value RD_HAS_DUMMY    1'b$rd_has_dummy_bin
}