# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 10.0
# Fri Apr 09 15:05:04 MYT 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_eth_2_5g_pcs_16b "altera_eth_2_5g_pcs_16b" v1.0
# | null 2010.04.09.15:05:04
# | 
# | 
# | /data/aishak/pcs/pcs_pma_2.5g/pcs_pma.v
# | 
# |    ./pcs_pma.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_eth_2_5g_pcs_16b
# | 
set_module_property NAME altera_eth_2_5g_pcs_16b
set_module_property VERSION 18.1
set_module_property AUTHOR "Altera Corporation"
set_module_property INTERNAL true
set_module_property DISPLAY_NAME "Ethernet 2.5G PCS"
set_module_property TOP_LEVEL_HDL_FILE altera_eth_2_5g_pcs_pma_16b.v
set_module_property STATIC_TOP_LEVEL_MODULE_NAME altera_eth_2_5g_pcs_pma_16b
set_module_property TOP_LEVEL_HDL_MODULE altera_eth_2_5g_pcs_pma_16b
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property GROUP "Interface Protocols/Ethernet"
set_module_property ELABORATION_CALLBACK elaborate
set_module_property VALIDATION_CALLBACK validate
# set_module_property SIMULATION_MODEL_IN_VERILOG true
# set_module_property SIMULATION_MODEL_IN_VHDL true
# | 
# +-----------------------------------

# +-----------------------------------
# | IEEE encryption
# |-----------------------------------
add_fileset simulation_verilog SIM_VERILOG sim_ver
add_fileset simulation_vhdl SIM_VHDL sim_ver
set_fileset_property simulation_verilog TOP_LEVEL altera_eth_2_5g_pcs_pma_16b


proc sim_ver {name} {
    if {[_is_phy_ip] == "5" } {
		add_fileset_file altera_eth_2_5g_pcs_pma_16b.v VERILOG PATH "nativephy/altera_eth_2_5g_pcs_pma_16b.v" 
		add_fileset_file altera_tse_pcs_pma_gige_16b.v VERILOG PATH "nativephy/altera_tse_pcs_pma_gige_16b.v"
    } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
		add_fileset_file altera_eth_2_5g_pcs_pma_16b.v VERILOG PATH "phyip/altera_eth_2_5g_pcs_pma_16b.v" 
		add_fileset_file altera_tse_pcs_pma_gige_16b.v VERILOG PATH "phyip/altera_tse_pcs_pma_gige_16b.v"
    } else {
		add_fileset_file altera_eth_2_5g_pcs_pma_16b.v VERILOG PATH "alt4gxb/altera_eth_2_5g_pcs_pma_16b.v" 
		add_fileset_file altera_tse_alt4gxb_gige_16b.v VERILOG PATH "alt4gxb/altera_tse_alt4gxb_gige_16b.v"
		add_fileset_file altera_tse_gxb_gige_inst_16b.v VERILOG PATH "alt4gxb/altera_tse_gxb_gige_inst_16b.v"
		add_fileset_file altera_tse_pcs_pma_gige_16b.v VERILOG PATH "alt4gxb/altera_tse_pcs_pma_gige_16b.v"
    }	
    add_fileset_file altera_std_synchronizer_nocut.v VERILOG PATH "../../primitives/altera_std_synchronizer/altera_std_synchronizer_nocut.v"

    if {1} {
      if {[_is_phy_ip] == "5" } {
      add_fileset_file mentor/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "mentor/nativephy/altera_tse_gxb_aligned_rxsync_16b.v" {MENTOR_SPECIFIC}      
      } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
      add_fileset_file mentor/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "mentor/phyip/altera_tse_gxb_aligned_rxsync_16b.v" {MENTOR_SPECIFIC}
      } else {
      add_fileset_file mentor/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "mentor/alt4gxb/altera_tse_gxb_aligned_rxsync_16b.v" {MENTOR_SPECIFIC}
      }
		add_fileset_file mentor/altera_tse_carrier_sense_16b.v VERILOG_ENCRYPT  PATH "mentor/altera_tse_carrier_sense_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_mdio_reg_16b.v VERILOG_ENCRYPT  PATH "mentor/altera_tse_mdio_reg_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_pcs_control_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_pcs_control_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_pcs_host_control_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_pcs_host_control_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_reset_sequencer_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_reset_sequencer_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_reset_synchronizer_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_reset_synchronizer_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_xcvr_resync_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_xcvr_resync_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_reset_ctrl_lego_16b.sv SYSTEM_VERILOG_ENCRYPT PATH "mentor/altera_tse_reset_ctrl_lego_16b.sv" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_gmii_aligner_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_gmii_aligner_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_rx_encapsulation_strx_gx_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_rx_encapsulation_strx_gx_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_top_1000_base_x_strx_gx_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_top_1000_base_x_strx_gx_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_top_autoneg_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_top_autoneg_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_top_pcs_strx_gx_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_top_pcs_strx_gx_16b.v" {MENTOR_SPECIFIC}
		add_fileset_file mentor/altera_tse_tx_encapsulation_16b.v VERILOG_ENCRYPT PATH "mentor/altera_tse_tx_encapsulation_16b.v" {MENTOR_SPECIFIC}
    }
    if {1} {
      if {[_is_phy_ip] == "5" } {
      add_fileset_file aldec/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "aldec/nativephy/altera_tse_gxb_aligned_rxsync_16b.v" {ALDEC_SPECIFIC}      
      } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
      add_fileset_file aldec/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "aldec/phyip/altera_tse_gxb_aligned_rxsync_16b.v" {ALDEC_SPECIFIC}
      } else {
      add_fileset_file aldec/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "aldec/alt4gxb/altera_tse_gxb_aligned_rxsync_16b.v" {ALDEC_SPECIFIC}
      }

		add_fileset_file aldec/altera_tse_carrier_sense_16b.v VERILOG_ENCRYPT  PATH "aldec/altera_tse_carrier_sense_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_mdio_reg_16b.v VERILOG_ENCRYPT  PATH "aldec/altera_tse_mdio_reg_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_pcs_control_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_pcs_control_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_pcs_host_control_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_pcs_host_control_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_reset_sequencer_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_reset_sequencer_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_reset_synchronizer_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_reset_synchronizer_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_xcvr_resync_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_xcvr_resync_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_reset_ctrl_lego_16b.sv SYSTEM_VERILOG_ENCRYPT PATH "aldec/altera_tse_reset_ctrl_lego_16b.sv" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_gmii_aligner_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_gmii_aligner_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_rx_encapsulation_strx_gx_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_rx_encapsulation_strx_gx_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_top_1000_base_x_strx_gx_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_top_1000_base_x_strx_gx_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_top_autoneg_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_top_autoneg_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_top_pcs_strx_gx_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_top_pcs_strx_gx_16b.v" {ALDEC_SPECIFIC}
		add_fileset_file aldec/altera_tse_tx_encapsulation_16b.v VERILOG_ENCRYPT PATH "aldec/altera_tse_tx_encapsulation_16b.v" {ALDEC_SPECIFIC}
    }
    if {1} {
      if {[_is_phy_ip] == "5" } {
      add_fileset_file cadence/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "cadence/nativephy/altera_tse_gxb_aligned_rxsync_16b.v" {CADENCE_SPECIFIC}      
      } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
      add_fileset_file cadence/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "cadence/phyip/altera_tse_gxb_aligned_rxsync_16b.v" {CADENCE_SPECIFIC}
      } else {
      add_fileset_file cadence/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "cadence/alt4gxb/altera_tse_gxb_aligned_rxsync_16b.v" {CADENCE_SPECIFIC}
      }

		add_fileset_file cadence/altera_tse_carrier_sense_16b.v VERILOG_ENCRYPT  PATH "cadence/altera_tse_carrier_sense_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_mdio_reg_16b.v VERILOG_ENCRYPT  PATH "cadence/altera_tse_mdio_reg_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_pcs_control_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_pcs_control_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_pcs_host_control_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_pcs_host_control_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_reset_sequencer_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_reset_sequencer_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_reset_synchronizer_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_reset_synchronizer_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_xcvr_resync_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_xcvr_resync_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_reset_ctrl_lego_16b.sv SYSTEM_VERILOG_ENCRYPT PATH "cadence/altera_tse_reset_ctrl_lego_16b.sv" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_gmii_aligner_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_gmii_aligner_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_rx_encapsulation_strx_gx_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_rx_encapsulation_strx_gx_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_top_1000_base_x_strx_gx_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_top_1000_base_x_strx_gx_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_top_autoneg_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_top_autoneg_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_top_pcs_strx_gx_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_top_pcs_strx_gx_16b.v" {CADENCE_SPECIFIC}
		add_fileset_file cadence/altera_tse_tx_encapsulation_16b.v VERILOG_ENCRYPT PATH "cadence/altera_tse_tx_encapsulation_16b.v" {CADENCE_SPECIFIC}
    }
    if {1} {
      if {[_is_phy_ip] == "5" } {
     	add_fileset_file synopsys/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "synopsys/nativephy/altera_tse_gxb_aligned_rxsync_16b.v" {SYNOPSYS_SPECIFIC}
      } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
        add_fileset_file synopsys/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "synopsys/phyip/altera_tse_gxb_aligned_rxsync_16b.v" {SYNOPSYS_SPECIFIC}
      } else {
     	add_fileset_file synopsys/altera_tse_gxb_aligned_rxsync_16b.v VERILOG_ENCRYPT PATH "synopsys/alt4gxb/altera_tse_gxb_aligned_rxsync_16b.v" {SYNOPSYS_SPECIFIC}
      }

		add_fileset_file synopsys/altera_tse_carrier_sense_16b.v VERILOG_ENCRYPT  PATH "synopsys/altera_tse_carrier_sense_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_mdio_reg_16b.v VERILOG_ENCRYPT  PATH "synopsys/altera_tse_mdio_reg_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_pcs_control_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_pcs_control_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_pcs_host_control_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_pcs_host_control_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_reset_sequencer_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_reset_sequencer_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_reset_synchronizer_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_reset_synchronizer_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_xcvr_resync_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_xcvr_resync_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_reset_ctrl_lego_16b.sv SYSTEM_VERILOG_ENCRYPT PATH "synopsys/altera_tse_reset_ctrl_lego_16b.sv" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_gmii_aligner_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_gmii_aligner_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_rx_encapsulation_strx_gx_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_rx_encapsulation_strx_gx_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_top_1000_base_x_strx_gx_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_top_1000_base_x_strx_gx_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_top_autoneg_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_top_autoneg_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_top_pcs_strx_gx_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_top_pcs_strx_gx_16b.v" {SYNOPSYS_SPECIFIC}
		add_fileset_file synopsys/altera_tse_tx_encapsulation_16b.v VERILOG_ENCRYPT PATH "synopsys/altera_tse_tx_encapsulation_16b.v" {SYNOPSYS_SPECIFIC}
    }
}

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------
add_parameter DEVICE_FAMILY STRING "Stratix IV"
set_parameter_property DEVICE_FAMILY DISPLAY_NAME "Device Family"
set_parameter_property DEVICE_FAMILY DESCRIPTION "Target Device Family for Ethernet 2.5G PHY IP"
# set_parameter_property DEVICE_FAMILY ALLOWED_RANGES {"Arria II GX" "Stratix IV" "Arria V"}
set_parameter_property DEVICE_FAMILY VISIBLE False
set_parameter_property DEVICE_FAMILY IS_HDL_PARAMETER true
set_parameter_property DEVICE_FAMILY SYSTEM_INFO DEVICE_FAMILY

add_parameter STARTING_CHANNEL_NUMBER INTEGER 0
set_parameter_property STARTING_CHANNEL_NUMBER DISPLAY_NAME "Starting Channel Number"
set_parameter_property STARTING_CHANNEL_NUMBER allowed_ranges {"0" "4" "8"}
set_parameter_property STARTING_CHANNEL_NUMBER DESCRIPTION "Starting Channel Number"
set_parameter_property STARTING_CHANNEL_NUMBER HDL_PARAMETER true

add_parameter CONFIGURATION INTEGER 0 "Choose Configuration for 0:PHY only or 1:PHY & MAC"
set_parameter_property CONFIGURATION VISIBLE False
set_parameter_property CONFIGURATION DESCRIPTION "Internal usage: Phy only or MAC & PHY seclection for sdc file generation"

add_parameter DEV_VERSION INTEGER 0
set_parameter_property DEV_VERSION DISPLAY_NAME "Device Version"
set_parameter_property DEV_VERSION DESCRIPTION "Device Version"
set_parameter_property DEV_VERSION HDL_PARAMETER 1
set_parameter_property DEV_VERSION DERIVED 1
set_parameter_property DEV_VERSION VISIBLE 0

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gmii_rx_data
# | 
add_interface gmii_rx_data avalon_streaming start
set_interface_property gmii_rx_data dataBitsPerSymbol 16
set_interface_property gmii_rx_data errorDescriptor ""
set_interface_property gmii_rx_data maxChannel 0
set_interface_property gmii_rx_data readyLatency 0
set_interface_property gmii_rx_data ASSOCIATED_CLOCK rx_clk
set_interface_property gmii_rx_data ENABLED true

add_interface_port gmii_rx_data gmii_rx_d data Output 16
add_interface_port gmii_rx_data gmii_rx_err error Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gmii_rx_enable
# | 
add_interface gmii_rx_enable avalon_streaming start
set_interface_property gmii_rx_enable dataBitsPerSymbol 2
set_interface_property gmii_rx_enable errorDescriptor ""
set_interface_property gmii_rx_enable maxChannel 0
set_interface_property gmii_rx_enable readyLatency 0
set_interface_property gmii_rx_enable ASSOCIATED_CLOCK rx_clk
set_interface_property gmii_rx_enable ENABLED true

add_interface_port gmii_rx_enable gmii_rx_dv data Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_mm_csr
# | 
add_interface avalon_mm_csr avalon end
set_interface_property avalon_mm_csr addressAlignment DYNAMIC
set_interface_property avalon_mm_csr burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_csr explicitAddressSpan 0
set_interface_property avalon_mm_csr holdTime 0
set_interface_property avalon_mm_csr isMemoryDevice false
set_interface_property avalon_mm_csr isNonVolatileStorage false
set_interface_property avalon_mm_csr linewrapBursts false
set_interface_property avalon_mm_csr maximumPendingReadTransactions 0
set_interface_property avalon_mm_csr printableDevice false
set_interface_property avalon_mm_csr readLatency 0
set_interface_property avalon_mm_csr readWaitTime 0
set_interface_property avalon_mm_csr setupTime 0
set_interface_property avalon_mm_csr timingUnits Cycles
set_interface_property avalon_mm_csr writeWaitTime 0
set_interface_property avalon_mm_csr ASSOCIATED_CLOCK clk
set_interface_property avalon_mm_csr associatedReset reset
set_interface_property avalon_mm_csr ENABLED true

add_interface_port avalon_mm_csr readdata readdata Output 32
add_interface_port avalon_mm_csr waitrequest waitrequest Output 1
add_interface_port avalon_mm_csr address address Input 5
add_interface_port avalon_mm_csr read read Input 1
add_interface_port avalon_mm_csr writedata writedata Input 32
add_interface_port avalon_mm_csr write write Input 1

# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gmii_tx_data
# | 
add_interface gmii_tx_data avalon_streaming end
set_interface_property gmii_tx_data dataBitsPerSymbol 16
set_interface_property gmii_tx_data errorDescriptor ""
set_interface_property gmii_tx_data maxChannel 0
set_interface_property gmii_tx_data readyLatency 0

set_interface_property gmii_tx_data ENABLED true
set_interface_property gmii_tx_data ASSOCIATED_CLOCK tx_clk
add_interface_port gmii_tx_data gmii_tx_d data Input 16
add_interface_port gmii_tx_data gmii_tx_err error Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gmii_tx_enable
# | 
add_interface gmii_tx_enable avalon_streaming end
set_interface_property gmii_tx_enable dataBitsPerSymbol 2
set_interface_property gmii_tx_enable errorDescriptor ""
set_interface_property gmii_tx_enable maxChannel 0
set_interface_property gmii_tx_enable readyLatency 0
set_interface_property gmii_tx_enable ASSOCIATED_CLOCK tx_clk
set_interface_property gmii_tx_enable ENABLED true

add_interface_port gmii_tx_enable gmii_tx_en data Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_clk
# | 
add_interface tx_clk clock start
set_interface_property tx_clk ENABLED true
set_interface_property tx_clk clockRateKnown "true"
set_interface_property tx_clk clockRate "156250000"
#set_interface_property tx_clk associatedDirectClock tx_clk
add_interface_port tx_clk tx_clk clk Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_clk_reset
# | 
add_interface tx_clk_reset reset end
set_interface_property tx_clk_reset ENABLED true
add_interface_port tx_clk_reset reset_tx_clk reset Input 1
set_interface_property tx_clk_reset ASSOCIATED_CLOCK tx_clk
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_clk
# | 
add_interface rx_clk clock start
set_interface_property rx_clk ENABLED true
set_interface_property rx_clk clockRateKnown "true"
set_interface_property rx_clk clockRate "156250000"
#set_interface_property rx_clk associatedDirectClock rx_clk
add_interface_port rx_clk rx_clk clk Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_clk_reset
# | 
add_interface rx_clk_reset reset end
set_interface_property rx_clk_reset ENABLED true
add_interface_port rx_clk_reset reset_rx_clk reset Input 1
set_interface_property rx_clk_reset ASSOCIATED_CLOCK rx_clk
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset ENABLED true
add_interface_port reset reset reset Input 1
set_interface_property reset ASSOCIATED_CLOCK clk
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point led_link
# | 
add_interface led_link conduit start
set_interface_property led_link ENABLED true
add_interface_port led_link led_link export Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point led_char_err
# | 
add_interface led_char_err conduit start
set_interface_property led_char_err ENABLED true
add_interface_port led_char_err led_char_err export Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point led_disp_err
# | 
add_interface led_disp_err conduit start
set_interface_property led_disp_err ENABLED true
add_interface_port led_disp_err led_disp_err export Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point led_an
# | 
add_interface led_an conduit start
set_interface_property led_an ENABLED true
add_interface_port led_an led_an export Output 1
# | 
# +-----------------------------------


proc elaborate {} {
    # Arria 10 device
    if {[_is_phy_ip] == "5"} {
       # rx_runningdisp
       add_interface rx_runningdisp conduit end
       set_interface_property rx_runningdisp ENABLED true
       add_interface_port rx_runningdisp rx_runningdisp rx_runningdisp Input 2 

       # rx_disperr
       add_interface rx_disperr conduit end
       set_interface_property rx_disperr ENABLED true
       add_interface_port rx_disperr rx_disperr rx_disperr Input 2

       # rx_errdetect
       add_interface rx_errdetect conduit end
       set_interface_property rx_errdetect ENABLED true
       add_interface_port rx_errdetect rx_errdetect rx_errdetect Input 2

       # rx_patterndetect
       add_interface rx_patterndetect conduit end
       set_interface_property rx_patterndetect ENABLED true
       add_interface_port rx_patterndetect rx_patterndetect rx_patterndetect Input 2

       # rx_syncstatus
       add_interface rx_syncstatus conduit end
       set_interface_property rx_syncstatus ENABLED true
       add_interface_port rx_syncstatus rx_syncstatus rx_syncstatus Input 2

       # rx_rmfifostatus
       add_interface rx_rmfifostatus conduit end
       set_interface_property rx_rmfifostatus ENABLED true
       add_interface_port rx_rmfifostatus rx_rmfifostatus rx_rmfifostatus Input 4

       # tx_clkout
       add_interface tx_clkout conduit end
       set_interface_property tx_clkout ENABLED true
       add_interface_port tx_clkout tx_clkout clk Input 1

       # rx_clkout
       add_interface rx_clkout conduit end
       set_interface_property rx_clkout ENABLED true
       add_interface_port rx_clkout rx_clkout clk Input 1
        
       # loopback tx/rx_clkout back to native_phy
       # tx_clkout_lb
       add_interface tx_clkout_lb conduit start
       set_interface_property tx_clkout_lb ENABLED true
       add_interface_port tx_clkout_lb tx_clkout_lb clk Output 1
       # rx_clkout_lb
       add_interface rx_clkout_lb conduit start
       set_interface_property rx_clkout_lb ENABLED true
       add_interface_port rx_clkout_lb rx_clkout_lb clk Output 1
       
       # tx_ready
       add_interface tx_ready conduit end
       set_interface_property tx_ready ENABLED true
       add_interface_port tx_ready tx_ready export Input 1

       # rx_ready
       add_interface rx_ready conduit end
       set_interface_property rx_ready ENABLED true
       add_interface_port rx_ready rx_ready export Input 1

       # tx_parallel_data
       add_interface tx_parallel_data conduit end
       set_interface_property tx_parallel_data ENABLED true
       add_interface_port tx_parallel_data tx_parallel_data tx_parallel_data Output 16

       # tx_datak
       add_interface tx_datak conduit end
       set_interface_property tx_datak ENABLED true
       add_interface_port tx_datak tx_datak tx_datak Output 2

       # rx_parallel_data
       add_interface rx_parallel_data conduit end
       set_interface_property rx_parallel_data ENABLED true
       add_interface_port rx_parallel_data rx_parallel_data rx_parallel_data Input 16

       # rx_datak
       add_interface rx_datak conduit end
       set_interface_property rx_datak ENABLED true
       add_interface_port rx_datak rx_datak rx_datak Input 2

       # rx_recovered_clk_in
       add_interface rx_recovered_clk_in conduit end
       set_interface_property rx_recovered_clk_in ENABLED true
       add_interface_port rx_recovered_clk_in rx_recovered_clk_in clk Input 1

       # rx_recovered_clk
       add_interface rx_recovered_clk clock start
       set_interface_property rx_recovered_clk ENABLED true
       add_interface_port rx_recovered_clk rx_recovered_clk clk Output 1

       # unused_tx_parallel_data
       add_interface unused_tx_parallel_data conduit end
       set_interface_property unused_tx_parallel_data ENABLED true
       add_interface_port unused_tx_parallel_data unused_tx_parallel_data unused_tx_parallel_data Output 110

       # unused_rx_parallel_data
       add_interface unused_rx_parallel_data conduit end
       set_interface_property unused_rx_parallel_data ENABLED true
       add_interface_port unused_rx_parallel_data unused_rx_parallel_data unused_rx_parallel_data Input 96

    } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
        
        # phy_pll_refclk
        #add_interface phy_pll_refclk clock start
        #set_interface_property phy_pll_refclk ENABLED true
        #add_interface_port phy_pll_refclk phy_pll_refclk clk Output 1
        
        # phy_mgmt_clk
        add_interface phy_mgmt_clk clock start
        set_interface_property phy_mgmt_clk ENABLED true
        add_interface_port phy_mgmt_clk phy_mgmt_clk clk Output 1
        
        # phy_mgmt_clk_reset
        add_interface phy_mgmt_clk_reset reset start
        set_interface_property phy_mgmt_clk_reset ENABLED true
        set_interface_property phy_mgmt_clk_reset ASSOCIATED_CLOCK phy_mgmt_clk
        set_interface_property phy_mgmt_clk_reset associatedResetSinks reset
        add_interface_port phy_mgmt_clk_reset phy_mgmt_clk_reset reset Output 1
        
        # phy_mgmt_csr
        add_interface phy_mgmt_csr avalon start
        set_interface_property phy_mgmt_csr burstOnBurstBoundariesOnly false
        set_interface_property phy_mgmt_csr holdTime 0
        set_interface_property phy_mgmt_csr linewrapBursts false
        set_interface_property phy_mgmt_csr maximumPendingReadTransactions 0
        set_interface_property phy_mgmt_csr readLatency 0
        set_interface_property phy_mgmt_csr readWaitTime 0
        set_interface_property phy_mgmt_csr setupTime 0
        set_interface_property phy_mgmt_csr timingUnits Cycles
        set_interface_property phy_mgmt_csr writeWaitTime 0
        set_interface_property phy_mgmt_csr ASSOCIATED_CLOCK phy_mgmt_clk
        set_interface_property phy_mgmt_csr associatedReset phy_mgmt_clk_reset
        set_interface_property phy_mgmt_csr addressUnits "WORDS"
        set_interface_property phy_mgmt_csr ENABLED true
        
        add_interface_port phy_mgmt_csr phy_mgmt_csr_readdata readdata Input 32
        add_interface_port phy_mgmt_csr phy_mgmt_csr_waitrequest waitrequest Input 1
        add_interface_port phy_mgmt_csr phy_mgmt_csr_address address Output 9
        add_interface_port phy_mgmt_csr phy_mgmt_csr_read read Output 1
        add_interface_port phy_mgmt_csr phy_mgmt_csr_writedata writedata Output 32
        add_interface_port phy_mgmt_csr phy_mgmt_csr_write write Output 1
        
        # rx_runningdisp
        add_interface rx_runningdisp conduit end
        set_interface_property rx_runningdisp ENABLED true
        add_interface_port rx_runningdisp rx_runningdisp export Input 2
        
        # rx_disperr
        add_interface rx_disperr conduit end
        set_interface_property rx_disperr ENABLED true
        add_interface_port rx_disperr rx_disperr export Input 2
        
        # rx_errdetect
        add_interface rx_errdetect conduit end
        set_interface_property rx_errdetect ENABLED true
        add_interface_port rx_errdetect rx_errdetect export Input 2
        
        # rx_patterndetect
        add_interface rx_patterndetect conduit end
        set_interface_property rx_patterndetect ENABLED true
        add_interface_port rx_patterndetect rx_patterndetect export Input 2
        
        # rx_syncstatus
        add_interface rx_syncstatus conduit end
        set_interface_property rx_syncstatus ENABLED true
        add_interface_port rx_syncstatus rx_syncstatus export Input 2
        
       # rx_bitslipboundaryselectout 
       # (unused port - created to fetch signal from custom phy)
       add_interface rx_bitslipboundaryselectout conduit end
       set_interface_property rx_bitslipboundaryselectout ENABLED true
       add_interface_port rx_bitslipboundaryselectout rx_bitslipboundaryselectout export Input 5
       
        # rx_rmfifodatainserted
        add_interface rx_rmfifodatainserted conduit end
        set_interface_property rx_rmfifodatainserted ENABLED true
        add_interface_port rx_rmfifodatainserted rx_rmfifodatainserted export Input 2
        
        # rx_rmfifodatadeleted
        add_interface rx_rmfifodatadeleted conduit end
        set_interface_property rx_rmfifodatadeleted ENABLED true
        add_interface_port rx_rmfifodatadeleted rx_rmfifodatadeleted export Input 2
        
        # rx_rlv
        add_interface rx_rlv conduit end
        set_interface_property rx_rlv ENABLED true
        add_interface_port rx_rlv rx_rlv export Input 1
        
        # tx_clkout
        add_interface tx_clkout conduit end
        set_interface_property tx_clkout ENABLED true
        add_interface_port tx_clkout tx_clkout export Input 1
        
        # rx_clkout
        add_interface rx_clkout conduit end
        set_interface_property rx_clkout ENABLED true
        add_interface_port rx_clkout rx_clkout export Input 1

        # tx_ready
        add_interface tx_ready conduit end
        set_interface_property tx_ready ENABLED true
        add_interface_port tx_ready tx_ready export Input 1

        # rx_ready
        add_interface rx_ready conduit end
        set_interface_property rx_ready ENABLED true
        add_interface_port rx_ready rx_ready export Input 1

        # rx_recovered_clk
        #add_interface rx_recovered_clk conduit end
        #set_interface_property rx_recovered_clk ENABLED true
        #add_interface_port rx_recovered_clk rx_recovered_clk export Input 1		

        # tx_parallel_data
        add_interface tx_parallel_data conduit end
        set_interface_property tx_parallel_data ENABLED true
        add_interface_port tx_parallel_data tx_parallel_data export Output 16
        
        # tx_datak
        add_interface tx_datak conduit end
        set_interface_property tx_datak ENABLED true
        add_interface_port tx_datak tx_datak export Output 2
        
        # rx_parallel_data
        add_interface rx_parallel_data conduit end
        set_interface_property rx_parallel_data ENABLED true
        add_interface_port rx_parallel_data rx_parallel_data export Input 16
        
        # rx_datak
        add_interface rx_datak conduit end
        set_interface_property rx_datak ENABLED true
        add_interface_port rx_datak rx_datak export Input 2
        
    } else {

        # +-----------------------------------
        # | connection point ref_clk
        # | 
        add_interface ref_clk clock end
        set_interface_property ref_clk ENABLED true
        add_interface_port ref_clk ref_clk clk Input 1
        # | 
        # +-----------------------------------

        # +-----------------------------------
        # | connection point gxb_cal_blk_clk
        # | 
        add_interface gxb_cal_blk_clk conduit end
        set_interface_property gxb_cal_blk_clk ENABLED true
        add_interface_port gxb_cal_blk_clk gxb_cal_blk_clk export Input 1
        # | 
        # +-----------------------------------
        
        # +-----------------------------------
        # | connection point pll_powerdown
        # | 
        add_interface pll_powerdown conduit end
        set_interface_property pll_powerdown ENABLED true
        add_interface_port pll_powerdown pll_powerdown export Input 1
        # | 
        # +-----------------------------------
        
        # +-----------------------------------
        # | connection point gxb_pwrdn_in
        # | 
        add_interface gxb_pwrdn_in conduit end
        set_interface_property gxb_pwrdn_in ENABLED true
        add_interface_port gxb_pwrdn_in gxb_pwrdn_in export Input 1
        # | 
        # +-----------------------------------
        
        # +-----------------------------------
        # | connection point reconfig_fromgxb
        # | 
        add_interface reconfig_fromgxb conduit start
        set_interface_property reconfig_fromgxb ENABLED true
        add_interface_port reconfig_fromgxb reconfig_fromgxb export Output 17
        # | 
        # +-----------------------------------
        
        # +-----------------------------------
        # | connection point reconfig_togxb
        # | 
        add_interface reconfig_togxb conduit end
        set_interface_property reconfig_togxb ENABLED true
        add_interface_port reconfig_togxb reconfig_togxb export Input 4
        # | 
        # +-----------------------------------

        # +-----------------------------------
        # | connection point reconfig_busy
        # | 
        add_interface reconfig_busy conduit end
        set_interface_property reconfig_busy ENABLED true
        add_interface_port reconfig_busy reconfig_busy export Input 1
        # | 
        # +-----------------------------------

        # +-----------------------------------
        # | connection point reconfig_clk
        # | 
        add_interface reconfig_clk conduit end
        set_interface_property reconfig_clk ENABLED true
        add_interface_port reconfig_clk reconfig_clk export Input 1
        # | 
        # +-----------------------------------

        # +-----------------------------------
        # | connection point rx_recovered_clk
        # | 
        add_interface rx_recovered_clk conduit start
        set_interface_property rx_recovered_clk ENABLED true
        add_interface_port rx_recovered_clk rx_recovered_clk export Output 1
        # | 
        # +-----------------------------------

        # +-----------------------------------
        # | connection point tx_pll_locked
        # | 
        add_interface tx_pll_locked conduit start
        set_interface_property tx_pll_locked ENABLED true
        add_interface_port tx_pll_locked tx_pll_locked export Output 1
        # | 
        # +-----------------------------------  

        # +-----------------------------------
        # | connection point txp
        # | 
        add_interface txp conduit start
        set_interface_property txp ENABLED true
        add_interface_port txp txp export Output 1
        # | 
        # +-----------------------------------
        
        # +-----------------------------------
        # | connection point rxp
        # | 
        add_interface rxp conduit end
        set_interface_property rxp ENABLED true
        add_interface_port rxp rxp export Input 1
        # | 
        # +-----------------------------------

        
    }
}  
  
  
add_fileset sdc QUARTUS_SYNTH sdc_proc
proc sdc_proc { none } {

	# +-----------------------------------
	# | files
	# |
    if {[_is_phy_ip] == "5"} {
                add_fileset_file altera_eth_2_5g_pcs_pma_16b.v VERILOG PATH "nativephy/altera_eth_2_5g_pcs_pma_16b.v"
                add_fileset_file altera_tse_pcs_pma_gige_16b.v VERILOG PATH "nativephy/altera_tse_pcs_pma_gige_16b.v"
                add_fileset_file altera_tse_gxb_aligned_rxsync_16b.v VERILOG PATH "nativephy/altera_tse_gxb_aligned_rxsync_16b.v"
    } elseif {[_is_phy_ip] == "1" || [_is_phy_ip] == "2" || [_is_phy_ip] == "3" || [_is_phy_ip] == "4"} {
		add_fileset_file altera_eth_2_5g_pcs_pma_16b.v VERILOG PATH "phyip/altera_eth_2_5g_pcs_pma_16b.v" 
		add_fileset_file altera_tse_pcs_pma_gige_16b.v VERILOG PATH "phyip/altera_tse_pcs_pma_gige_16b.v"
                add_fileset_file altera_tse_gxb_aligned_rxsync_16b.v VERILOG PATH "phyip/altera_tse_gxb_aligned_rxsync_16b.v"
    } else {
		add_fileset_file altera_eth_2_5g_pcs_pma_16b.v VERILOG PATH "alt4gxb/altera_eth_2_5g_pcs_pma_16b.v" 
		add_fileset_file altera_tse_alt4gxb_gige_16b.v VERILOG PATH "alt4gxb/altera_tse_alt4gxb_gige_16b.v"
		add_fileset_file altera_tse_gxb_gige_inst_16b.v VERILOG PATH "alt4gxb/altera_tse_gxb_gige_inst_16b.v"
		add_fileset_file altera_tse_pcs_pma_gige_16b.v VERILOG PATH "alt4gxb/altera_tse_pcs_pma_gige_16b.v"
      add_fileset_file altera_tse_gxb_aligned_rxsync_16b.v VERILOG PATH "alt4gxb/altera_tse_gxb_aligned_rxsync_16b.v"
    }	
    add_fileset_file altera_std_synchronizer_nocut.v VERILOG PATH "../../primitives/altera_std_synchronizer/altera_std_synchronizer_nocut.v"
    add_fileset_file altera_tse_carrier_sense_16b.v VERILOG PATH altera_tse_carrier_sense_16b.v
	add_fileset_file altera_tse_mdio_reg_16b.v VERILOG PATH altera_tse_mdio_reg_16b.v
	add_fileset_file altera_tse_pcs_control_16b.v VERILOG PATH altera_tse_pcs_control_16b.v
	add_fileset_file altera_tse_pcs_host_control_16b.v VERILOG PATH altera_tse_pcs_host_control_16b.v
	add_fileset_file altera_tse_reset_sequencer_16b.v VERILOG PATH altera_tse_reset_sequencer_16b.v
	add_fileset_file altera_tse_reset_synchronizer_16b.v VERILOG PATH altera_tse_reset_synchronizer_16b.v
	add_fileset_file altera_tse_xcvr_resync_16b.v VERILOG PATH altera_tse_xcvr_resync_16b.v
	add_fileset_file altera_tse_reset_ctrl_lego_16b.sv SYSTEM_VERILOG PATH altera_tse_reset_ctrl_lego_16b.sv
	add_fileset_file altera_tse_gmii_aligner_16b.v VERILOG PATH altera_tse_gmii_aligner_16b.v
	add_fileset_file altera_tse_rx_encapsulation_strx_gx_16b.v VERILOG PATH altera_tse_rx_encapsulation_strx_gx_16b.v
	add_fileset_file altera_tse_top_1000_base_x_strx_gx_16b.v VERILOG PATH altera_tse_top_1000_base_x_strx_gx_16b.v
	add_fileset_file altera_tse_top_autoneg_16b.v VERILOG PATH altera_tse_top_autoneg_16b.v
	add_fileset_file altera_tse_top_pcs_strx_gx_16b.v VERILOG PATH altera_tse_top_pcs_strx_gx_16b.v
	add_fileset_file altera_tse_tx_encapsulation_16b.v VERILOG PATH altera_tse_tx_encapsulation_16b.v
	add_fileset_file altera_tse_top_1000_base_x_strx_gx_16b.ocp OTHER PATH altera_tse_top_1000_base_x_strx_gx_16b.ocp
	# | 
	# +-----------------------------------
	
	#Generating SDC script...
	set configuration [get_parameter_value CONFIGURATION]    
	set constraints [list]
	if { $configuration == "1" } {
        #MAC & PHY        
		lappend constraints "derive_pll_clocks"
		lappend constraints "derive_clock_uncertainty\n"
		lappend constraints "create_clock -period \"122 MHz\" -name \{clk_122\} \[get_ports clk_122\]"
		lappend constraints "create_clock -period \"39 MHz\" -name \{clk_39\} \[get_ports clk_39\]"
    	if {[_is_phy_ip] == "1"
        || [_is_phy_ip] == "2" } {
                        # Stratix V
		        lappend constraints "create_clock -period \"125 MHz\" -name \{ref_clk\[0\]\} \[get_ports ref_clk\[0\]\]"
			lappend constraints "set_clock_groups -asynchronous -group \{clk_122\} -group \{clk_39\} -group \{ref_clk\[0\]\} -group \{*inst_*_pcs_ch|inst_*_hssi_8g_tx_pcs|wys|clkout\}"
    	} elseif {[_is_phy_ip] == "3"
        || [_is_phy_ip] == "4" } {
                        # Arria V
		        lappend constraints "create_clock -period \"125 MHz\" -name \{ref_clk\[0\]\} \[get_ports ref_clk\[0\]\]"
			lappend constraints "set_clock_groups -asynchronous -group \{clk_122\} -group \{clk_39\} -group \{ref_clk\[0\]\} -group \{*inst_*_pcs_ch|inst_*_hssi_8g_tx_pcs|wys|txpmalocalclk\}"
    	} elseif {[_is_phy_ip] == "5" } {
                        # Arria 10
		        lappend constraints "create_clock -period \"125 MHz\" -name \{rx_cdr_refclk_clk\} \[get_ports rx_cdr_refclk_clk\]"        
		        lappend constraints "create_clock -period \"50 MHz\" -name \{reconfig_clk_clk\[0\]\} \[get_ports reconfig_clk_clk\[0\]\]" 
			lappend constraints "set_clock_groups -asynchronous -group \{clk_122\} -group \{clk_39\} -group \{rx_cdr_refclk_clk\} -group \{*tx_clkout*\}"
        } else {
		        lappend constraints "create_clock -period \"125 MHz\" -name \{ref_clk\} \[get_ports ref_clk\]"
			lappend constraints "create_clock -period \"50 MHz\" -name \{gxb_cal_blk_clk\} \[get_ports gxb_cal_blk_clk\]"
			lappend constraints "create_clock -period \"50 MHz\" -name \{reconfig_clk\} \[get_ports reconfig_clk\]\n"
			lappend constraints "set_clock_groups -asynchronous -group \{clk_122\} -group \{clk_39\} -group \{ref_clk\} -group \{gxb_cal_blk_clk\} -group \{reconfig_clk\} -group \{*|altera_tse_alt4gxb_gige_16b_alt4gxb_deba_component|transmit_pcs0|clkout*\}"		
    	}	
        
        #synchronizer
		lappend constraints "#synchronizer"
		lappend constraints "if \{ \[string equal \"quartus_sta\" $\:\:TimeQuestInfo\(nameofexecutable\)\] \} \{"
		lappend constraints "   set_max_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] 100ns"
		lappend constraints "   set_min_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] -100ns"
		lappend constraints "\} else \{"
		lappend constraints "   set_net_delay -from \[get_pins -compatibility_mode *|q\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] -max 4ns"
		lappend constraints "   set_max_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] 6ns"
		lappend constraints "   set_min_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] -100ns"
		lappend constraints "\}"
        
		set sdc_file_name altera_eth_2_5g_system
	} else {
        #PHY only               
		lappend constraints "derive_pll_clocks"
		lappend constraints "derive_clock_uncertainty\n"
		lappend constraints "create_clock -period \"122 MHz\" -name \{clk\} \[get_ports clk\]"
    	if {[_is_phy_ip] == "1"
        || [_is_phy_ip] == "2" } {
                        # Stratix V
		        lappend constraints "create_clock -period \"125 MHz\" -name \{ref_clk\[0\]\} \[get_ports ref_clk\[0\]\]"  
			lappend constraints "set_clock_groups -asynchronous -group \{clk\} -group \{ref_clk\[0\]\} -group \{*inst_*_pcs_ch|inst_*_hssi_8g_tx_pcs|wys|clkout\}"  
    	} elseif {[_is_phy_ip] == "3"
        || [_is_phy_ip] == "4" } {                        
                        # Arria V
		        lappend constraints "create_clock -period \"125 MHz\" -name \{ref_clk\[0\]\} \[get_ports ref_clk\[0\]\]"  
			lappend constraints "set_clock_groups -asynchronous -group \{clk\} -group \{ref_clk\[0\]\} -group \{*inst_*_pcs_ch|inst_*_hssi_8g_tx_pcs|wys|txpmalocalclk\}"  
    	} elseif {[_is_phy_ip] == "5" } {
                        # Arria 10
		        lappend constraints "create_clock -period \"125 MHz\" -name \{rx_cdr_refclk_clk\} \[get_ports rx_cdr_refclk_clk\]"
		        lappend constraints "create_clock -period \"50 MHz\" -name \{reconfig_clk_clk\[0\]\} \[get_ports reconfig_clk_clk\[0\]\]"  
			lappend constraints "set_clock_groups -asynchronous -group \{clk\} -group \{rx_cdr_refclk_clk\} -group \{*tx_clkout*\}"
        } else {
		        lappend constraints "create_clock -period \"125 MHz\" -name \{ref_clk\} \[get_ports ref_clk\]"		
			lappend constraints "create_clock -period \"50 MHz\" -name \{gxb_cal_blk_clk\} \[get_ports gxb_cal_blk_clk\]"
			lappend constraints "create_clock -period \"50 MHz\" -name \{reconfig_clk\} \[get_ports reconfig_clk\]\n"
			lappend constraints "set_clock_groups -asynchronous -group \{clk\} -group \{ref_clk\} -group \{gxb_cal_blk_clk\} -group \{reconfig_clk\} -group \{*|altera_tse_alt4gxb_gige_16b_alt4gxb_deba_component|transmit_pcs0|clkout*\}"			
    	}	
        
        #synchronizer
		lappend constraints "#synchronizer"
		lappend constraints "if \{ \[string equal \"quartus_sta\" $\:\:TimeQuestInfo\(nameofexecutable\)\] \} \{"
		lappend constraints "   set_max_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] 100ns"
		lappend constraints "   set_min_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] -100ns"
		lappend constraints "\} else \{"
		lappend constraints "   set_net_delay -from \[get_pins -compatibility_mode *|q\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] -max 4ns"
		lappend constraints "   set_max_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] 6ns"
		lappend constraints "   set_min_delay -from \[get_registers *\] -to \[get_registers *altera_eth_2_5g_pcs_pma_16b*altera_std_synchronizer_nocut:*|din_s1\] -100ns"
		lappend constraints "\}"

		set sdc_file_name altera_eth_2_5g_phy	
	}
        # Stratix V set multicycle path
    	if {[_is_phy_ip] == "1" 
        || [_is_phy_ip] == "2" } {
	        lappend constraints "set_multicycle_path -from \{*\|altera_xcvr_custom:xcvr_phy\|sv_xcvr_custom_nr:S5|sv_xcvr_custom_native:transceiver_core\|sv_xcvr_native:gen.sv_xcvr_native_insts\[0\].gen_bonded_group.sv_xcvr_native_inst\|sv_pcs:inst_sv_pcs\|sv_pcs_ch:ch\[0\].inst_sv_pcs_ch\|sv_hssi_8g_rx_pcs_rbc:inst_sv_hssi_8g_rx_pcs\|wys~SYNC_DATA_REG21\} -to\ \{*\|altera_tse_pcs_pma_gige_16b:altera_tse_pcs_pma_gige_inst\|altera_tse_gxb_aligned_rxsync_16b:the_altera_tse_gxb_aligned_rxsync_16b\|alt_runlengthviolation_latched\} -setup -end 2"
	        lappend constraints "set_multicycle_path -from \{*\|altera_xcvr_custom:xcvr_phy\|sv_xcvr_custom_nr:S5|sv_xcvr_custom_native:transceiver_core\|sv_xcvr_native:gen.sv_xcvr_native_insts\[0\].gen_bonded_group.sv_xcvr_native_inst\|sv_pcs:inst_sv_pcs\|sv_pcs_ch:ch\[0\].inst_sv_pcs_ch\|sv_hssi_8g_rx_pcs_rbc:inst_sv_hssi_8g_rx_pcs\|wys~SYNC_DATA_REG21\} -to\ \{*\|altera_tse_pcs_pma_gige_16b:altera_tse_pcs_pma_gige_inst\|altera_tse_gxb_aligned_rxsync_16b:the_altera_tse_gxb_aligned_rxsync_16b\|alt_runlengthviolation_latched\} -hold -end 2"
        }


	set constraints_text [join $constraints \n]

	add_fileset_file $sdc_file_name.sdc SDC TEXT $constraints_text	
}

proc _is_phy_ip {} {
    set device_family [get_parameter_value DEVICE_FAMILY]
    
    if {![string compare $device_family "Stratix V"]} {
        return 1;
    } elseif {![string compare $device_family "Arria V GZ"]} {
        return 2;
    } elseif {![string compare $device_family "Arria V"]} {
        return 3;
    } elseif {![string compare $device_family "Cyclone V"]} {
        return 4;
    } elseif {![string compare $device_family "Arria 10"]} {
        return 5;
    } else {
        return 0;
    }



}

#################################################################################################
# Validate
#################################################################################################
proc validate {} {
   validate_version
}

###################################################################################
# Called during validate callback to calculate the core_version 
# and dev_version value
###################################################################################
proc validate_version {} {

   set version_val [get_module_property VERSION]
   set version_items [split $version_val "."]
   set version_num [lindex $version_items 0]
   set version_dot_num [lindex $version_items 1]

   set version_number [expr [expr $version_num << 8] | $version_dot_num]
   
   set_parameter_value DEV_VERSION $version_number
}
