# Module name strings
HWTCL_MODULE_DISPLAY_NAME = Simulation Checker for EMIF Example Traffic Generator
HWTCL_MODULE_DESCRIPTION = Altera External Memory Interface Simulation Checker for Example Avalon Traffic Generator
