# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 13.1
# Fri May 17 14:55:02 PDT 2013
# DO NOT MODIFY


#
#
# request TCL package from ACDS version
#
# Case 198687
package require -exact qsys 14.1

sopc::preview_add_transform name preview_avalon_mm_transform

#
# module altera_pcie_sriov_dma_desc_ctl
#
set_module_property DESCRIPTION "Example : Descriptor Controller that manage either DMA-Read or DMA-Write controller"
set_module_property NAME altera_pcie_sriov_dma_desc_ctl
set_module_property VERSION 18.1
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/PCI Express/Example Design Components"
set_module_property AUTHOR "PCIe IPD"
set_module_property DISPLAY_NAME "Example : PCIe SR-IOV Descriptor controller for one DMA engine"
set_module_property ELABORATION_CALLBACK elaboration_callback


# # +-----------------------------------
# # | Component Properties
#   |
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property instantiateInSystemModule "true"
set_module_property HIDE_FROM_QUARTUS true
set_module_property HIDE_FROM_QSYS true
set_module_property INTERNAL true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Stratix V" "ARRIA V GZ" "Arria 10"}



#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_pcie_sriov_dma_desc_ctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_pcie_sriov_dma_desc_ctl.sv SYSTEM_VERILOG PATH altera_pcie_sriov_dma_desc_ctl.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_pcie_sriov_dma_desc_ctl
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_pcie_sriov_dma_desc_ctl.sv SYSTEM_VERILOG PATH altera_pcie_sriov_dma_desc_ctl.sv


#
# parameters
#
   set group_name "Descriptor Controller Settings"
   # FUNC_NUM
   add_parameter          FUNC_NUM integer 0
   set_parameter_property FUNC_NUM DISPLAY_NAME "Assigned Function Number"
   set_parameter_property FUNC_NUM ALLOWED_RANGES {"0:PF0" "128:VF0" "129:VF1" "130:VF2" "131:VF3" "132:VF4" "133:VF5" "134:VF6" "135:VF7"}
   set_parameter_property FUNC_NUM GROUP $group_name
   set_parameter_property FUNC_NUM VISIBLE true
   set_parameter_property FUNC_NUM HDL_PARAMETER true
   set_parameter_property FUNC_NUM DESCRIPTION "Function number assigned to this controller. Valid values are PF0, VF0-VF7"

     # Interface Width
   add_parameter          DMA_WIDTH integer 256
   set_parameter_property DMA_WIDTH DISPLAY_NAME "Application interface width"
   set_parameter_property DMA_WIDTH ALLOWED_RANGES {"128:128-bit" "256:256-bit"}
   set_parameter_property DMA_WIDTH GROUP $group_name
   set_parameter_property DMA_WIDTH VISIBLE true
   set_parameter_property DMA_WIDTH HDL_PARAMETER true
   set_parameter_property DMA_WIDTH DESCRIPTION "Selects the application interface width"


   # READ_CONTROL
   add_parameter          READ_CONTROL integer 1
   set_parameter_property READ_CONTROL DISPLAY_NAME "DMA-READ Control"
   set_parameter_property READ_CONTROL DISPLAY_HINT boolean
   set_parameter_property READ_CONTROL GROUP $group_name
   set_parameter_property READ_CONTROL VISIBLE true
   set_parameter_property READ_CONTROL HDL_PARAMETER true
   set_parameter_property READ_CONTROL DESCRIPTION "1:DMA-READ; 0:DMA-WRITE"

   # USER_STATUS
   add_parameter          USER_STATUS integer 1
   set_parameter_property USER_STATUS DISPLAY_NAME "Enable User Status"
   set_parameter_property USER_STATUS DISPLAY_HINT boolean
   set_parameter_property USER_STATUS GROUP $group_name
   set_parameter_property USER_STATUS VISIBLE true
   set_parameter_property USER_STATUS HDL_PARAMETER true
   set_parameter_property USER_STATUS DESCRIPTION "1:Enable User Status Interface; 0:Disable User Status Interface"


  add_parameter          CHANNELIZER_ENABLE integer 0
  set_parameter_property CHANNELIZER_ENABLE DISPLAY_NAME "Channelizer Interface"
  set_parameter_property CHANNELIZER_ENABLE DISPLAY_HINT boolean
  set_parameter_property CHANNELIZER_ENABLE GROUP $group_name
  set_parameter_property CHANNELIZER_ENABLE VISIBLE true
  set_parameter_property CHANNELIZER_ENABLE HDL_PARAMETER true
  set_parameter_property CHANNELIZER_ENABLE DESCRIPTION "Interface ports to Channelizer enable"
#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 250
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock Clk_i clk Input 1


#
# connection point Resetn
#
add_interface Resetn reset end
set_interface_property Resetn associatedClock clock
set_interface_property Resetn synchronousEdges DEASSERT
set_interface_property Resetn ENABLED true
set_interface_property Resetn EXPORT_OF ""
set_interface_property Resetn PORT_NAME_MAP ""
set_interface_property Resetn SVD_ADDRESS_GROUP ""

add_interface_port Resetn Rstn_i reset_n Input 1


#
# connection point desc_ctrl
#
add_interface desc_ctrl avalon end
set_interface_property desc_ctrl addressUnits SYMBOLS
set_interface_property desc_ctrl associatedClock clock
set_interface_property desc_ctrl associatedReset Resetn
set_interface_property desc_ctrl bitsPerSymbol 8
set_interface_property desc_ctrl burstOnBurstBoundariesOnly false
set_interface_property desc_ctrl burstcountUnits WORDS
set_interface_property desc_ctrl explicitAddressSpan 0
set_interface_property desc_ctrl holdTime 0
set_interface_property desc_ctrl linewrapBursts false
set_interface_property desc_ctrl maximumPendingReadTransactions 0
set_interface_property desc_ctrl readLatency 0
set_interface_property desc_ctrl readWaitTime 1
set_interface_property desc_ctrl setupTime 0
set_interface_property desc_ctrl timingUnits Cycles
set_interface_property desc_ctrl writeWaitTime 0
set_interface_property desc_ctrl ENABLED true
set_interface_property desc_ctrl EXPORT_OF ""
set_interface_property desc_ctrl PORT_NAME_MAP ""
set_interface_property desc_ctrl SVD_ADDRESS_GROUP ""

add_interface_port desc_ctrl DCSChipSelect_i chipselect Input 1
add_interface_port desc_ctrl DCSWrite_i write Input 1
add_interface_port desc_ctrl DCSAddress_i address Input 5
add_interface_port desc_ctrl DCSWriteData_i writedata Input 32
add_interface_port desc_ctrl DCSByteEnable_i byteenable Input 4
add_interface_port desc_ctrl DCSWaitRequest_o waitrequest Output 1
set_interface_assignment desc_ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment desc_ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment desc_ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment desc_ctrl embeddedsw.configuration.isPrintableDevice 0


#
# connection point desc_entries
#
add_interface desc_entries avalon end
set_interface_property desc_entries addressUnits WORDS
set_interface_property desc_entries associatedClock clock
set_interface_property desc_entries associatedReset Resetn
set_interface_property desc_entries bitsPerSymbol 8
set_interface_property desc_entries burstOnBurstBoundariesOnly false
set_interface_property desc_entries burstcountUnits WORDS
set_interface_property desc_entries explicitAddressSpan 0
set_interface_property desc_entries holdTime 0
set_interface_property desc_entries linewrapBursts false
set_interface_property desc_entries maximumPendingReadTransactions 0
set_interface_property desc_entries readLatency 0
set_interface_property desc_entries readWaitTime 1
set_interface_property desc_entries setupTime 0
set_interface_property desc_entries timingUnits Cycles
set_interface_property desc_entries writeWaitTime 0
set_interface_property desc_entries ENABLED true
set_interface_property desc_entries EXPORT_OF ""
set_interface_property desc_entries PORT_NAME_MAP ""
set_interface_property desc_entries SVD_ADDRESS_GROUP ""

add_interface_port desc_entries DTSChipSelect_i chipselect Input 1
add_interface_port desc_entries DTSWrite_i write Input 1
add_interface_port desc_entries DTSBurstCount_i burstcount Input 5
add_interface_port desc_entries DTSAddress_i address Input 8
add_interface_port desc_entries DTSWriteData_i writedata Input 256
add_interface_port desc_entries DTSWaitRequest_o waitrequest Output 1
set_interface_assignment desc_entries embeddedsw.configuration.isFlash 0
set_interface_assignment desc_entries embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment desc_entries embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment desc_entries embeddedsw.configuration.isPrintableDevice 0


#
# connection point desc_inst
#



#
# connection point dma_status
# DMA status to update Descriptor Table
#
add_interface dma_status avalon_streaming end
set_interface_property dma_status associatedClock clock
set_interface_property dma_status associatedReset Resetn
set_interface_property dma_status dataBitsPerSymbol 32
set_interface_property dma_status errorDescriptor ""
set_interface_property dma_status firstSymbolInHighOrderBits true
set_interface_property dma_status maxChannel 0
set_interface_property dma_status readyLatency 0
set_interface_property dma_status ENABLED true
set_interface_property dma_status EXPORT_OF ""
set_interface_property dma_status PORT_NAME_MAP ""
set_interface_property dma_status SVD_ADDRESS_GROUP ""

add_interface_port dma_status DmaRxData_i data Input 32
add_interface_port dma_status DmaRxValid_i valid Input 1

#
# connection point status2txs
# Update DMA Status to Descriptor Table
#
add_interface status2txs avalon start
set_interface_property status2txs addressUnits SYMBOLS
set_interface_property status2txs associatedClock clock
set_interface_property status2txs associatedReset Resetn
set_interface_property status2txs bitsPerSymbol 8
set_interface_property status2txs burstOnBurstBoundariesOnly false
set_interface_property status2txs burstcountUnits WORDS
set_interface_property status2txs doStreamReads false
set_interface_property status2txs doStreamWrites false
set_interface_property status2txs holdTime 0
set_interface_property status2txs linewrapBursts false
set_interface_property status2txs maximumPendingReadTransactions 0
set_interface_property status2txs readLatency 0
set_interface_property status2txs readWaitTime 1
set_interface_property status2txs setupTime 0
set_interface_property status2txs timingUnits Cycles
set_interface_property status2txs writeWaitTime 0
set_interface_property status2txs ENABLED true
set_interface_property status2txs EXPORT_OF ""
set_interface_property status2txs PORT_NAME_MAP ""
set_interface_property status2txs SVD_ADDRESS_GROUP ""

add_interface_port status2txs DCMAddress_o address Output 64
add_interface_port status2txs DCMWrite_o write Output 1
add_interface_port status2txs DCMWriteData_o writedata Output 32
add_interface_port status2txs DCMRead_o read Output 1
add_interface_port status2txs DCMByteEnable_o byteenable Output 4
add_interface_port status2txs DCMWaitRequest_i waitrequest Input 1
add_interface_port status2txs DCMReadData_i readdata Input 32
add_interface_port status2txs DCMReadDataValid_i readdatavalid Input 1

proc add_user_status {} {
  set en_user_status [ get_parameter_value USER_STATUS]
  #
  # connection point status2user
  # DMA status to User Logic
  #
    add_interface status2user avalon_streaming Start
    set_interface_property status2user associatedClock clock
    set_interface_property status2user associatedReset Resetn
    set_interface_property status2user dataBitsPerSymbol 96
    set_interface_property status2user errorDescriptor ""
    set_interface_property status2user firstSymbolInHighOrderBits true
    set_interface_property status2user maxChannel 0
    set_interface_property status2user readyLatency 0

    if { $en_user_status == 1 } {
      set_interface_property status2user ENABLED true
    } else {
      set_interface_property status2user ENABLED false
    }

    set_interface_property status2user EXPORT_OF ""
    set_interface_property status2user PORT_NAME_MAP ""
    set_interface_property status2user SVD_ADDRESS_GROUP ""

    add_interface_port status2user DCTxUserReady_i ready Input 1
    add_interface_port status2user DCTxUserData_o  data Output 96
    add_interface_port status2user DCTxUserValid_o valid Output 1
}




proc add_desc_inst {} {


  set dma_rd_port [ get_parameter_value READ_CONTROL]
  set channelizer_en [ get_parameter_value CHANNELIZER_ENABLE ]
   if { $channelizer_en == 1 } {
     set descriptor_width 169
    } else {
     set descriptor_width 168
   }


 add_interface desc_inst avalon_streaming start
set_interface_property desc_inst associatedClock clock
set_interface_property desc_inst associatedReset Resetn
set_interface_property desc_inst dataBitsPerSymbol $descriptor_width
set_interface_property desc_inst errorDescriptor ""
set_interface_property desc_inst firstSymbolInHighOrderBits true
set_interface_property desc_inst maxChannel 0
set_interface_property desc_inst readyLatency 0
set_interface_property desc_inst ENABLED true
set_interface_property desc_inst EXPORT_OF ""
set_interface_property desc_inst PORT_NAME_MAP ""
set_interface_property desc_inst SVD_ADDRESS_GROUP ""

add_interface_port desc_inst DmaTxData_o data Output $descriptor_width
add_interface_port desc_inst DmaTxValid_o valid Output 1
add_interface_port desc_inst DmaTxReady_i ready Input 1

}



#
# connection point WrFetchDT
# DMA status to User Logic
#
proc add_dmawr_fetch_dt {} {


  set dma_rd_port [ get_parameter_value READ_CONTROL]
  set channelizer_en [ get_parameter_value CHANNELIZER_ENABLE ]
   if { $channelizer_en == 1 } {
     set descriptor_width 169
    } else {
     set descriptor_width 168
   }


  add_interface WrFetchDT avalon_streaming Start
  set_interface_property WrFetchDT associatedClock clock
  set_interface_property WrFetchDT associatedReset Resetn
  set_interface_property WrFetchDT dataBitsPerSymbol $descriptor_width
  set_interface_property WrFetchDT errorDescriptor ""
  set_interface_property WrFetchDT firstSymbolInHighOrderBits true
  set_interface_property WrFetchDT maxChannel 0
  set_interface_property WrFetchDT readyLatency 0
  set_interface_property WrFetchDT ENABLED true
  set_interface_property WrFetchDT EXPORT_OF ""
  set_interface_property WrFetchDT PORT_NAME_MAP ""
  set_interface_property WrFetchDT SVD_ADDRESS_GROUP ""

  add_interface_port WrFetchDT WrDescTxData_o  data Output  $descriptor_width
  add_interface_port WrFetchDT WrDescTxReq_o   valid Output 1

 #=============================================================
 # If DMA_Read, tie off the ACK control signal
  if { $dma_rd_port == 0 } {
    add_interface_port WrFetchDT WrDescTxAck_i   ready Input 1
  } else {
    add_to_no_connect  WrDescTxAck_i  1 Input
  }
}

#
# connection point RdAckWrFetchDT
# DMA status to User Logic
#
proc add_dmard_ack_dmawrfetch {} {

  set dma_rd_port [ get_parameter_value READ_CONTROL]
    set channelizer_en [ get_parameter_value CHANNELIZER_ENABLE ]
   if { $channelizer_en == 1 } {
     set descriptor_width 169
    } else {
     set descriptor_width 168
   }

  add_interface RdAckWrFetchDT avalon_streaming End
  set_interface_property RdAckWrFetchDT associatedClock clock
  set_interface_property RdAckWrFetchDT associatedReset Resetn
  set_interface_property RdAckWrFetchDT dataBitsPerSymbol $descriptor_width
  set_interface_property RdAckWrFetchDT errorDescriptor ""
  set_interface_property RdAckWrFetchDT firstSymbolInHighOrderBits true
  set_interface_property RdAckWrFetchDT maxChannel 0
  set_interface_property RdAckWrFetchDT readyLatency 0
  set_interface_property RdAckWrFetchDT ENABLED true
  set_interface_property RdAckWrFetchDT EXPORT_OF ""
  set_interface_property RdAckWrFetchDT PORT_NAME_MAP ""
  set_interface_property RdAckWrFetchDT SVD_ADDRESS_GROUP ""

 #==========================================
 # If DMA_Write, tie off the Write requests
  if { $dma_rd_port == 1 } {
    add_interface_port RdAckWrFetchDT WrDescTxData_i  data Input $descriptor_width
    add_interface_port RdAckWrFetchDT WrDescTxReq_i   valid Input 1
  } else {
    add_to_no_connect WrDescTxData_i  169 Input
    add_to_no_connect WrDescTxReq_i   1   Input
  }
    add_interface_port RdAckWrFetchDT WrDescTxAck_o   ready Output 1

}

#========================================================================
# Set condition to expose the right ports for DMA-WR descriptor fetching
proc elaboration_callback { } {
  add_dmawr_fetch_dt
  add_dmard_ack_dmawrfetch
  add_desc_inst
  add_user_status

  set dma_rd_port [ get_parameter_value READ_CONTROL]
      if { $dma_rd_port== 1} {
          set_interface_property WrFetchDT ENABLED false
      } else {
          set_interface_property RdAckWrFetchDT ENABLED false
      }
}

####################################################################################################
#
# add_to_no_connect signal_name:string signal_width:int direction:string
#  tied internal signal to
#     - open (when output of the instance)
#     - GND (input of the instance)
#

proc add_to_no_connect { signal_name signal_width direction } {
#send_message debug "proc add_to_no_connect $signal_name $signal_width $direction"
   add_interface no_connect conduit end
   if { [ regexp In $direction ] } {
      add_interface_port no_connect $signal_name $signal_name Input $signal_width
      set_port_property $signal_name TERMINATION true
      set_port_property $signal_name TERMINATION_VALUE 0
   } else {
      add_interface_port no_connect $signal_name $signal_name Output $signal_width
      set_port_property  $signal_name TERMINATION true
   }
}


