# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


package provide altera_emif::ip_arch_nd::enum_defs_hmc_cfgs 0.1

package require altera_emif::util::enums

namespace eval ::altera_emif::ip_arch_nd::enum_defs_hmc_cfgs:: {
   namespace import ::altera_emif::util::enums::*


}


proc ::altera_emif::ip_arch_nd::enum_defs_hmc_cfgs::def_enums {} {

   def_enum_type HMC_CFG                                      {     WYSIWYG_NAME                           DATA_TYPE          WIDTH      DEFAULT                             COMMENT}
   def_enum      HMC_CFG    HMC_CFG_PING_PONG_MODE            [list "hmc_pinpong_mode"                     "string"           0          "pingpong_off"                      "Ping-Pong PHY mode"]
   def_enum      HMC_CFG    HMC_CFG_CS_ADDR_WIDTH             [list "hmc_cs_addr_width"                    "string"           0          "cs_width_2"                        "Address width in bits required to access every CS in interface"]
   def_enum      HMC_CFG    HMC_CFG_COL_ADDR_WIDTH            [list "hmc_col_addr_width"                   "string"           0          "col_width_12"                      "Column address width"]
   def_enum      HMC_CFG    HMC_CFG_ROW_ADDR_WIDTH            [list "hmc_row_addr_width"                   "string"           0          "row_width_16"                      "Row address width"]
   def_enum      HMC_CFG    HMC_CFG_BANK_ADDR_WIDTH           [list "hmc_bank_addr_width"                  "string"           0          "bank_width_3"                      "Bank address width"]
   def_enum      HMC_CFG    HMC_CFG_BANK_GROUP_ADDR_WIDTH     [list "hmc_bank_group_addr_width"            "string"           0          "bank_group_width_0"                "Bank group address width"]
   def_enum      HMC_CFG    HMC_CFG_ADDR_ORDER                [list "hmc_addr_order"                       "string"           0          "addr_order_cs_ba_row_col"          "Mapping of Avalon address to physical address of the memory device"]
   def_enum      HMC_CFG    HMC_CFG_ARBITER_TYPE              [list "hmc_arbiter_type"                     "string"           0          "arbiter_type_2t"                   "Arbiter Type"]
   def_enum      HMC_CFG    HMC_CFG_OPEN_PAGE_EN              [list "hmc_open_page_en"                     "string"           0          "disable"                           "Unused"]
   def_enum      HMC_CFG    HMC_CFG_CTRL_ENABLE_RC            [list "hmc_ctrl_rc_en"                       "string"           0          "disable"                           "Enable rate-conversion feature"]
   def_enum      HMC_CFG    HMC_CFG_DBC0_ENABLE_RC            [list "hmc_dbc0_rc_en"                       "string"           0          "disable"                           "Enable rate-conversion feature"]
   def_enum      HMC_CFG    HMC_CFG_DBC1_ENABLE_RC            [list "hmc_dbc1_rc_en"                       "string"           0          "disable"                           "Enable rate-conversion feature"]
   def_enum      HMC_CFG    HMC_CFG_DBC2_ENABLE_RC            [list "hmc_dbc2_rc_en"                       "string"           0          "disable"                           "Enable rate-conversion feature"]
   def_enum      HMC_CFG    HMC_CFG_DBC3_ENABLE_RC            [list "hmc_dbc3_rc_en"                       "string"           0          "disable"                           "Enable rate-conversion feature"]
   def_enum      HMC_CFG    HMC_CFG_CTRL_ENABLE_ECC           [list "hmc_ctrl_enable_ecc"                  "string"           0          "disable"                           "Enable ECC"]
   def_enum      HMC_CFG    HMC_CFG_DBC0_ENABLE_ECC           [list "hmc_dbc0_enable_ecc"                  "string"           0          "disable"                           "Enable ECC"]
   def_enum      HMC_CFG    HMC_CFG_DBC1_ENABLE_ECC           [list "hmc_dbc1_enable_ecc"                  "string"           0          "disable"                           "Enable ECC"]
   def_enum      HMC_CFG    HMC_CFG_DBC2_ENABLE_ECC           [list "hmc_dbc2_enable_ecc"                  "string"           0          "disable"                           "Enable ECC"]
   def_enum      HMC_CFG    HMC_CFG_DBC3_ENABLE_ECC           [list "hmc_dbc3_enable_ecc"                  "string"           0          "disable"                           "Enable ECC"]
   def_enum      HMC_CFG    HMC_CFG_REORDER_DATA              [list "hmc_reorder_data"                     "string"           0          "enable"                            "Enable command reodering"]
   def_enum      HMC_CFG    HMC_CFG_REORDER_READ              [list "hmc_reorder_read"                     "string"           0          "enable"                            "Enable read command reordering if command reordering is enabled"]
   def_enum      HMC_CFG    HMC_CFG_CTRL_REORDER_RDATA        [list "hmc_ctrl_reorder_rdata"               "string"           0          "enable"                            "Enable in-order read data return when read command reordering is enabled"]
   def_enum      HMC_CFG    HMC_CFG_DBC0_REORDER_RDATA        [list "hmc_dbc0_reorder_rdata"               "string"           0          "enable"                            "Enable in-order read data return when read command reordering is enabled"]
   def_enum      HMC_CFG    HMC_CFG_DBC1_REORDER_RDATA        [list "hmc_dbc1_reorder_rdata"               "string"           0          "enable"                            "Enable in-order read data return when read command reordering is enabled"]
   def_enum      HMC_CFG    HMC_CFG_DBC2_REORDER_RDATA        [list "hmc_dbc2_reorder_rdata"               "string"           0          "enable"                            "Enable in-order read data return when read command reordering is enabled"]
   def_enum      HMC_CFG    HMC_CFG_DBC3_REORDER_RDATA        [list "hmc_dbc3_reorder_rdata"               "string"           0          "enable"                            "Enable in-order read data return when read command reordering is enabled"]
   def_enum      HMC_CFG    HMC_CFG_CTRL_SLOT_OFFSET          [list "hmc_ctrl_slot_offset"                 "integer"          2          0                                   "Command slot offset"]
   def_enum      HMC_CFG    HMC_CFG_DBC0_SLOT_OFFSET          [list "hmc_dbc0_slot_offset"                 "integer"          2          0                                   "Command slot offset"]
   def_enum      HMC_CFG    HMC_CFG_DBC1_SLOT_OFFSET          [list "hmc_dbc1_slot_offset"                 "integer"          2          0                                   "Command slot offset"]
   def_enum      HMC_CFG    HMC_CFG_DBC2_SLOT_OFFSET          [list "hmc_dbc2_slot_offset"                 "integer"          2          0                                   "Command slot offset"]
   def_enum      HMC_CFG    HMC_CFG_DBC3_SLOT_OFFSET          [list "hmc_dbc3_slot_offset"                 "integer"          2          0                                   "Command slot offset"]
   def_enum      HMC_CFG    HMC_CFG_CTRL_SLOT_ROTATE_EN       [list "hmc_ctrl_slot_rotate_en"              "string"           0          "ctrl_disable"                      "Command slot rotation"]
   def_enum      HMC_CFG    HMC_CFG_DBC0_SLOT_ROTATE_EN       [list "hmc_dbc0_slot_rotate_en"              "string"           0          "dbc0_disable"                      "Command slot rotation"]
   def_enum      HMC_CFG    HMC_CFG_DBC1_SLOT_ROTATE_EN       [list "hmc_dbc1_slot_rotate_en"              "string"           0          "dbc1_disable"                      "Command slot rotation"]
   def_enum      HMC_CFG    HMC_CFG_DBC2_SLOT_ROTATE_EN       [list "hmc_dbc2_slot_rotate_en"              "string"           0          "dbc2_disable"                      "Command slot rotation"]
   def_enum      HMC_CFG    HMC_CFG_DBC3_SLOT_ROTATE_EN       [list "hmc_dbc3_slot_rotate_en"              "string"           0          "dbc3_disable"                      "Command slot rotation"]
   def_enum      HMC_CFG    HMC_CFG_COL_CMD_SLOT              [list "hmc_col_cmd_slot"                     "integer"          4          2                                   "Command slot for column commands"]
   def_enum      HMC_CFG    HMC_CFG_ROW_CMD_SLOT              [list "hmc_row_cmd_slot"                     "integer"          4          1                                   "Command slot for row commands"]
   def_enum      HMC_CFG    HMC_CFG_ROW_TO_COL_OFFSET         [list "hmc_row_to_col_offset"                "integer"          32         0                                   "Command slot offset from row to col command"]
   def_enum      HMC_CFG    HMC_CFG_ROW_TO_ROW_OFFSET         [list "hmc_row_to_row_offset"                "integer"          32         0                                   "Command slot offset from row to row command"]
   def_enum      HMC_CFG    HMC_CFG_COL_TO_COL_OFFSET         [list "hmc_col_to_col_offset"                "integer"          32         0                                   "Command slot offset from col to col command"]
   def_enum      HMC_CFG    HMC_CFG_COL_TO_DIFF_COL_OFFSET    [list "hmc_col_to_diff_col_offset"           "integer"          32         0                                   "Command slot offset from col to col command (different columns)"]
   def_enum      HMC_CFG    HMC_CFG_COL_TO_ROW_OFFSET         [list "hmc_col_to_row_offset"                "integer"          32         0                                   "Command slot offset from col to row command"]
   def_enum      HMC_CFG    HMC_CFG_SIDEBAND_OFFSET           [list "hmc_sideband_offset"                  "integer"          32         0                                   "Command slot offset for sideband commands"]
   def_enum      HMC_CFG    HMC_CFG_CS_TO_CHIP_MAPPING        [list "hmc_cs_chip"                          "integer"          16         33825                               "Chip select mapping scheme"]
   def_enum      HMC_CFG    HMC_CFG_CTL_ODT_ENABLED           [list "hmc_ctl_odt_enabled"                  "integer"          32         1                                   "ODT enabled"]
   def_enum      HMC_CFG    HMC_CFG_RD_ODT_ON                 [list "hmc_rd_odt_on"                        "integer"          6          2                                   "Indicates number of memory clock cycle gap between read command and ODT signal rising edge"]
   def_enum      HMC_CFG    HMC_CFG_RD_ODT_PERIOD             [list "hmc_rd_odt_period"                    "integer"          6          6                                   "Indicates number of memory clock cycle read ODT signal should stay asserted after rising edge"]
   def_enum      HMC_CFG    HMC_CFG_READ_ODT_CHIP             [list "hmc_read_odt_chip"                    "integer"          16         795                                 "ODT scheme setting for read command"]
   def_enum      HMC_CFG    HMC_CFG_WR_ODT_ON                 [list "hmc_wr_odt_on"                        "integer"          6          0                                   "Indicates number of memory clock cycle gap between write command and ODT signal rising edge"]
   def_enum      HMC_CFG    HMC_CFG_WR_ODT_PERIOD             [list "hmc_wr_odt_period"                    "integer"          6          6                                   "Indicates number of memory clock cycle write ODT signal should stay asserted after rising edge"]
   def_enum      HMC_CFG    HMC_CFG_WRITE_ODT_CHIP            [list "hmc_write_odt_chip"                   "integer"          16         47822                               "ODT scheme setting for write command"]
   def_enum      HMC_CFG    HMC_CFG_CMD_FIFO_RESERVE_EN       [list "hmc_cmd_fifo_reserve_en"              "string"           0          "enable"                            "Command FIFO reserve enable"]
   def_enum      HMC_CFG    HMC_CFG_RB_RESERVED_ENTRY         [list "hmc_rb_reserved_entry"                "integer"          7          8                                   "Number of entries reserved in read buffer before almost full is asserted. Should be set to 4 + 2 * user_pipe_stages"]
   def_enum      HMC_CFG    HMC_CFG_WB_RESERVED_ENTRY         [list "hmc_wb_reserved_entry"                "integer"          7          8                                   "Number of entries reserved in write buffer before almost full is asserted. Should be set to 4 + 2 * user_pipe_stages"]
   def_enum      HMC_CFG    HMC_CFG_STARVE_LIMIT              [list "hmc_starve_limit"                     "integer"          6          63                                  "When command reordering is enabled, specifies the number of commands that can be served before a starved command is starved."]
   def_enum      HMC_CFG    HMC_CFG_PHY_DELAY_MISMATCH        [list "hmc_phy_delay_mismatch"               "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_DQSTRK_EN                 [list "hmc_dqstrk_en"                        "string"           0          "disable"                           "Enable DQS tracking"]
   def_enum      HMC_CFG    HMC_CFG_DQSTRK_TO_VALID           [list "hmc_dqstrk_to_valid"                  "integer"          8          0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_DQSTRK_TO_VALID_LAST      [list "hmc_dqstrk_to_valid_last"             "integer"          8          0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_CTL_SHORT_DQSTRK_EN       [list "hmc_ctl_short_dqstrk_en"              "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_PERIOD_DQSTRK_CTRL_EN     [list "hmc_period_dqstrk_ctrl_en"            "string"           0          "disable"                           ""]
   def_enum      HMC_CFG    HMC_CFG_PERIOD_DQSTRK_INTERVAL    [list "hmc_period_dqstrk_interval"           "integer"          16         0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_SHORT_DQSTRK_CTRL_EN      [list "hmc_short_dqstrk_ctrl_en"             "string"           0          "disable"                           ""]
   def_enum      HMC_CFG    HMC_CFG_ENABLE_FAST_EXIT_PPD      [list "hmc_enable_fast_exit_ppd"             "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_USER_RFSH_EN              [list "hmc_user_rfsh_en"                     "string"           0          "disable"                           "Setting to enable user refresh"]
   def_enum      HMC_CFG    HMC_CFG_GEAR_DOWN_EN              [list "hmc_geardn_en"                        "string"           0          "disable"                           "Gear-down (DDR4)"]
   def_enum      HMC_CFG    HMC_CFG_MEM_AUTO_PD_CYCLES        [list "hmc_mem_auto_pd_cycles"               "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_MEM_CLK_DISABLE_ENTRY_CYC [list "hmc_mem_clk_disable_entry_cycles"     "integer"          6          4                                   "Set to a the number of clocks after the execution of an self-refresh to stop the clock.  This register is generally set based on PHY design latency and should generally not be changed"]
   def_enum      HMC_CFG    HMC_MEMCLKGATE_SETTING            [list "hmc_memclkgate_setting"               "integer"          8          0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_TCL                       [list "hmc_tcl"                              "integer"          7          8                                   "Memory CAS latency"]
   def_enum      HMC_CFG    HMC_CFG_16_ACT_TO_ACT             [list "hmc_16_act_to_act"                    "integer"          8          0                                   "The 16-activate window timing parameter (RLD3) (e.g. tSAW)"]
   def_enum      HMC_CFG    HMC_CFG_4_ACT_TO_ACT              [list "hmc_4_act_to_act"                     "integer"          8          12                                  "The four-activate window timing parameter. (e.g. tFAW)"]
   def_enum      HMC_CFG    HMC_MEM_IF_AL                     [list "hmc_mem_if_al"                        "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_CS_PER_DIMM            [list "hmc_mem_if_cs_per_dimm"               "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_RD_PREAMBLE            [list "hmc_mem_if_rd_preamble"               "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TCCD                   [list "hmc_mem_if_tccd"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TCCD_S                 [list "hmc_mem_if_tccd_s"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TCKESR                 [list "hmc_mem_if_tckesr"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TCKSRX                 [list "hmc_mem_if_tcksrx"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TCL                    [list "hmc_mem_if_tcl"                       "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TCWL                   [list "hmc_mem_if_tcwl"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TDQSCKMAX              [list "hmc_mem_if_tdqsckmax"                 "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TFAW                   [list "hmc_mem_if_tfaw"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TMOD                   [list "hmc_mem_if_tmod"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TPL                    [list "hmc_mem_if_tpl"                       "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRAS                   [list "hmc_mem_if_tras"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRC                    [list "hmc_mem_if_trc"                       "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRCD                   [list "hmc_mem_if_trcd"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TREFI                  [list "hmc_mem_if_trefi"                     "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRFC                   [list "hmc_mem_if_trfc"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRP                    [list "hmc_mem_if_trp"                       "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRRD                   [list "hmc_mem_if_trrd"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRRD_S                 [list "hmc_mem_if_trrd_s"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TRTP                   [list "hmc_mem_if_trtp"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TWR                    [list "hmc_mem_if_twr"                       "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TWR_CRC_DM             [list "hmc_mem_if_twr_crc_dm"                "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TWTR                   [list "hmc_mem_if_twtr"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TWTR_L_CRC_DM          [list "hmc_mem_if_twtr_l_crc_dm"             "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TWTR_S                 [list "hmc_mem_if_twtr_s"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TWTR_S_CRC_DM          [list "hmc_mem_if_twtr_s_crc_dm"             "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TXP                    [list "hmc_mem_if_txp"                       "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TXPDLL                 [list "hmc_mem_if_txpdll"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TXSR                   [list "hmc_mem_if_txsr"                      "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TZQCS                  [list "hmc_mem_if_tzqcs"                     "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_TZQOPER                [list "hmc_mem_if_tzqoper"                   "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_WR_CRC                 [list "hmc_mem_if_wr_crc"                    "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_MEM_IF_WR_PREAMBLE            [list "hmc_mem_if_wr_preamble"               "integer"          32         0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_ACT_TO_ACT                [list "hmc_act_to_act"                       "integer"          6          18                                  "Active to activate timing on same bank (e.g. tRC)"]
   def_enum      HMC_CFG    HMC_CFG_ACT_TO_ACT_DIFF_BANK      [list "hmc_act_to_act_diff_bank"             "integer"          6          3                                   "Active to activate timing on different banks, for DDR4 same bank group (e.g. tRRD)"]
   def_enum      HMC_CFG    HMC_CFG_ACT_TO_ACT_DIFF_BG        [list "hmc_act_to_act_diff_bg"               "integer"          6          0                                   "Active to activate timing on different bank groups, DDR4 only"]
   def_enum      HMC_CFG    HMC_CFG_ACT_TO_PCH                [list "hmc_act_to_pch"                       "integer"          6          14                                  "Active to precharge (e.g. tRAS)"]
   def_enum      HMC_CFG    HMC_CFG_ACT_TO_RDWR               [list "hmc_act_to_rdwr"                      "integer"          6          3                                   "Activate to Read/write command timing (e.g. tRCD)"]
   def_enum      HMC_CFG    HMC_CFG_ARF_PERIOD                [list "hmc_arf_period"                       "integer"          13         3120                                "Auto-refresh period (e.g. tREFI)"]
   def_enum      HMC_CFG    HMC_CFG_ARF_TO_VALID              [list "hmc_arf_to_valid"                     "integer"          8          36                                  "Auto Refresh to valid DRAM command window."]
   def_enum      HMC_CFG    HMC_CFG_MMR_CMD_TO_VALID          [list "hmc_mmr_cmd_to_valid"                 "integer"          8          4                                   "MMR cmd to valid delay"]
   def_enum      HMC_CFG    HMC_CFG_MPR_TO_VALID              [list "hmc_mpr_to_valid"                     "integer"          5          0                                   "Multi Purpose Register Read to Valid"]
   def_enum      HMC_CFG    HMC_CFG_MPS_DQSTRK_DISABLE        [list "hmc_mps_dqstrk_disable"               "string"           0          "disable"                           "Setting to disable DQS Tracking after Maximum Power Saving exit"]
   def_enum      HMC_CFG    HMC_CFG_MPS_EXIT_CKE_TO_CS        [list "hmc_mps_exit_cke_to_cs"               "integer"          4          0                                   "Max Power Saving CKE to CS"]
   def_enum      HMC_CFG    HMC_CFG_MPS_EXIT_CS_TO_CKE        [list "hmc_mps_exit_cs_to_cke"               "integer"          4          0                                   "Max Power Saving CS to CKE"]
   def_enum      HMC_CFG    HMC_CFG_MPS_TO_VALID              [list "hmc_mps_to_valid"                     "integer"          10         0                                   "Max Power Saving to Valid"]
   def_enum      HMC_CFG    HMC_CFG_MPS_ZQCAL_DISABLE         [list "hmc_mps_zqcal_disable"                "string"           0          "disable"                           "Setting to disable ZQ Calibration after Maximum Power Saving exit"]
   def_enum      HMC_CFG    HMC_CFG_MRR_TO_VALID              [list "hmc_mrr_to_valid"                     "integer"          4          0                                   "Mode Register Read to Valid"]
   def_enum      HMC_CFG    HMC_CFG_MRS_TO_VALID              [list "hmc_mrs_to_valid"                     "integer"          4          2                                   "Mode Register Setting to valid (e.g. tMRD)"]
   def_enum      HMC_CFG    HMC_CFG_PCH_ALL_TO_VALID          [list "hmc_pch_all_to_valid"                 "integer"          6          4                                   "Precharge all to banks being ready for bank activation command."]
   def_enum      HMC_CFG    HMC_CFG_PCH_TO_VALID              [list "hmc_pch_to_valid"                     "integer"          6          4                                   "Precharge to valid command timing. (e.g. tRP)"]
   def_enum      HMC_CFG    HMC_CFG_PDN_PERIOD                [list "hmc_pdn_period"                       "integer"          16         0                                   "Number of controller cycles before automatic power down."]
   def_enum      HMC_CFG    HMC_CFG_PDN_TO_VALID              [list "hmc_pdn_to_valid"                     "integer"          6          3                                   "Power down to valid bank command window."]
   def_enum      HMC_CFG    HMC_CFG_POWER_SAVING_EXIT_CYC     [list "hmc_power_saving_exit_cycles"         "integer"          6          10                                  "The minimum number of cycles to stay in a low power state. This applies to both power down and self-refresh and should be set to the greater of tPD and tCKESR"]
   def_enum      HMC_CFG    HMC_CFG_RD_AP_TO_VALID            [list "hmc_rd_ap_to_valid"                   "integer"          6          8                                   "Read command with autoprecharge to data valid timing"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_PCH                 [list "hmc_rd_to_pch"                        "integer"          6          4                                   "Read to precharge command timing (e.g. tRTP)"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_RD                  [list "hmc_rd_to_rd"                         "integer"          6          2                                   "Read to read command timing on same bank (e.g. tCCD)"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_RD_DIFF_BG          [list "hmc_rd_to_rd_diff_bg"                 "integer"          6          0                                   "Read to read command timing on different chips"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_RD_DIFF_CHIP        [list "hmc_rd_to_rd_diff_chip"               "integer"          6          3                                   "Read to read command timing on different chips"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_WR                  [list "hmc_rd_to_wr"                         "integer"          6          3                                   "Read to write command timing on same bank"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_WR_DIFF_BG          [list "hmc_rd_to_wr_diff_bg"                 "integer"          6          0                                   "Read to write command timing on different bank groups"]
   def_enum      HMC_CFG    HMC_CFG_RD_TO_WR_DIFF_CHIP        [list "hmc_rd_to_wr_diff_chip"               "integer"          6          3                                   "Read to write command timing on different chips"]
   def_enum      HMC_CFG    HMC_CFG_RFSH_WARN_THRESHOLD       [list "hmc_rfsh_warn_threshold"              "integer"          7          0                                   ""]
   def_enum      HMC_CFG    HMC_CFG_RLD3_MULTIBANK_REF_DELAY  [list "hmc_rld3_multibank_ref_delay"         "integer"          3          0                                   "RLD3 multi-bank ref delay"]
   def_enum      HMC_CFG    HMC_CFG_RLD3_REFRESH_SEQ0         [list "hmc_rld3_refresh_seq0"                "integer"          16         0                                   "Banks to refresh for RLD3 in sequence 0. Must not be more than 4 banks"]
   def_enum      HMC_CFG    HMC_CFG_RLD3_REFRESH_SEQ1         [list "hmc_rld3_refresh_seq1"                "integer"          16         0                                   "Banks to refresh for RLD3 in sequence 1. Must not be more than 4 banks"]
   def_enum      HMC_CFG    HMC_CFG_RLD3_REFRESH_SEQ2         [list "hmc_rld3_refresh_seq2"                "integer"          16         0                                   "Banks to refresh for RLD3 in sequence 2. Must not be more than 4 banks"]
   def_enum      HMC_CFG    HMC_CFG_RLD3_REFRESH_SEQ3         [list "hmc_rld3_refresh_seq3"                "integer"          16         0                                   "Banks to refresh for RLD3 in sequence 3. Must not be more than 4 banks"]
   def_enum      HMC_CFG    HMC_CFG_SB_CG_DISABLE             [list "hmc_sb_cg_disable"                    "string"           0          "disable"                           "Setting to disable mem_ck gating during self refresh and deep power down"]
   def_enum      HMC_CFG    HMC_CFG_SB_DDR4_MR3               [list "hmc_sb_ddr4_mr3"                      "integer"          20         0                                   "DDR4 MR3"]
   def_enum      HMC_CFG    HMC_CFG_SB_DDR4_MR4               [list "hmc_sb_ddr4_mr4"                      "integer"          20         0                                   "DDR4 MR4"]
   def_enum      HMC_CFG    HMC_CFG_SB_DDR4_MR5               [list "hmc_sb_ddr4_mr5"                      "integer"          20         0                                   "DDR4 MR5"]
   def_enum      HMC_CFG    HMC_CFG_DDR4_MPS_ADDRMIRROR       [list "hmc_ddr4_mps_addrmirror"              "string"           0          "disable"                           "DDR4 MPS Address Mirror"]
   def_enum      HMC_CFG    HMC_CFG_SRF_AUTOEXIT_EN           [list "hmc_srf_autoexit_en"                  "string"           0          "disable"                           "Setting to enable controller to exit Self Refresh when new command is detected"]
   def_enum      HMC_CFG    HMC_CFG_SRF_ENTRY_EXIT_BLOCK      [list "hmc_srf_entry_exit_block"             "integer"          2          0                                   "Blocking arbiter from issuing commands"]
   def_enum      HMC_CFG    HMC_CFG_SRF_TO_VALID              [list "hmc_srf_to_valid"                     "integer"          10         256                                 "Self-refresh to valid bank command window. (e.g. tRFC)"]
   def_enum      HMC_CFG    HMC_CFG_SRF_TO_ZQ_CAL             [list "hmc_srf_to_zq_cal"                    "integer"          10         128                                 "Self refresh to ZQ calibration window"]
   def_enum      HMC_CFG    HMC_CFG_SRF_ZQCAL_DISABLE         [list "hmc_srf_zqcal_disable"                "string"           0          "disable"                           "Setting to disable ZQ Calibration after self refresh"]
   def_enum      HMC_CFG    HMC_TEMP_4_ACT_TO_ACT             [list "hmc_temp_4_act_to_act"                "integer"          32         0                                   "Unused parameter"]
   def_enum      HMC_CFG    HMC_TEMP_RD_TO_RD_DIFF_BG         [list "hmc_temp_rd_to_rd_diff_bg"            "integer"          32         0                                   "Unused parameter"]
   def_enum      HMC_CFG    HMC_TEMP_WR_TO_RD                 [list "hmc_temp_wr_to_rd"                    "integer"          32         0                                   "Unused parameter"]
   def_enum      HMC_CFG    HMC_TEMP_WR_TO_RD_DIFF_BG         [list "hmc_temp_wr_to_rd_diff_bg"            "integer"          32         0                                   "Unused parameter"]
   def_enum      HMC_CFG    HMC_TEMP_WR_TO_RD_DIFF_CHIP       [list "hmc_temp_wr_to_rd_diff_chip"          "integer"          32         0                                   "Unused parameter"]
   def_enum      HMC_CFG    HMC_TEMP_WR_TO_WR_DIFF_BG         [list "hmc_temp_wr_to_wr_diff_bg"            "integer"          32         0                                   "Unused parameter"]
   def_enum      HMC_CFG    HMC_CFG_WR_AP_TO_VALID            [list "hmc_wr_ap_to_valid"                   "integer"          6          17                                  "Write with autoprecharge to valid command timing."]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_PCH                 [list "hmc_wr_to_pch"                        "integer"          6          13                                  "Write to precharge command timing. (e.g. tWR)"]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_RD                  [list "hmc_wr_to_rd"                         "integer"          6          9                                   "Write to read command timing. (e.g. tWTR)"]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_RD_DIFF_BG          [list "hmc_wr_to_rd_diff_bg"                 "integer"          6          0                                   "Write to read command timing on different bank groups"]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_RD_DIFF_CHIP        [list "hmc_wr_to_rd_diff_chip"               "integer"          6          7                                   "Write to read command timing on different chips."]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_WR                  [list "hmc_wr_to_wr"                         "integer"          6          2                                   "Write to write command timing on same bank. (e.g. tCCD)"]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_WR_DIFF_BG          [list "hmc_wr_to_wr_diff_bg"                 "integer"          6          0                                   "Write to write command timing on different bank groups."]
   def_enum      HMC_CFG    HMC_CFG_WR_TO_WR_DIFF_CHIP        [list "hmc_wr_to_wr_diff_chip"               "integer"          6          3                                   "Write to write command timing on different chips."]
   def_enum      HMC_CFG    HMC_CFG_ZQCL_TO_VALID             [list "hmc_zqcl_to_valid"                    "integer"          9          128                                 "Long ZQ calibration to valid"]
   def_enum      HMC_CFG    HMC_CFG_ZQCS_TO_VALID             [list "hmc_zqcs_to_valid"                    "integer"          7          32                                  "Short ZQ calibration to valid"]
   def_enum      HMC_CFG    HMC_CHIP_ID                       [list "hmc_chip_id"                          "integer"          9          273                                 "Configure 3DS pin mapping"]
   def_enum      HMC_CFG    HMC_CID_ADDR_WIDTH                [list "hmc_cid_addr_width"                   "integer"          2          0                                   "Width of chip ID"]
   def_enum      HMC_CFG    HMC_3DS_EN                        [list "hmc_3ds_en"                           "string"           0          "disable"                           ""]
   def_enum      HMC_CFG    HMC_3DS_LR_NUM0                   [list "hmc_3ds_lr_num0"                      "integer"          4          0                                   ""]
   def_enum      HMC_CFG    HMC_3DS_LR_NUM1                   [list "hmc_3ds_lr_num1"                      "integer"          4          0                                   ""]
   def_enum      HMC_CFG    HMC_3DS_LR_NUM2                   [list "hmc_3ds_lr_num2"                      "integer"          4          0                                   ""]
   def_enum      HMC_CFG    HMC_3DS_LR_NUM3                   [list "hmc_3ds_lr_num3"                      "integer"          4          0                                   ""]
   def_enum      HMC_CFG    HMC_3DS_PR_STAG_ENABLE            [list "hmc_3ds_pr_stag_enable"               "string"           0          "disable"                           ""]
   def_enum      HMC_CFG    HMC_3DS_REF2REF_DLR               [list "hmc_3ds_ref2ref_dlr"                  "integer"          7          0                                   ""]
   def_enum      HMC_CFG    HMC_3DSREF_ACK_ON_DONE            [list "hmc_3dsref_ack_on_done"               "string"           0          "disable"                           ""]   

   def_enum_type HMC_CFG_ADDR_ORDER                                    {            WYSIWYG_NAME }
   def_enum      HMC_CFG_ADDR_ORDER       HMC_CFG_ADDR_ORDER_CS_B_R_C  [list "addr_order_cs_ba_row_col" ]
   def_enum      HMC_CFG_ADDR_ORDER       HMC_CFG_ADDR_ORDER_CS_R_B_C  [list "addr_order_cs_row_ba_col" ]
   def_enum      HMC_CFG_ADDR_ORDER       HMC_CFG_ADDR_ORDER_R_CS_B_C  [list "addr_order_row_cs_ba_col" ]
}


proc ::altera_emif::ip_arch_nd::enum_defs_hmc_cfgs::_init {} {
   ::altera_emif::ip_arch_nd::enum_defs_hmc_cfgs::def_enums
}

::altera_emif::ip_arch_nd::enum_defs_hmc_cfgs::_init

