# Module name strings
HWTCL_MODULE_DISPLAY_NAME = EMIF Architecture Component for the Stratix 10 Device Family
HWTCL_MODULE_DESCRIPTION = Altera External Memory Interface Architecture Component for the Stratix 10 Device Family
