# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 13.1
# Tue Dec 10 17:47:52 SGT 2013
# DO NOT MODIFY


# 
# interrupt_latency_counter "Altera Interrupt Latency Counter" v14.0
# Altera Corporation 2013.12.10.17:47:52
# This component measures the time taken from the moment an IRQ signal is fired till the Interrupt Service Routine begins in clock cycle
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module interrupt_latency_counter
# 
set_module_property DESCRIPTION "This component measures the time taken from the moment an IRQ signal is fired till the Interrupt Service Routine begins in clock cycle"
set_module_property NAME interrupt_latency_counter
set_module_property VERSION 18.1
set_module_property INTERNAL false
set_module_property HIDE_FROM_QUARTUS true
set_module_property OPAQUE_ADDRESS_MAP true
#set_module_property GROUP "Peripherals/Multiprocessor Coordination"
set_module_property GROUP "Processors and Peripherals/Inter-Process Communication"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Interrupt Latency Counter Intel FPGA IP"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property     "ELABORATION_CALLBACK"      "elaborate"

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL interrupt_latency_counter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file interrupt_latency_counter.v VERILOG PATH interrupt_latency_counter.v TOP_LEVEL_FILE
add_fileset_file irq_detector.v VERILOG PATH irq_detector.v
add_fileset_file state_machine_counter.v VERILOG PATH state_machine_counter.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL interrupt_latency_counter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file interrupt_latency_counter.v VERILOG PATH interrupt_latency_counter.v
add_fileset_file irq_detector.v VERILOG PATH irq_detector.v
add_fileset_file state_machine_counter.v VERILOG PATH state_machine_counter.v

# 
# parameters
# 
add_parameter INTR_TYPE INTEGER 0
set_parameter_property INTR_TYPE DEFAULT_VALUE 0
set_parameter_property INTR_TYPE DISPLAY_NAME INTERRUPT_TYPE
set_parameter_property INTR_TYPE TYPE INTEGER
set_parameter_property INTR_TYPE DESCRIPTION {Value 0: level sensitive interrupt input; Value 1: edge/pulse interrupt input}
set_parameter_property INTR_TYPE UNITS None
set_parameter_property INTR_TYPE ALLOWED_RANGES {0:level 1:pulse}
set_parameter_property INTR_TYPE DISPLAY_HINT integer
set_parameter_property INTR_TYPE HDL_PARAMETER true
add_parameter CLOCK_RATE INTEGER 0
set_parameter_property CLOCK_RATE DEFAULT_VALUE 0
set_parameter_property CLOCK_RATE DISPLAY_NAME { CLOCK_RATE}
set_parameter_property CLOCK_RATE TYPE INTEGER
set_parameter_property CLOCK_RATE DESCRIPTION {Shows the frequency of the clock signal that is connected to the IP}
set_parameter_property CLOCK_RATE UNITS None
set_parameter_property CLOCK_RATE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLOCK_RATE HDL_PARAMETER true
set_parameter_property CLOCK_RATE SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property CLOCK_RATE SYSTEM_INFO_ARG clk
add_parameter IRQ_PORT_CNT INTEGER 32
set_parameter_property IRQ_PORT_CNT DEFAULT_VALUE 32
set_parameter_property IRQ_PORT_CNT DISPLAY_NAME IRQ_PORT_COUNT
set_parameter_property IRQ_PORT_CNT TYPE INTEGER
set_parameter_property IRQ_PORT_CNT DESCRIPTION {Allows user to configure the number of IRQ PORT to use.}
set_parameter_property IRQ_PORT_CNT UNITS None
set_parameter_property IRQ_PORT_CNT ALLOWED_RANGES 1:32
set_parameter_property IRQ_PORT_CNT HDL_PARAMETER true


# 
# display items
# 


proc elaborate {} {
set  IRQ_PORT_CNT [get_parameter_value IRQ_PORT_CNT]
# set avmm_addr_width [ log2ceil [expr {$IRQ_PORT_CNT+3}]]
# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point irq
# 
add_interface irq interrupt start
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset_n
set_interface_property irq irqScheme INDIVIDUAL_REQUESTS
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Input IRQ_PORT_CNT


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset reset_n
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

# add_interface_port avalon_slave avmm_addr address Input $avmm_addr_width
add_interface_port avalon_slave avmm_addr address Input 6
add_interface_port avalon_slave avmm_wrdata writedata Input 32
add_interface_port avalon_slave avmm_write write Input 1
add_interface_port avalon_slave avmm_read read Input 1
add_interface_port avalon_slave avmm_rddata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

# add device tree properties
set_module_assignment embeddedsw.dts.vendor "altr"
set_module_assignment embeddedsw.dts.name "altera_ilc"
set_module_assignment embeddedsw.dts.group "ilc"
set_module_assignment embeddedsw.dts.compatible "altr,ilc-1.0"
set_module_assignment embeddedsw.dts.params.altr,sw-fifo-depth "32"

}
# ==============================================================================
# Adapted from altera_avalon_half_rate_bridge.tcl - log2 and ceil
# ==============================================================================
# proc log2ceil {num} {
    # set val 0
    # set i 1
    # while {$i < $num} {
        # set val [expr $val + 1]
        # set i [expr 1 << $val]
    # }
    # return $val
# }

## Add documentation links for user guide and/or release notes
add_documentation_link "User Guide" https://documentation.altera.com/#/link/sfo1400787952932/lro1402071729562 
add_documentation_link "Release Notes" https://documentation.altera.com/#/link/hco1421698042087/hco1421698013408
