DISPLAY_NAME = Turbo
DESCRIPTION  = Altera Turbo Codec
GROUP = DSP/Error Detection and Correction
AUTHOR = Altera Corporation
#DATASHEET_URL = http://www.altera.com/literature/ug/ug_turbo.pdf
DATASHEET_URL = docs/an505.pdf

#Section names
TURBO_SPEC_SECTION_NAME = Turbo Specification
TURBO_DEC_SECTION_NAME = Turbo Decoder Options

#parameter strings that appear in Documentation page
TURBO_STANDARD_DISPLAY_NAME = Standard
CODEC_TYPE_DISPLAY_NAME = Codec Type
NUM_OF_ENGINES_DISPLAY_NAME = Number of Processors
DECODING_ALGORITHM_DISPLAY_NAME = MAP Decoding
NUM_OF_INPUTS_DISPLAY_NAME = Width of the Input LLRs
NUM_OF_LLR_DISPLAY_NAME = Number of LLRs per Input
NUM_OF_OUTPUTS_DISPLAY_NAME = Number of Output Bits
DECODER_DEBUG_DISPLAY_NAME = Enable decoder debug ports


TURBO_STANRARD_TYPE_DESCRIPTION = Select whether to use the LTE or UMTS Standard.
CODEC_TYPE_DESCRIPTION = Select whether to generate an encoder or decoder.
NUM_OF_ENGINES_DESCRIPTION = Select the number of parallel engines used by the decoder.
DECODING_ALGORITHM_DESCRIPTION = Select from a list of available decoding algorithms. Only Max logMAP is currently supported.
NUM_OF_INPUTS_DESCRIPTION = Select the number of input bits to the decoder.
NUM_OF_OUTPUTS_DESCRIPTION = Select the number of output bits from the decoder.

#WARNING Messages
FEATURE_NOT_SUPPORTED_WARNING = Clock Enable Port is deprecated and may be removed in a future release
NUM_ENGINES_WARNING = <b>NUM_OF_ENGINES_DISPLAY_NAME</b> ($engines) is not extensively tested. Contact Altera if you require this configuration.

#Error messages

NUM_ENGINES_ERROR = <b>NUM_OF_ENGINES_DISPLAY_NAME</b> ($engines) is not supported.
NUM_INPUT_BITS_ERROR = <b>DEC_INPUT_BITS_DISPLAY_NAME</b> ($dec_input_bits) is not supported. Contact Altera if you require this configuration.

#Parameter Names
UMTS_NAME = UMTS
LTE_NAME = LTE
ENCODER_NAME = Encoder
DECODER_NAME = Decoder
MAX_LOG_MAP_NAME = Max Log MAP
LOG_MAP_NAME = Log MAP 

