# Module name strings
HWTCL_MODULE_DISPLAY_NAME = EMIF Example QDR II/II+/II+ Xtreme Memory Model Component
HWTCL_MODULE_DESCRIPTION = Altera External Memory Interface Example II/II+/II+ Xtreme Memory Model Component
