AUTHOR      = Altera Corporation
DESCRIPTION = A collection of fixed point functions
GROUP       = Basic Functions/Arithmetic

RELEASE_NOTES = https://documentation.altera.com/#/link/hco1421698042087/hco1421698013408
USER_GUIDE = http://www.altera.com/literature/ug/ug_altfp_mfug.pdf

RELEASE_NOTES_DISPLAY_NAME = Release Notes
USER_GUIDE_DISPLAY_NAME    = User Guide


#Groups
ALL_GRP =   All

FUNCTION_FAMILY_DISPLAY_NAME     = Family
FUNCTION_FAMILY_DESCRIPTION      = Choose the fixed point function

#Function display names
ADD_DISPLAY_NAME                 = Parallel add
MUL_DISPLAY_NAME                 = Multiply
DIV_DISPLAY_NAME                 = Divide
SQRT_DISPLAY_NAME                = Square root
SIMPLE_COUNTER_DISPLAY_NAME      = Simple Counter
LOADABLE_COUNTER_DISPLAY_NAME    = Loadable Counter

ALL_FUNCTION_DISPLAY_NAME        = Function
ALL_FUNCTION_DESCRIPTION         = Parallel Add adds two or more fixed-point inputs; Multiply multiplies real or complex fixed-point inputs

CHECK_PERFORMANCE_BUTTON_DISPLAY_NAME  = Check Performance
CHECK_PERFORMANCE_BUTTON_DESCRIPTION   = Press button to check if the requested latency is achievable and if so at what frequency

CHECK_OUTPUT_WIDTH_BUTTON_DISPLAY_NAME = Check output width
CHECK_OUTPUT_WIDTH_BUTTON_DESCRIPTION  = Re-compute optimal output width based on the selected operation and input widths

COMPLEX_FORMAT_DISPLAY_NAME      = Complex data 
COMPLEX_FORMAT_DESCRIPTION       = Inputs and outputs of complex functions consist of real and imaginary components of the specified data format. Total width is twice the width of an individual component. The real part of a complex value occupies its low-order bits. 

COMPLEX_KARATSUBA_DISPLAY_NAME   = Karatsuba complex multiplication
COMPLEX_KARATSUBA_DESCRIPTION    = Karatsuba multiplication of complex numbers reduces the number of multipliers and hence DSP block usage, at the cost of higher latency and increased logic utilization.
 
FREQUENCY_TARGET_DISPLAY_NAME    = Target
FREQUENCY_TARGET_UNITS           = Megahertz
FREQUENCY_TARGET_DESCRIPTION     = Choose the frequency in MHz at which this function is expected to run. This together with the target device family will determine the amount of pipelining.
LATENCY_TARGET_DISPLAY_NAME      = Target
LATENCY_TARGET_UNITS             = Cycles
LATENCY_TARGET_DESCRIPTION       = Choose the required latency

PERFORMANCE_GOAL_DISPLAY_NAME    = Goal
PERFORMANCE_GOAL_DESCRIPTION     = Choose the performance target

FREQUENCY_REP_NAME               = Frequency
LATENCY_REP_NAME                 = Latency
COMBINED_REP_NAME                = Combined

OPTIMAL_OUTPUT_FORMAT_DISPLAY_NAME = Optimal output format
OPTIMAL_OUTPUT_FORMAT_DESCRIPTION  = The output format will be determined automatically based on the input(s) and operation

GEN_ENABLE_DISPLAY_NAME          = Generate an enable port
GEN_ENABLE_DESCRIPTION           = Choose if the function should have an enable signal.

FORCE_MULT_IN_LOGIC_DISPLAY_NAME = Force multiplication in logic
FORCE_MULT_IN_LOGIC_DESCRIPTION  = Generate the multipliers in logic instead of using DSP blocks

ADD_NO_GROWTH_DISPLAY_NAME       = Disable adder word growth
ADD_NO_GROWTH_DESCRIPTION        = The addition and/or subtraction logic in the IP core normally allows for word growth, but you can disable word growth using this option

LOADABLE_COUNTER_DISPLAY_NAME    = Loadable counter
LOADABLE_COUNTER_DESCRIPTION     = Generate a counter with inputs which allow the initial value, step, and limit to be loaded at run time.

NUM_INPUTS_DISPLAY_NAME          = Number of inputs
NUM_INPUTS_UNITS                 = None
NUM_INPUTS_DESCRIPTION           = Select the number of inputs for this function

INITIAL_VALUE_DISPLAY_NAME       = Initial value
INITIAL_VALUE_DESCRIPTION        = The counter is initialised to this value on reset, and returns to it when applying the step would result in the limit being reached
STEP_VALUE_DISPLAY_NAME          = Step
STEP_VALUE_DESCRIPTION           = Increment applied on each cycle that the counter's enable input is high. The simple counter's step must be positive. 
LIMIT_VALUE_DISPLAY_NAME         = Limit
LIMIT_VALUE_DESCRIPTION          = If incrementing the counter would result in the limit being reached, the counter returns to its initial value. The counter output only runs up to the limit value.

FXP_WIDTH_DISPLAY_NAME           = Width
FXP_WIDTH_UNITS                  = Bits
FXP_WIDTH_DESCRIPTION            = Choose the width of the fixed point data
FXP_FRACTION_DISPLAY_NAME        = Fraction
FXP_FRACTION_UNITS               = Bits
FXP_FRACTION_DESCRIPTION         = Choose the number of fraction bits
FXP_SIGNED_DISPLAY_NAME          = Sign
FXP_SIGNED_DESCRIPTION           = Choose the signedness of the fixed point data

SIGNED_REP_NAME                  = signed
UNSIGNED_REP_NAME                = unsigned




