# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor __VERSION__
# Fri Oct 09 14:05:33 BST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_sdm_mbox_fabric "altera_sdm_mbox_fabric" v1.0
# | null 2009.10.09.14:05:29
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 14.1
# | 
package require -exact qsys 14.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_sdm_mbox_fabric
# | 
set_module_property NAME altera_sdm_mbox_fabric
set_module_property VERSION 18.1
set_module_property AUTHOR "Altera Corporation"
set_module_property INTERNAL true
set_module_property DISPLAY_NAME "Altera SDM Mbox Fabric"
set_module_property EDITABLE false
set_module_property OPAQUE_ADDRESS_MAP false
set_module_property REPORT_TO_TALKBACK true
set_module_property composition_callback compose
set_module_property GROUP "Basic Functions/Configuration and Programming"
set all_supported_device_families_list {"Stratix 10"}
set_module_property SUPPORTED_DEVICE_FAMILIES       $all_supported_device_families_list
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_display_item "" "Stream Endpoint Information Table" "group" "table"

add_parameter ENDPOINT_INDEX STRING_LIST ep_0
set_parameter_property ENDPOINT_INDEX DISPLAY_NAME {ENDPOINT_INDEX}
set_parameter_property ENDPOINT_INDEX AFFECTS_ELABORATION true
set_parameter_property ENDPOINT_INDEX AFFECTS_GENERATION true
set_parameter_property ENDPOINT_INDEX HDL_PARAMETER false
set_parameter_property ENDPOINT_INDEX DERIVED true
set_parameter_property ENDPOINT_INDEX GROUP "Stream Endpoint Information Table"
set_parameter_property ENDPOINT_INDEX DESCRIPTION {List of endpoint that have stream interface}

add_parameter HAS_STREAM INTEGER_LIST 1
set_parameter_property HAS_STREAM DISPLAY_NAME {HAS_STREAM}
set_parameter_property HAS_STREAM AFFECTS_ELABORATION true
set_parameter_property HAS_STREAM AFFECTS_GENERATION true
set_parameter_property HAS_STREAM HDL_PARAMETER false
set_parameter_property HAS_STREAM DERIVED true
set_parameter_property HAS_STREAM GROUP "Stream Endpoint Information Table"
set_parameter_property HAS_STREAM DESCRIPTION {List of endpoint that have stream interface}

add_parameter STR_MUX_SELECT STRING_LIST  2'b00
set_parameter_property STR_MUX_SELECT DISPLAY_NAME {STR_MUX_SELECT}
set_parameter_property STR_MUX_SELECT AFFECTS_ELABORATION true
set_parameter_property STR_MUX_SELECT AFFECTS_GENERATION true
set_parameter_property STR_MUX_SELECT HDL_PARAMETER false
set_parameter_property STR_MUX_SELECT DERIVED true
set_parameter_property STR_MUX_SELECT GROUP "Stream Endpoint Information Table"
set_parameter_property STR_MUX_SELECT DESCRIPTION {The value assigned for multiplexer select}

add_parameter CLIENT_ID INTEGER_LIST  14
set_parameter_property CLIENT_ID DISPLAY_NAME {CLIENT_ID}
set_parameter_property CLIENT_ID AFFECTS_ELABORATION true
set_parameter_property CLIENT_ID AFFECTS_GENERATION true
set_parameter_property CLIENT_ID HDL_PARAMETER false
set_parameter_property CLIENT_ID DERIVED true
set_parameter_property CLIENT_ID GROUP "Stream Endpoint Information Table"
set_parameter_property CLIENT_ID DESCRIPTION {The value assigned for multiplexer select}


add_parameter NUM_STR_ENDPOINTS INTEGER 1 ""
set_parameter_property NUM_STR_ENDPOINTS DEFAULT_VALUE 1
set_parameter_property NUM_STR_ENDPOINTS DISPLAY_NAME "NUmber of streaming endpoint"
set_parameter_property NUM_STR_ENDPOINTS TYPE INTEGER
set_parameter_property NUM_STR_ENDPOINTS UNITS None
set_parameter_property NUM_STR_ENDPOINTS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_STR_ENDPOINTS DESCRIPTION ""
set_parameter_property NUM_STR_ENDPOINTS DERIVED true
set_parameter_property NUM_STR_ENDPOINTS HDL_PARAMETER false


#add_parameter SETTINGS string ""
add_parameter SETTINGS string "{ready_latency 0 has_urgent 1 has_stream 0 max_size 256 stream_width 64 clock clk_0 clock_rate_clk 50000000} {ready_latency 1 has_urgent 0 has_stream 1 max_size 256 stream_width 64 clock clk_0 clock_rate_clk 60000000} {ready_latency 2 has_urgent 1 has_stream 1 max_size 256 stream_width 64 clock clk_0 clock_rate_clk 60000000}"
set_parameter_property SETTINGS DISPLAY_NAME "TCL encoding of the connected slave"
set_parameter_property SETTINGS UNITS None
set_parameter_property SETTINGS DESCRIPTION "The debug connection transform will set this up for you"
set_parameter_property SETTINGS DISPLAY_HINT "rows:5"
set_parameter_property SETTINGS AFFECTS_GENERATION true
set_parameter_property SETTINGS HDL_PARAMETER false
set_parameter_property SETTINGS STATUS experimental

# SETTINGS entries are of the form:
# { ready_latency 0 has_urgent 1 has_stream 0 max_size 256 stream_width 64 }

# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection points
# | 
# clock and reset
add_interface clk clock sink
add_interface reset reset sink
# AXI master and slave interfaces
add_interface axi_master axi4 master
add_interface axi_slave axi4 slave

# Control interfaces: GPI GPO IRQ 
add_interface sdm_gpi_irq conduit end
add_interface sdm_gpo conduit end
add_interface sdm_gpi conduit end

# | 
# +-----------------------------------

proc compose {} {
	add_instance clk_bridge altera_clock_bridge 18.1
    set_instance_parameter_value clk_bridge {EXPLICIT_CLOCK_RATE} {0.0}
    set_instance_parameter_value clk_bridge {NUM_CLOCK_OUTPUTS} {1}

    add_instance reset_bridge altera_reset_bridge 18.1
    set_instance_parameter_value reset_bridge {ACTIVE_LOW_RESET} {0}
    set_instance_parameter_value reset_bridge {SYNCHRONOUS_EDGES} {deassert}
    set_instance_parameter_value reset_bridge {NUM_RESET_OUTPUTS} {1}
    set_instance_parameter_value reset_bridge {USE_RESET_REQUEST} {0}


    add_instance mbox_mutiplexer altera_mailbox_mutiplexer 18.1
    set_instance_parameter_value mbox_mutiplexer {USE_MEMORY_BLOCKS} {1}
    set_instance_parameter_value mbox_mutiplexer {ADDR_W} {4}
    set_instance_parameter_value mbox_mutiplexer {ST_DATA_W} {32}
    set_instance_parameter_value mbox_mutiplexer {DEPTH} {16}
    set_instance_parameter_value mbox_mutiplexer {ID_W} {4}
    #set_instance_parameter_value mbox_mutiplexer {NUM_ENDPOINTS} {2}

    add_instance nd_mailbox_driver altera_nd_mailbox_driver 18.1
    set_instance_parameter_value nd_mailbox_driver {HAS_URGENT} {0}
    set_instance_parameter_value nd_mailbox_driver {HAS_STREAM} {0}
    set_instance_parameter_value nd_mailbox_driver {GPI_WIDTH} {4}
    set_instance_parameter_value nd_mailbox_driver {ADDR_W} {32}
    set_instance_parameter_value nd_mailbox_driver {DATA_W} {64}
    set_instance_parameter_value nd_mailbox_driver {ID_W} {4}
    set_instance_parameter_value nd_mailbox_driver {USER_W} {5}
    # For now, fixed the stream at 64 bits, if clients are 32 bits, the data adapter will be inserted
    set_instance_parameter_value nd_mailbox_driver {STREAM_WIDTH} {64}

    # connections and connection parameters
    add_connection mbox_mutiplexer.cmd_out nd_mailbox_driver.command_packet avalon_streaming

    add_connection nd_mailbox_driver.response_packet mbox_mutiplexer.rsp_in avalon_streaming

    add_connection clk_bridge.out_clk reset_bridge.clk clock
    add_connection clk_bridge.out_clk mbox_mutiplexer.clk clock
    add_connection clk_bridge.out_clk nd_mailbox_driver.clock clock

    add_connection reset_bridge.out_reset nd_mailbox_driver.reset reset
    add_connection reset_bridge.out_reset mbox_mutiplexer.reset reset

    # exported interfaces
    set_interface_property axi_master EXPORT_OF nd_mailbox_driver.axi_master
    set_interface_property axi_slave EXPORT_OF nd_mailbox_driver.axi_slave
    
    set_interface_property clk EXPORT_OF clk_bridge.in_clk
    set_interface_property reset EXPORT_OF reset_bridge.in_reset
    set_interface_property sdm_gpi_irq EXPORT_OF nd_mailbox_driver.irq
    set_interface_property sdm_gpo EXPORT_OF nd_mailbox_driver.gpo
    set_interface_property sdm_gpi EXPORT_OF nd_mailbox_driver.gpi


	set settings [get_parameter_value SETTINGS]
	#send_message {info text} "Settings: $settings"

	# Find out endpoint configuration
    # n: total of number endpoints
    # For endpoint, command and response are a must but urgent and stream can be optional
    # find how many urgent and stream interfaces for all endpoints. Note that need to follow 
    # the index of endpoint or else it will break
	set n [llength $settings]
    set numb_urg_ep_index ""
    set numb_str_ep_index ""
    set has_stream  ""
    set stream_width  ""
    set clock_list  ""
    #send_message {info text} "Settings n value: $n"

	for { set i 0 } { $i < $n } { incr i } {
		set setting [lindex $settings $i]

		array set conf {ready_latency 0 has_urgent 1 has_stream 0 max_size 256 stream_width 64 clock clk_0 clock_rate_clk 50000000}
		catch {array set conf $setting}
        #send_message {info text} "$i: [array get conf]"
        
        if {$conf(has_urgent) == 1} {
            lappend numb_urg_ep_index $i
        }
        if {$conf(has_stream) == 1} {
            lappend numb_str_ep_index $i
            lappend stream_width $conf(stream_width)
        }
        lappend has_stream $conf(has_stream)
        lappend clock_list $conf(clock)
	}
    # some cases, mutiple clients can use same clock, detect this and remove the duplicated clock name
    set unique_clock_list [lsort -unique $clock_list]

    set numb_urg_ep [llength $numb_urg_ep_index]; 
    set numb_str_ep [llength $numb_str_ep_index];
    set numb_clk_ep [llength $unique_clock_list];

    #send_message {info text} "Settings has_stream : $has_stream"
    #send_message {info text} "Settings stream_width : $stream_width"
    #send_message {info text} "Settings clock_list : $clock_list"
    #send_message {info text} "Settings unique_clock_list : $unique_clock_list"
    #send_message {info text} "Settings numb_urg_ep_index value: $numb_urg_ep_index"
    #send_message {info text} "Settings numb_str_ep_index value: $numb_str_ep_index"
    set_parameter_value HAS_STREAM $has_stream
    set_parameter_value NUM_STR_ENDPOINTS $numb_str_ep


    
    #send_message {info text} "Settings numb_urg_ep value: $numb_urg_ep"
    #send_message {info text} "Settings numb_str_ep value: $numb_str_ep"

    # Build the seleciton value of the mux for streaming endpoint
    set mux_str_select_value ""
    set mux_str_select_bin_value ""
    set mux_str_select_dec 0
    set endpoint_index ""
    # build the client ID
    set clientid_count 0
    set clientid ""
    for { set i 0 } { $i < $n } { incr i } {
        set m [lindex $has_stream $i]
        if {$numb_str_ep != 0} {
            if {$m != 0} {
                lappend clientid $clientid_count
                set clientid_count [expr $clientid_count + 1] 
                set mux_str_select_dec [expr $mux_str_select_dec + 1]
                lappend mux_str_select_value $mux_str_select_dec
                lappend mux_str_select_bin_value [dec2bin $mux_str_select_dec $numb_str_ep]
            } else {
                #set mux_str_select_dec [expr $mux_str_select_dec + 1]
                lappend clientid 14
                lappend mux_str_select_value 0
                lappend mux_str_select_bin_value [dec2bin 0 $numb_str_ep]
            }
        } else {
            lappend mux_str_select_bin_value [dec2bin 0 ""]
        }
        lappend endpoint_index Endpoint_${i}
    }   
    set_parameter_value STR_MUX_SELECT $mux_str_select_bin_value
    set_parameter_value ENDPOINT_INDEX $endpoint_index
    set_parameter_value CLIENT_ID $clientid
    #send_message {info text} "Settings mux_str_select_value : $mux_str_select_value"
    #send_message {info text} "Settings clientid : $clientid"

    # Set number of endpint to the mailbox multiplexer
    set_instance_parameter_value mbox_mutiplexer {NUM_ENDPOINTS} $n
    set_instance_parameter_value mbox_mutiplexer {ENDPOINT_INDEX}    [get_parameter_value ENDPOINT_INDEX]
    set_instance_parameter_value mbox_mutiplexer {HAS_STREAM}        [get_parameter_value HAS_STREAM]
    set_instance_parameter_value mbox_mutiplexer {CLIENT_ID}         [get_parameter_value CLIENT_ID]
    set_instance_parameter_value mbox_mutiplexer {STR_MUX_SELECT}    [get_parameter_value STR_MUX_SELECT]
    set_instance_parameter_value mbox_mutiplexer {NUM_STR_ENDPOINTS} [get_parameter_value NUM_STR_ENDPOINTS]




    # Add Stream multiplexer instance
    if {$numb_str_ep != 0} {
        set_instance_parameter_value nd_mailbox_driver {HAS_STREAM} {1}

        add_instance mbox_stream_multiplexer altera_nd_mailbox_stream_multiplexer 18.1
        set_instance_parameter_value mbox_stream_multiplexer {PIPELINE_ARB} {1}
        # Stream width use witht the mux is always 64
        set_instance_parameter_value mbox_stream_multiplexer {STREAM_WIDTH} {64}
        set_instance_parameter_value mbox_stream_multiplexer {NUM_ENDPOINTS} $numb_str_ep
        add_connection mbox_stream_multiplexer.stream_out_int nd_mailbox_driver.stream_packet avalon_streaming
        add_connection clk_bridge.out_clk mbox_stream_multiplexer.clk clock
        add_connection reset_bridge.out_reset mbox_stream_multiplexer.reset reset
        # connect these internal signals to the stream id decoder
        add_connection nd_mailbox_driver.stream_select mbox_stream_multiplexer.stream_select conduit
        add_connection nd_mailbox_driver.stream_active mbox_stream_multiplexer.stream_active conduit
        # connect these internal signals to the ID mapper inside the mailbox multiplexer
        #add_connection mbox_stream_multiplexer.stream_id_decode  mbox_mutiplexer.stream_id_decode avalon_streaming
        #add_connection mbox_mutiplexer.mux_sel_decoded          mbox_stream_multiplexer.mux_sel_decoded avalon_streaming
    }

    # Add Urgent multiplexer instance
    if {$numb_urg_ep != 0} {
        set_instance_parameter_value nd_mailbox_driver {HAS_URGENT} {1}
        add_instance mbox_urgent_multiplexer altera_nd_mailbox_urgent_multiplexer 18.1
        set_instance_parameter_value mbox_urgent_multiplexer {PIPELINE_ARB} {1}
        set_instance_parameter_value mbox_urgent_multiplexer {NUM_ENDPOINTS} $numb_urg_ep
        add_connection mbox_urgent_multiplexer.urg_out_int nd_mailbox_driver.urgent_packet avalon_streaming
        add_connection clk_bridge.out_clk mbox_urgent_multiplexer.clk clock
        add_connection reset_bridge.out_reset mbox_urgent_multiplexer.reset reset
    }
    # Create clock instance
    for { set i 0 } { $i < $numb_clk_ep } { incr i } {
        # Create clock and reset bridge for each endpont clock
        set clk_name [lindex $unique_clock_list $i]
        add_interface clk_$i clock sink
        add_instance  clk_ep_$clk_name altera_clock_bridge 18.1
        set_instance_parameter_value clk_ep_$clk_name {EXPLICIT_CLOCK_RATE} {0.0}
        set_instance_parameter_value clk_ep_$clk_name {NUM_CLOCK_OUTPUTS} {1}
        set_interface_property clk_$i EXPORT_OF clk_ep_$clk_name.in_clk

        #add_interface reset_$i reset end
        #add_instance ep_reset_$clk_name altera_reset_bridge
        #set_interface_property reset_$i export_of ep_reset_$clk_name.in_reset
        #add_connection clk_ep_$clk_name.out_clk ep_reset_$clk_name.clk
    }
    # Create reset instance
    # eventhoug endpoints can use same clock, but the reset is seperated for each endpoint
    for { set i 0 } { $i < $n } { incr i } {
        set clk_point [lindex $clock_list $i]
        add_interface reset_$i reset end
        add_instance ep_reset_$i altera_reset_bridge
        set_interface_property reset_$i export_of ep_reset_$i.in_reset
        add_connection clk_ep_$clk_point.out_clk ep_reset_$i.clk
    }


    # Command and response interfaces
    for { set i 0 } { $i < $n } { incr i } {
        # Clock and reset for each endpoints, these clocks are used to connect to the clock crosser
        #add_interface clk_$i clock sink
        #add_instance  clk_ep_$i altera_clock_bridge 18.1
        #set_instance_parameter_value clk_ep_$i {EXPLICIT_CLOCK_RATE} {0.0}
        #set_instance_parameter_value clk_ep_$i {NUM_CLOCK_OUTPUTS} {1}
        #set_interface_property clk_$i EXPORT_OF clk_ep_$i.in_clk

        #add_interface reset_$i reset end
        #add_instance ep_reset_$i altera_reset_bridge
        #set_interface_property reset_$i export_of ep_reset_$i.in_reset
        #add_connection clk_ep_$i.out_clk ep_reset_$i.clk

        # For now, each interface has its own clock crossing (even the case two clients use same clock, optimize it later)
        set clk_point [lindex $clock_list $i]

        # CLock crosser for command interfaces
        add_instance command_${i}_clock_crosser_${i} altera_avalon_st_handshake_clock_crosser 18.1
        set_instance_parameter_value command_${i}_clock_crosser_${i} {DATA_WIDTH} {32}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {BITS_PER_SYMBOL} {32}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {USE_PACKETS} {1}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {USE_CHANNEL} {0}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {CHANNEL_WIDTH} {1}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {MAX_CHANNEL} {0}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {USE_ERROR} {0}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {ERROR_WIDTH} {1}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {VALID_SYNC_DEPTH} {2}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {READY_SYNC_DEPTH} {2}
        set_instance_parameter_value command_${i}_clock_crosser_${i} {USE_OUTPUT_PIPELINE} {1}
        # Connect clock and reset to the clock crosser
        add_connection clk_ep_$clk_point.out_clk command_${i}_clock_crosser_${i}.in_clk clock
        add_connection ep_reset_$i.out_reset command_${i}_clock_crosser_${i}.in_clk_reset reset
        add_connection clk_bridge.out_clk command_${i}_clock_crosser_${i}.out_clk clock
        add_connection reset_bridge.out_reset command_${i}_clock_crosser_${i}.out_clk_reset reset
        # Connect avalon interfaces of clock crosser
        add_interface command_$i avalon_streaming sink
        set_interface_property command_$i EXPORT_OF command_${i}_clock_crosser_${i}.in
        add_connection  command_${i}_clock_crosser_${i}.out mbox_mutiplexer.cmd_in$i avalon_streaming


        # CLock crosser for response interfaces, response is a source interface, in clock is system clock (int oscilator from sdm bridge)
        # out lock is clk_x to end points
        #add_interface command_$i avalon_streaming sink
        #set_interface_property command_$i EXPORT_OF mbox_mutiplexer.cmd_in$i
        add_instance response_${i}_clock_crosser_${i} altera_avalon_st_handshake_clock_crosser 18.1
        set_instance_parameter_value response_${i}_clock_crosser_${i} {DATA_WIDTH} {32}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {BITS_PER_SYMBOL} {32}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {USE_PACKETS} {1}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {USE_CHANNEL} {0}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {CHANNEL_WIDTH} {1}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {MAX_CHANNEL} {0}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {USE_ERROR} {0}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {ERROR_WIDTH} {1}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {VALID_SYNC_DEPTH} {2}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {READY_SYNC_DEPTH} {2}
        set_instance_parameter_value response_${i}_clock_crosser_${i} {USE_OUTPUT_PIPELINE} {1}
        # Connect clock and reset to the clock crosser
        add_connection clk_ep_$clk_point.out_clk response_${i}_clock_crosser_${i}.out_clk clock
        add_connection ep_reset_$i.out_reset response_${i}_clock_crosser_${i}.out_clk_reset reset
        add_connection clk_bridge.out_clk response_${i}_clock_crosser_${i}.in_clk clock
        add_connection reset_bridge.out_reset response_${i}_clock_crosser_${i}.in_clk_reset reset
        add_interface response_$i avalon_streaming source
        set_interface_property response_$i EXPORT_OF response_${i}_clock_crosser_${i}.out
        add_connection  mbox_mutiplexer.rsp_out$i response_${i}_clock_crosser_${i}.in avalon_streaming
        
    }

    # Urgent interfaces
    for { set j 0 } { $j < $numb_urg_ep } { incr j } {
        # read the index and use it as the name for interfaces
        set i [lindex $numb_urg_ep_index $j]
        #set_interface_property urgent_$i EXPORT_OF mbox_urgent_multiplexer.urg_in$i
        # CLock crosser for urgent interfaces
        set clk_point [lindex $clock_list $i]

        add_instance urgent_${i}_clock_crosser_${i} altera_avalon_st_handshake_clock_crosser 18.1
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {DATA_WIDTH} {32}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {BITS_PER_SYMBOL} {32}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {USE_PACKETS} {0}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {USE_CHANNEL} {0}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {CHANNEL_WIDTH} {1}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {MAX_CHANNEL} {0}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {USE_ERROR} {0}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {ERROR_WIDTH} {1}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {VALID_SYNC_DEPTH} {2}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {READY_SYNC_DEPTH} {2}
        set_instance_parameter_value urgent_${i}_clock_crosser_${i} {USE_OUTPUT_PIPELINE} {1}
        # Connect clock and reset to the clock crosser
        add_connection clk_ep_$clk_point.out_clk urgent_${i}_clock_crosser_${i}.in_clk clock
        add_connection ep_reset_$i.out_reset urgent_${i}_clock_crosser_${i}.in_clk_reset reset
        add_connection clk_bridge.out_clk urgent_${i}_clock_crosser_${i}.out_clk clock
        add_connection reset_bridge.out_reset urgent_${i}_clock_crosser_${i}.out_clk_reset reset
        # Connect avalon interfaces of clock crosser
        #add_connection command_$i command_${i}_clock_crosser_${i}.in avalon_streaming
        add_interface urgent_$i avalon_streaming sink
        set_interface_property urgent_$i EXPORT_OF urgent_${i}_clock_crosser_${i}.in
        #add_connection  urgent_${i}_clock_crosser_${i}.out mbox_urgent_multiplexer.urg_in$i avalon_streaming
        # the mux still goes with 0 - 1 - 2 ...
        add_connection  urgent_${i}_clock_crosser_${i}.out mbox_urgent_multiplexer.urg_in${j} avalon_streaming
    }


    # Stream interfaces
    for { set k 0 } { $k < $numb_str_ep } { incr k } {
        # read the index and use it as the name for interfaces
        set i       [lindex $numb_str_ep_index $k]
        set str_width   [lindex $stream_width $k]
        set clk_point [lindex $clock_list $i]
        #add_interface stream_$i avalon_streaming sink
        #set_interface_property stream_$i EXPORT_OF mbox_stream_multiplexer.stream_in_$i
        # CLock crosser for stream interfaces    
        add_instance stream_${i}_clock_crosser_${i} altera_avalon_st_handshake_clock_crosser 18.1
        #set_instance_parameter_value stream_${i}_clock_crosser_${i} {DATA_WIDTH} {64}
        #set_instance_parameter_value stream_${i}_clock_crosser_${i} {BITS_PER_SYMBOL} {64}
        # Stream width is 32 bits for now
        #set_instance_parameter_value stream_${i}_clock_crosser_${i} {DATA_WIDTH} {32}
        #set_instance_parameter_value stream_${i}_clock_crosser_${i} {BITS_PER_SYMBOL} {32}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {DATA_WIDTH} $str_width
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {BITS_PER_SYMBOL} $str_width
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {USE_PACKETS} {0}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {USE_CHANNEL} {0}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {CHANNEL_WIDTH} {1}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {MAX_CHANNEL} {0}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {USE_ERROR} {0}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {ERROR_WIDTH} {1}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {VALID_SYNC_DEPTH} {2}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {READY_SYNC_DEPTH} {2}
        set_instance_parameter_value stream_${i}_clock_crosser_${i} {USE_OUTPUT_PIPELINE} {1}
        # Connect clock and reset to the clock crosser
        add_connection clk_ep_$clk_point.out_clk stream_${i}_clock_crosser_${i}.in_clk clock
        add_connection ep_reset_$i.out_reset stream_${i}_clock_crosser_${i}.in_clk_reset reset
        add_connection clk_bridge.out_clk stream_${i}_clock_crosser_${i}.out_clk clock
        add_connection reset_bridge.out_reset stream_${i}_clock_crosser_${i}.out_clk_reset reset
        # Connect avalon interfaces of clock crosser
        #add_connection command_$i command_${i}_clock_crosser_${i}.in avalon_streaming
        add_interface stream_$i avalon_streaming sink
        set_interface_property stream_$i EXPORT_OF stream_${i}_clock_crosser_${i}.in
        #add_connection  stream_${i}_clock_crosser_${i}.out mbox_stream_multiplexer.stream_in_$i avalon_streaming
        # if the client is 32 bits, then output of the clock crosser, connect through the adapter to conver data from 32 to 64
        if { $str_width == 32} {
            add_instance stream_${i}_data_adapter_32_64 altera_mbox_data_adapter 18.1
            add_connection clk_bridge.out_clk stream_${i}_data_adapter_32_64.clock clock
            add_connection reset_bridge.out_reset stream_${i}_data_adapter_32_64.reset reset

            add_connection  stream_${i}_clock_crosser_${i}.out stream_${i}_data_adapter_32_64.in avalon_streaming
            add_connection  stream_${i}_data_adapter_32_64.out mbox_stream_multiplexer.stream_in_${k} avalon_streaming
        } else {
            add_connection  stream_${i}_clock_crosser_${i}.out mbox_stream_multiplexer.stream_in_${k} avalon_streaming
        }
        
        # Stream active interfaces
        add_interface stream_active_$i conduit start
        #set_interface_property stream_active_$i EXPORT_OF mbox_stream_multiplexer.stream_active_$i
        # Overwrite the name, composed component, for conduit, it will append the name
        #set_interface_property stream_active_$i PORT_NAME_MAP "stream_active_${i} stream_active_${i}_active_${i}"
        # add the clock crosser for stream active
        add_instance stream_active_${i}_clock_crosser_${i} altera_mbox_synchronizer 18.1
        set_instance_parameter_value stream_active_${i}_clock_crosser_${i} {WIDTH} {1}
        # Do connections
        add_connection clk_ep_$clk_point.out_clk stream_active_${i}_clock_crosser_${i}.clock_out clock
        add_connection ep_reset_$i.out_reset stream_active_${i}_clock_crosser_${i}.reset_out reset
        add_connection clk_bridge.out_clk stream_active_${i}_clock_crosser_${i}.clock_in clock
        add_connection reset_bridge.out_reset stream_active_${i}_clock_crosser_${i}.reset_in reset
        set_interface_property stream_active_$i EXPORT_OF stream_active_${i}_clock_crosser_${i}.stream_active
        #add_connection mbox_stream_multiplexer.stream_active_$i stream_active_${i}_clock_crosser_${i}.stream_active_0 conduit
        add_connection mbox_stream_multiplexer.stream_active_${k} stream_active_${i}_clock_crosser_${i}.stream_active_0 conduit
    }

}


proc log2ceil x "expr {int(ceil(log(\$x)/[expr log(2)]))}"

proc dec2bin {i {width {}}} {
    if {$i != 0} {
        set res {1}
    } else {
        set res {0}
    }
    
    for {set j 1} {$j < $i} {incr j} {
        append res 0
    }

    if {$width != {}} {
        append d [string repeat 0 $width] $res
        set res [string range $d [string length $res] end]
        return $width'b$res    
    } else {
        # nothing then default return zero
        return 1'b0
    }
    
}