# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.0
# Thu Oct 31 15:17:20 MYT 2013
# DO NOT MODIFY


# 
# altera_smb "Altera Avalon System Management Bus" v1.0
# Altera Corporation 2013.10.31.15:17:20
# This component is a two wire serial interface through which various system component devices communicate with each other.
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module altera_smb
# 
set_module_property DESCRIPTION "This component is a two wire serial interface through which various system component devices communicate with each other."
set_module_property NAME altera_smb
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Serial"
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera Avalon System Management Bus"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property VALIDATION_CALLBACK "validate"
#set_module_property ELABORATION_CALLBACK "elaborate"

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_smb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_smb.v VERILOG PATH altera_smb.v TOP_LEVEL_FILE
add_fileset_file altr_smb_condt_det.v VERILOG PATH altr_smb_condt_det.v
add_fileset_file altr_smb_csr.v VERILOG PATH altr_smb_csr.v
add_fileset_file altr_smb_intr_ctrl.v VERILOG PATH altr_smb_intr_ctrl.v
add_fileset_file altr_smb_pec_gen.v VERILOG PATH altr_smb_pec_gen.v
add_fileset_file altr_smb_rxfifo.v VERILOG PATH altr_smb_rxfifo.v
add_fileset_file altr_smb_rxshifter.v VERILOG PATH altr_smb_rxshifter.v
add_fileset_file altr_smb_slvfsm.v VERILOG PATH altr_smb_slvfsm.v
add_fileset_file altr_smb_txfifo.v VERILOG PATH altr_smb_txfifo.v
add_fileset_file altr_smb_txout.v VERILOG PATH altr_smb_txout.v
add_fileset_file altr_smb_txshifter.v VERILOG PATH altr_smb_txshifter.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_smb
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_smb.v VERILOG PATH altera_smb.v
add_fileset_file altr_smb_condt_det.v VERILOG PATH altr_smb_condt_det.v
add_fileset_file altr_smb_csr.v VERILOG PATH altr_smb_csr.v
add_fileset_file altr_smb_intr_ctrl.v VERILOG PATH altr_smb_intr_ctrl.v
add_fileset_file altr_smb_pec_gen.v VERILOG PATH altr_smb_pec_gen.v
add_fileset_file altr_smb_rxfifo.v VERILOG PATH altr_smb_rxfifo.v
add_fileset_file altr_smb_rxshifter.v VERILOG PATH altr_smb_rxshifter.v
add_fileset_file altr_smb_slvfsm.v VERILOG PATH altr_smb_slvfsm.v
add_fileset_file altr_smb_txfifo.v VERILOG PATH altr_smb_txfifo.v
add_fileset_file altr_smb_txout.v VERILOG PATH altr_smb_txout.v
add_fileset_file altr_smb_txshifter.v VERILOG PATH altr_smb_txshifter.v


# 
# parameters
# 
add_parameter 			SMB_SLV_RCV_HOLD_EN boolean true
set_parameter_property 	SMB_SLV_RCV_HOLD_EN DISPLAY_NAME "Enable slave receive hold"
set_parameter_property 	SMB_SLV_RCV_HOLD_EN TYPE boolean
set_parameter_property 	SMB_SLV_RCV_HOLD_EN DESCRIPTION "When 1, upon receiving the full 8 bit data byte, altera_smb holds the SMBCLK to low. When 0, upon receiving the full 8 bit data byte, altera_smb does not hold the SMBCLK and respond with an ACK/NACK based on the defined rules."
set_parameter_property 	SMB_SLV_RCV_HOLD_EN HDL_PARAMETER true

add_parameter 			SMB_PEC_EN boolean true
set_parameter_property 	SMB_PEC_EN DISPLAY_NAME "Enable PEC mode"
set_parameter_property 	SMB_PEC_EN TYPE boolean
set_parameter_property 	SMB_PEC_EN DESCRIPTION "When 1, SMBus transfer is supporting Packet Error Checking (PEC). When 0, SMBus transfer is without PEC."
set_parameter_property 	SMB_PEC_EN HDL_PARAMETER true

add_parameter 			DEFAULT_M_STOP_COND boolean true
set_parameter_property 	DEFAULT_M_STOP_COND DISPLAY_NAME "Enable STOP_COND interrupt bit"
set_parameter_property 	DEFAULT_M_STOP_COND TYPE boolean
set_parameter_property 	DEFAULT_M_STOP_COND DESCRIPTION "STOP condition detection. When 1, it indicates a STOP condition is detected when altera_smb is the targeted slave device. When altera_smb is not the targeted slave device, this interrupt is not raised."

add_parameter 			DEFAULT_M_NACK_BY_MST boolean true
set_parameter_property 	DEFAULT_M_NACK_BY_MST DISPLAY_NAME "Enable NACK_BY_MST interrupt bit"
set_parameter_property 	DEFAULT_M_NACK_BY_MST TYPE boolean
set_parameter_property 	DEFAULT_M_NACK_BY_MST DESCRIPTION "NACK by master. When 1, it indicates remote SMBus master device issues a NACK towards transmit data byte sent by altera_smb."

add_parameter 			DEFAULT_M_RX_OVF boolean true
set_parameter_property 	DEFAULT_M_RX_OVF DISPLAY_NAME "Enable RX_OVF interrupt bit"
set_parameter_property 	DEFAULT_M_RX_OVF TYPE boolean
set_parameter_property 	DEFAULT_M_RX_OVF DESCRIPTION "Receive data overflow. When 1, it indicates receive data register is overflow. This condition occurs when altera_smb has received a new data while receive data register is full."

add_parameter 			DEFAULT_M_CLKLOW_TMOUT boolean true
set_parameter_property 	DEFAULT_M_CLKLOW_TMOUT DISPLAY_NAME "Enable CLKLOW_TMOUT interrupt bit"
set_parameter_property 	DEFAULT_M_CLKLOW_TMOUT TYPE boolean
set_parameter_property 	DEFAULT_M_CLKLOW_TMOUT DESCRIPTION "Clock low timeout. When 1, it indicates SMBCLK has been held low for a duration exceeding the period set in SMB_TCLKLOW_TMOUT register."

add_parameter 			DEFAULT_M_PEC_ERR boolean true
set_parameter_property 	DEFAULT_M_PEC_ERR DISPLAY_NAME "Enable PEC_ERR interrupt bit"
set_parameter_property 	DEFAULT_M_PEC_ERR TYPE boolean
set_parameter_property 	DEFAULT_M_PEC_ERR DESCRIPTION "PEC error. This bit exists only when SMB_PEC_EN parameter is 1. If SMB_PEC_EN parameter is 0, this bit is reserved."

add_parameter 			DEFAULT_M_SLV_ADDR_ERR boolean true
set_parameter_property 	DEFAULT_M_SLV_ADDR_ERR DISPLAY_NAME "Enable SLV_ADDR_ERR interrupt bit"
set_parameter_property 	DEFAULT_M_SLV_ADDR_ERR TYPE boolean
set_parameter_property 	DEFAULT_M_SLV_ADDR_ERR DESCRIPTION "Slave address error. This interrupt is raised when the first slave address received by altera_smb after the START condition is matching with altera_smb’s own address but the second slave address received by altera_smb after the repeated START condition does not match with altera_smb’s own address or the read/write bit that comes right after the second slave address indicates a write request. "

add_parameter 			DEFAULT_M_RX_DATA_AVAIL boolean true
set_parameter_property 	DEFAULT_M_RX_DATA_AVAIL DISPLAY_NAME "Enable RX_DATA_AVAIL interrupt bit"
set_parameter_property 	DEFAULT_M_RX_DATA_AVAIL TYPE boolean
set_parameter_property 	DEFAULT_M_RX_DATA_AVAIL DESCRIPTION "Receive data is available. Applicable to SMBus slave receiver. When 1, it indicates receive data register contains SMBus data (either command or data) sent by the remote SMBus master."

add_parameter 			DEFAULT_M_TX_DATA_REQ boolean true
set_parameter_property 	DEFAULT_M_TX_DATA_REQ DISPLAY_NAME "Enable TX_DATA_REQ interrupt bit"
set_parameter_property 	DEFAULT_M_TX_DATA_REQ TYPE boolean
set_parameter_property 	DEFAULT_M_TX_DATA_REQ DESCRIPTION "Transmit data request. Applicable to SMBus slave transmitter. When 1, it indicates remote SMBus master is requesting data from altera_smb. Software or Avalon-MM master peripheral need to provide transmit data by writing data into transmit data register (SMB_TX_DATA). During this read request period, altera_smb holds the SMBCLK line to low until a transmit data is available in the transmit data register."

add_parameter 			SMB_DFLT_IMR STD_LOGIC_VECTOR 255
set_parameter_property  SMB_DFLT_IMR VISIBLE false
set_parameter_property 	SMB_DFLT_IMR DISPLAY_NAME "Default value for Interrupt mask register"
set_parameter_property  SMB_DFLT_IMR WIDTH 8
set_parameter_property  SMB_DFLT_IMR ALLOWED_RANGES 0:255
set_parameter_property 	SMB_DFLT_IMR DERIVED true
set_parameter_property 	SMB_DFLT_IMR HDL_PARAMETER true

add_parameter 			SMB_DFLT_THDDAT STD_LOGIC_VECTOR 30
set_parameter_property 	SMB_DFLT_THDDAT DISPLAY_NAME "Default value for data hold time register"
set_parameter_property  SMB_DFLT_THDDAT WIDTH 16
set_parameter_property 	SMB_DFLT_THDDAT ALLOWED_RANGES 0:65535
set_parameter_property 	SMB_DFLT_THDDAT DESCRIPTION "Determine the default value of SMB_THDDAT register."
set_parameter_property 	SMB_DFLT_THDDAT HDL_PARAMETER true

add_parameter 			SMB_DFLT_TSUDAT STD_LOGIC_VECTOR 25
set_parameter_property 	SMB_DFLT_TSUDAT DISPLAY_NAME "Default value for data setup time register"
set_parameter_property  SMB_DFLT_TSUDAT WIDTH 16
set_parameter_property 	SMB_DFLT_TSUDAT ALLOWED_RANGES 0:65535
set_parameter_property 	SMB_DFLT_TSUDAT DESCRIPTION "Determine the default value of SMB_TSUDAT register."
set_parameter_property 	SMB_DFLT_TSUDAT HDL_PARAMETER true

add_parameter 			SMB_DFLT_TCLKLOW_TMOUT STD_LOGIC_VECTOR 2500000 ""
set_parameter_property 	SMB_DFLT_TCLKLOW_TMOUT DISPLAY_NAME "Default value for clock low timeout register"
set_parameter_property  SMB_DFLT_TCLKLOW_TMOUT WIDTH 32
set_parameter_property 	SMB_DFLT_TCLKLOW_TMOUT ALLOWED_RANGES 0:4294967295
set_parameter_property 	SMB_DFLT_TCLKLOW_TMOUT DESCRIPTION "Determine the default value of SMB_TCLKLOW_TMOUT register."
set_parameter_property 	SMB_DFLT_TCLKLOW_TMOUT HDL_PARAMETER true

add_parameter 			SMB_DFLT_SLV_OA STD_LOGIC_VECTOR 0
set_parameter_property 	SMB_DFLT_SLV_OA DISPLAY_NAME "Default value for slave own address register"
set_parameter_property  SMB_DFLT_SLV_OA WIDTH 7
set_parameter_property 	SMB_DFLT_SLV_OA ALLOWED_RANGES 0:127
set_parameter_property 	SMB_DFLT_SLV_OA DESCRIPTION "Determine the default value of SMB_SLV_OA register."
set_parameter_property 	SMB_DFLT_SLV_OA HDL_PARAMETER true

add_parameter           DEVICE_FAMILY STRING          ""
set_parameter_property  DEVICE_FAMILY SYSTEM_INFO     "DEVICE_FAMILY"
set_parameter_property  DEVICE_FAMILY HDL_PARAMETER   true
set_parameter_property  DEVICE_FAMILY VISIBLE	      	false

add_parameter 			MEMORY_TYPE STRING 		 	"UNUSED"
set_parameter_property 	MEMORY_TYPE DISPLAY_NAME 	"Memory type"
set_parameter_property 	MEMORY_TYPE DISPLAY_HINT 	"Select the memory block type to be used in the FIFO"
set_parameter_property 	MEMORY_TYPE DESCRIPTION 	"Memory type"
set_parameter_property 	MEMORY_TYPE HDL_PARAMETER 	true
set_parameter_property 	MEMORY_TYPE AFFECTS_GENERATION false
set_parameter_property  MEMORY_TYPE ALLOWED_RANGES  {"UNUSED" "RAM_BLOCK_TYPE=MLAB: MLAB" "RAM_BLOCK_TYPE=M512: M512" "RAM_BLOCK_TYPE=M4K: M4K" "RAM_BLOCK_TYPE=MRam: MRam" "RAM_BLOCK_TYPE=M9K: M9K" "RAM_BLOCK_TYPE=M10K: M10K" "RAM_BLOCK_TYPE=M20K: M20K" "RAM_BLOCK_TYPE=M144K: M144K"}

# add system info parameter
add_parameter           deviceFeaturesSystemInfo   STRING 			"None"
set_parameter_property  deviceFeaturesSystemInfo   system_info		"DEVICE_FEATURES"
set_parameter_property  deviceFeaturesSystemInfo   VISIBLE false
# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender smb_intr irq Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port 			avalon_slave addr address Input 4
add_interface_port 			avalon_slave read read Input 1
add_interface_port 			avalon_slave write write Input 1
add_interface_port 			avalon_slave writedata writedata Input 32
add_interface_port 			avalon_slave readdata readdata Output 32
set_interface_assignment 	avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment 	avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment 	avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment 	avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point SMBus_serial
# 
add_interface 			SMBus_serial conduit end
set_interface_property 	SMBus_serial ENABLED true
add_interface_port 		SMBus_serial smb_data_in smb_data_in Input 1
add_interface_port 		SMBus_serial smb_clk_in smb_clk_in Input 1
add_interface_port 		SMBus_serial smb_data_oe smb_data_oe Output 1
add_interface_port 		SMBus_serial smb_clk_oe smb_clk_oe Output 1

#proc elaborate {} {
#
#  set memory_type_param 	 [ get_parameter_value MEMORY_TYPE ]
#
#  if {$memory_type_param == "None"} {
#	send_message Error "Please select a memory block type"
#  }
#}

proc is_enabled {parameter} {
    if {[get_parameter_value $parameter] == "true"} {
		return 1
    } else {
		return 0
    }
}

proc validate {} {
	set supported_ram_type  [ proc_get_supported_ram_type ]
	set_parameter_property  MEMORY_TYPE         "ALLOWED_RANGES"  $supported_ram_type
	set smb_dflt_imr_value   0

        if { [is_enabled DEFAULT_M_STOP_COND] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 128}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]

        if { [is_enabled DEFAULT_M_NACK_BY_MST] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 64}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]

	if { [is_enabled DEFAULT_M_RX_OVF] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 32}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]
	
	if { [is_enabled DEFAULT_M_CLKLOW_TMOUT] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 16}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]
	
	if { [is_enabled DEFAULT_M_PEC_ERR] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 8}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]
	
	if { [is_enabled DEFAULT_M_SLV_ADDR_ERR] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 4}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]
	
	if { [is_enabled DEFAULT_M_RX_DATA_AVAIL] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 2}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]
	
	if { [is_enabled DEFAULT_M_TX_DATA_REQ] } {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 1}];
	} else {
		set_parameter_value		SMB_DFLT_IMR		[expr {$smb_dflt_imr_value + 0}];
	}
	set smb_dflt_imr_value   [ get_parameter_value SMB_DFLT_IMR ]
}

proc proc_get_supported_ram_type {} {
    set supported_ram_type_system_info [list]
    array set feature_array  [get_parameter_value deviceFeaturesSystemInfo]
    foreach one_feature [array names feature_array] {
        if { [ string match "*_MEMORY*" "$one_feature" ] } {
            if { $feature_array($one_feature) } {
                lappend supported_ram_type_system_info "$one_feature"
            }
        }
    }
    set supported_ram_type [list]
    foreach ram_type $supported_ram_type_system_info {
        switch $ram_type {
            "M4K_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=M4K: M4K"
            }
            "M9K_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=M9K: M9K"
            }
            "M10K_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=M10K: M10K"
            }
            "M20K_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=M20K: M20K"
            }
            "M144K_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=M144K: M144K"
            }
            "MRAM_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=MRam: MRam"
            }
            "MLAB_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=MLAB: MLAB"
            }
            "M512_MEMORY" {
                lappend supported_ram_type "RAM_BLOCK_TYPE=M512: M512"
            }
            default {
                # Should never enter this function
                send_message error "$ram_type is not a valid ram type"
            }

        }
    }
	lappend supported_ram_type "UNUSED"	
    return "$supported_ram_type"
}
