# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 16.1
# Tue Jun 21 01:24:24 MYT 2016
# DO NOT MODIFY


# 
# altera_asmi2_csr_controller "Altera ASMI2 CSR Controller" v1.0
#  2016.06.21.01:24:24
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0
package require -exact altera_terp 1.0

# 
# module altera_asmi2_csr_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_asmi2_csr_controller
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Configuration and Programming"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Altera ASMI2 CSR Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK    elaboration

# 
# file sets
# 
add_fileset synth_fileset QUARTUS_SYNTH synth_callback_procedure
add_fileset synthver_fileset SIM_VERILOG synth_callback_procedure
add_fileset synthvhd_fileset SIM_VHDL synth_callback_procedure


# 
# parameters
# 
#----------------------------------------------------------------------
add_parameter COM_ID STRING_LIST 1
set_parameter_property COM_ID DISPLAY_NAME {No}
set_parameter_property COM_ID AFFECTS_ELABORATION true
set_parameter_property COM_ID AFFECTS_GENERATION true
set_parameter_property COM_ID HDL_PARAMETER false
set_parameter_property COM_ID DERIVED false
set_parameter_property COM_ID GROUP "Common_table"
set_parameter_property COM_ID DESCRIPTION {List of IDs}

add_parameter COM_OPERATION STRING_LIST "01"
set_parameter_property COM_OPERATION DISPLAY_NAME {Operation} 
set_parameter_property COM_OPERATION AFFECTS_ELABORATION true
set_parameter_property COM_OPERATION AFFECTS_GENERATION true
set_parameter_property COM_OPERATION HDL_PARAMETER false
set_parameter_property COM_OPERATION DERIVED false
set_parameter_property COM_OPERATION GROUP "Common_table"
set_parameter_property COM_OPERATION DESCRIPTION {List of channel IDs}

add_parameter COM_OPCODE STRING_LIST 0
set_parameter_property COM_OPCODE DISPLAY_NAME {Opcode}
set_parameter_property COM_OPCODE AFFECTS_ELABORATION true
set_parameter_property COM_OPCODE AFFECTS_GENERATION true
set_parameter_property COM_OPCODE HDL_PARAMETER false
set_parameter_property COM_OPCODE DERIVED false
set_parameter_property COM_OPCODE GROUP "Common_table"
set_parameter_property COM_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property COM_OPCODE DESCRIPTION {List of opcode}

add_parameter COM_ADDR_BYTES STRING_LIST 0
set_parameter_property COM_ADDR_BYTES DISPLAY_NAME {Address bytes}
set_parameter_property COM_ADDR_BYTES AFFECTS_ELABORATION true
set_parameter_property COM_ADDR_BYTES AFFECTS_GENERATION true
set_parameter_property COM_ADDR_BYTES HDL_PARAMETER false
set_parameter_property COM_ADDR_BYTES DERIVED false
set_parameter_property COM_ADDR_BYTES GROUP "Common_table"
set_parameter_property COM_ADDR_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property COM_ADDR_BYTES DESCRIPTION {List of address bytes}

add_parameter COM_DATA_IN_BYTES STRING_LIST 0
set_parameter_property COM_DATA_IN_BYTES DISPLAY_NAME {Data in bytes}
set_parameter_property COM_DATA_IN_BYTES AFFECTS_ELABORATION true
set_parameter_property COM_DATA_IN_BYTES AFFECTS_GENERATION true
set_parameter_property COM_DATA_IN_BYTES HDL_PARAMETER false
set_parameter_property COM_DATA_IN_BYTES DERIVED false
set_parameter_property COM_DATA_IN_BYTES GROUP "Common_table"
set_parameter_property COM_DATA_IN_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property COM_DATA_IN_BYTES DESCRIPTION {List of data bytes}

add_parameter COM_DATA_OUT_BYTES STRING_LIST 0
set_parameter_property COM_DATA_OUT_BYTES DISPLAY_NAME {Data out bytes}
set_parameter_property COM_DATA_OUT_BYTES AFFECTS_ELABORATION true
set_parameter_property COM_DATA_OUT_BYTES AFFECTS_GENERATION true
set_parameter_property COM_DATA_OUT_BYTES HDL_PARAMETER false
set_parameter_property COM_DATA_OUT_BYTES DERIVED false
set_parameter_property COM_DATA_OUT_BYTES GROUP "Common_table"
set_parameter_property COM_DATA_OUT_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property COM_DATA_OUT_BYTES DESCRIPTION {List of data bytes}


add_parameter COM_DUMMY_BYTES STRING_LIST 0
set_parameter_property COM_DUMMY_BYTES DISPLAY_NAME {Dummy bytes}
set_parameter_property COM_DUMMY_BYTES AFFECTS_ELABORATION true
set_parameter_property COM_DUMMY_BYTES AFFECTS_GENERATION true
set_parameter_property COM_DUMMY_BYTES HDL_PARAMETER false
set_parameter_property COM_DUMMY_BYTES DERIVED false
set_parameter_property COM_DUMMY_BYTES GROUP "Common_table"
set_parameter_property COM_DUMMY_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property COM_DUMMY_BYTES DESCRIPTION {List of dummy bytes}

add_parameter MISC_ID STRING_LIST 1
set_parameter_property MISC_ID DISPLAY_NAME {No}
set_parameter_property MISC_ID AFFECTS_ELABORATION true
set_parameter_property MISC_ID AFFECTS_GENERATION true
set_parameter_property MISC_ID HDL_PARAMETER false
set_parameter_property MISC_ID DERIVED false
set_parameter_property MISC_ID GROUP "Miscellaneous_table"
set_parameter_property MISC_ID DESCRIPTION {List of IDs}

add_parameter MISC_OPERATION STRING_LIST "01"
set_parameter_property MISC_OPERATION DISPLAY_NAME {Operation} 
set_parameter_property MISC_OPERATION AFFECTS_ELABORATION true
set_parameter_property MISC_OPERATION AFFECTS_GENERATION true
set_parameter_property MISC_OPERATION HDL_PARAMETER false
set_parameter_property MISC_OPERATION DERIVED false
set_parameter_property MISC_OPERATION GROUP "Miscellaneous_table"
set_parameter_property MISC_OPERATION DESCRIPTION {List of channel IDs}

add_parameter MISC_OPCODE STRING_LIST 0
set_parameter_property MISC_OPCODE DISPLAY_NAME {Opcode}
set_parameter_property MISC_OPCODE AFFECTS_ELABORATION true
set_parameter_property MISC_OPCODE AFFECTS_GENERATION true
set_parameter_property MISC_OPCODE HDL_PARAMETER false
set_parameter_property MISC_OPCODE DERIVED false
set_parameter_property MISC_OPCODE GROUP "Miscellaneous_table"
set_parameter_property MISC_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property MISC_OPCODE DESCRIPTION {List of opcode}


add_parameter MISC_ADDR_BYTES STRING_LIST 0
set_parameter_property MISC_ADDR_BYTES DISPLAY_NAME {Address bytes}
set_parameter_property MISC_ADDR_BYTES AFFECTS_ELABORATION true
set_parameter_property MISC_ADDR_BYTES AFFECTS_GENERATION true
set_parameter_property MISC_ADDR_BYTES HDL_PARAMETER false
set_parameter_property MISC_ADDR_BYTES DERIVED false
set_parameter_property MISC_ADDR_BYTES GROUP "Miscellaneous_table"
set_parameter_property MISC_ADDR_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property MISC_ADDR_BYTES DESCRIPTION {List of address bytes}

add_parameter MISC_DATA_IN_BYTES STRING_LIST 0
set_parameter_property MISC_DATA_IN_BYTES DISPLAY_NAME {Data in bytes}
set_parameter_property MISC_DATA_IN_BYTES AFFECTS_ELABORATION true
set_parameter_property MISC_DATA_IN_BYTES AFFECTS_GENERATION true
set_parameter_property MISC_DATA_IN_BYTES HDL_PARAMETER false
set_parameter_property MISC_DATA_IN_BYTES DERIVED false
set_parameter_property MISC_DATA_IN_BYTES GROUP "Miscellaneous_table"
set_parameter_property MISC_DATA_IN_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property MISC_DATA_IN_BYTES DESCRIPTION {List of data bytes}

add_parameter MISC_DATA_OUT_BYTES STRING_LIST 0
set_parameter_property MISC_DATA_OUT_BYTES DISPLAY_NAME {Data out bytes}
set_parameter_property MISC_DATA_OUT_BYTES AFFECTS_ELABORATION true
set_parameter_property MISC_DATA_OUT_BYTES AFFECTS_GENERATION true
set_parameter_property MISC_DATA_OUT_BYTES HDL_PARAMETER false
set_parameter_property MISC_DATA_OUT_BYTES DERIVED false
set_parameter_property MISC_DATA_OUT_BYTES GROUP "Miscellaneous_table"
set_parameter_property MISC_DATA_OUT_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property MISC_DATA_OUT_BYTES DESCRIPTION {List of data bytes}

add_parameter MISC_DUMMY_BYTES STRING_LIST 0
set_parameter_property MISC_DUMMY_BYTES DISPLAY_NAME {Dummy bytes}
set_parameter_property MISC_DUMMY_BYTES AFFECTS_ELABORATION true
set_parameter_property MISC_DUMMY_BYTES AFFECTS_GENERATION true
set_parameter_property MISC_DUMMY_BYTES HDL_PARAMETER false
set_parameter_property MISC_DUMMY_BYTES DERIVED false
set_parameter_property MISC_DUMMY_BYTES GROUP "Miscellaneous_table"
set_parameter_property MISC_DUMMY_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property MISC_DUMMY_BYTES DESCRIPTION {List of dummy bytes}

#----------------------------------------------------------------------

#----------------------------------------------------------------------
add_parameter WR_ID STRING_LIST 1
set_parameter_property WR_ID DISPLAY_NAME {No}
set_parameter_property WR_ID AFFECTS_ELABORATION true
set_parameter_property WR_ID AFFECTS_GENERATION true
set_parameter_property WR_ID HDL_PARAMETER false
set_parameter_property WR_ID DERIVED false
#set_parameter_property WR_ID GROUP "Write_Table"
set_parameter_property WR_ID DESCRIPTION {List of IDs}

add_parameter WR_OPERATION STRING_LIST "01"
set_parameter_property WR_OPERATION DISPLAY_NAME {Operation} 
set_parameter_property WR_OPERATION AFFECTS_ELABORATION true
set_parameter_property WR_OPERATION AFFECTS_GENERATION true
set_parameter_property WR_OPERATION HDL_PARAMETER false
set_parameter_property WR_OPERATION DERIVED false
#set_parameter_property WR_OPERATION GROUP "Write_Table"
set_parameter_property WR_OPERATION DESCRIPTION {List of channel IDs}

add_parameter WR_OPCODE STRING_LIST 0
set_parameter_property WR_OPCODE DISPLAY_NAME {Opcode}
set_parameter_property WR_OPCODE AFFECTS_ELABORATION true
set_parameter_property WR_OPCODE AFFECTS_GENERATION true
set_parameter_property WR_OPCODE HDL_PARAMETER false
set_parameter_property WR_OPCODE DERIVED false
#set_parameter_property WR_OPCODE GROUP "Write_Table"
set_parameter_property WR_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property WR_OPCODE DESCRIPTION {List of opcode}

add_parameter WR_ENABLE INTEGER_LIST 0
set_parameter_property WR_ENABLE DISPLAY_NAME {Enable}
set_parameter_property WR_ENABLE AFFECTS_ELABORATION true
set_parameter_property WR_ENABLE AFFECTS_GENERATION true
set_parameter_property WR_ENABLE HDL_PARAMETER false
set_parameter_property WR_ENABLE DERIVED false
#set_parameter_property WR_ENABLE GROUP "Write_Table"
set_parameter_property WR_ENABLE DISPLAY_HINT "boolean"
set_parameter_property WR_ENABLE ALLOWED_RANGES {"0" "1"}
set_parameter_property WR_ENABLE DESCRIPTION {List of Enable}

add_parameter WR_DUMMY_BYTES STRING_LIST 0
set_parameter_property WR_DUMMY_BYTES DISPLAY_NAME {Dummy bytes}
set_parameter_property WR_DUMMY_BYTES AFFECTS_ELABORATION true
set_parameter_property WR_DUMMY_BYTES AFFECTS_GENERATION true
set_parameter_property WR_DUMMY_BYTES HDL_PARAMETER false
set_parameter_property WR_DUMMY_BYTES DERIVED false
set_parameter_property WR_DUMMY_BYTES GROUP "Read_Table"
set_parameter_property WR_DUMMY_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property WR_DUMMY_BYTES DESCRIPTION {List of dummy bytes}

add_parameter WR_ADDR_BYTES STRING_LIST 0
set_parameter_property WR_ADDR_BYTES DISPLAY_NAME {Address bytes}
set_parameter_property WR_ADDR_BYTES AFFECTS_ELABORATION true
set_parameter_property WR_ADDR_BYTES AFFECTS_GENERATION true
set_parameter_property WR_ADDR_BYTES HDL_PARAMETER false
set_parameter_property WR_ADDR_BYTES DERIVED false
set_parameter_property WR_ADDR_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property WR_ADDR_BYTES DESCRIPTION {List of address bytes}


add_display_item "Write_Table" WR_ID parameter
add_display_item "Write_Table" WR_OPERATION parameter
add_display_item "Write_Table" WR_OPCODE parameter
add_display_item "Write_Table" WR_ADDR_BYTES parameter
add_display_item "Write_Table" WR_DUMMY_BYTES parameter
add_display_item "Write_Table" WR_ENABLE parameter

#----------------------------------------------------------------------

#----------------------------------------------------------------------
add_parameter RD_ID STRING_LIST 1
set_parameter_property RD_ID DISPLAY_NAME {No}
set_parameter_property RD_ID AFFECTS_ELABORATION true
set_parameter_property RD_ID AFFECTS_GENERATION true
set_parameter_property RD_ID HDL_PARAMETER false
set_parameter_property RD_ID DERIVED false
set_parameter_property RD_ID GROUP "Read_Table"
set_parameter_property RD_ID DESCRIPTION {List of IDs}

add_parameter RD_OPERATION STRING_LIST "01"
set_parameter_property RD_OPERATION DISPLAY_NAME {Operation} 
set_parameter_property RD_OPERATION AFFECTS_ELABORATION true
set_parameter_property RD_OPERATION AFFECTS_GENERATION true
set_parameter_property RD_OPERATION HDL_PARAMETER false
set_parameter_property RD_OPERATION DERIVED false
set_parameter_property RD_OPERATION GROUP "Read_Table"
set_parameter_property RD_OPERATION DESCRIPTION {List of channel IDs}

add_parameter RD_OPCODE STRING_LIST 0
set_parameter_property RD_OPCODE DISPLAY_NAME {Opcode}
set_parameter_property RD_OPCODE AFFECTS_ELABORATION true
set_parameter_property RD_OPCODE AFFECTS_GENERATION true
set_parameter_property RD_OPCODE HDL_PARAMETER false
set_parameter_property RD_OPCODE DERIVED false
set_parameter_property RD_OPCODE GROUP "Read_Table"
set_parameter_property RD_OPCODE DISPLAY_HINT "hexadecimal"
set_parameter_property RD_OPCODE DESCRIPTION {List of opcode}

add_parameter RD_ADDR_BYTES STRING_LIST 0
set_parameter_property RD_ADDR_BYTES DISPLAY_NAME {Address bytes}
set_parameter_property RD_ADDR_BYTES AFFECTS_ELABORATION true
set_parameter_property RD_ADDR_BYTES AFFECTS_GENERATION true
set_parameter_property RD_ADDR_BYTES HDL_PARAMETER false
set_parameter_property RD_ADDR_BYTES DERIVED false
set_parameter_property RD_ADDR_BYTES GROUP "Read_Table"
set_parameter_property RD_ADDR_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property RD_ADDR_BYTES DESCRIPTION {List of address bytes}

add_parameter RD_DUMMY_BYTES STRING_LIST 0
set_parameter_property RD_DUMMY_BYTES DISPLAY_NAME {Dummy bytes}
set_parameter_property RD_DUMMY_BYTES AFFECTS_ELABORATION true
set_parameter_property RD_DUMMY_BYTES AFFECTS_GENERATION true
set_parameter_property RD_DUMMY_BYTES HDL_PARAMETER false
set_parameter_property RD_DUMMY_BYTES DERIVED false
set_parameter_property RD_DUMMY_BYTES GROUP "Read_Table"
set_parameter_property RD_DUMMY_BYTES DISPLAY_HINT "hexadecimal"
set_parameter_property RD_DUMMY_BYTES DESCRIPTION {List of dummy bytes}

add_parameter RD_ENABLE INTEGER_LIST 0
set_parameter_property RD_ENABLE DISPLAY_NAME {Enable}
set_parameter_property RD_ENABLE AFFECTS_ELABORATION true
set_parameter_property RD_ENABLE AFFECTS_GENERATION true
set_parameter_property RD_ENABLE HDL_PARAMETER false
set_parameter_property RD_ENABLE DERIVED false
set_parameter_property RD_ENABLE GROUP "Read_Table"
set_parameter_property RD_ENABLE DISPLAY_HINT "boolean"
set_parameter_property RD_ENABLE ALLOWED_RANGES {"0" "1"}
set_parameter_property RD_ENABLE DESCRIPTION {List of Enable}

add_parameter OP_INFO STRING "" 0
set_parameter_property OP_INFO UNITS None
set_parameter_property OP_INFO AFFECTS_ELABORATION true
set_parameter_property OP_INFO AFFECTS_GENERATION true
set_parameter_property OP_INFO VISIBLE false
set_parameter_property OP_INFO DERIVED true


# HIde these
add_parameter EXTRA_EN STRING 0
set_parameter_property EXTRA_EN DISPLAY_NAME {Extra EN}
set_parameter_property EXTRA_EN AFFECTS_ELABORATION true
set_parameter_property EXTRA_EN AFFECTS_GENERATION true
set_parameter_property EXTRA_EN HDL_PARAMETER false
set_parameter_property EXTRA_EN DERIVED false
set_parameter_property EXTRA_EN DESCRIPTION {List of IDs}

add_parameter EXTRA_ID STRING_LIST 1
set_parameter_property EXTRA_ID DISPLAY_NAME {Extra ID}
set_parameter_property EXTRA_ID AFFECTS_ELABORATION true
set_parameter_property EXTRA_ID AFFECTS_GENERATION true
set_parameter_property EXTRA_ID HDL_PARAMETER false
set_parameter_property EXTRA_ID DERIVED false
set_parameter_property EXTRA_ID DESCRIPTION {List of IDs}

add_parameter EXTRA_OPERATION STRING_LIST "01"
set_parameter_property EXTRA_OPERATION DISPLAY_NAME {Extra Operation} 
set_parameter_property EXTRA_OPERATION AFFECTS_ELABORATION true
set_parameter_property EXTRA_OPERATION AFFECTS_GENERATION true
set_parameter_property EXTRA_OPERATION HDL_PARAMETER false
set_parameter_property EXTRA_OPERATION DERIVED false
set_parameter_property EXTRA_OPERATION DESCRIPTION {List of channel IDs}

# Show chip select conduit
add_parameter           CHIP_SELECT_EN  BOOLEAN             true
set_parameter_property  CHIP_SELECT_EN  AFFECTS_GENERATION  true
set_parameter_property  CHIP_SELECT_EN  AFFECTS_ELABORATION true
set_parameter_property  CHIP_SELECT_EN  VISIBLE             true

# 
# display items
# 
add_display_item "" "Settings" GROUP tab
add_display_item "Settings" "Common Operations"   GROUP
add_display_item "Settings" "Miscellaneous Operations"   GROUP
add_display_item "Settings" "Write Operations"   GROUP
add_display_item "Settings" "Read Operations"   GROUP
add_display_item "Common Operations" "Common_table" GROUP TABLE
add_display_item "Miscellaneous Operations" "Miscellaneous_table" GROUP TABLE
add_display_item "Write Operations" "Write_Table" GROUP TABLE
add_display_item "Read Operations" "Read_Table" GROUP TABLE
set_display_item_property "Common_table" DISPLAY_HINT {table rows:10}
set_display_item_property "Miscellaneous_table" DISPLAY_HINT {table rows:13}
set_display_item_property "Write_Table" DISPLAY_HINT {table rows:4}
set_display_item_property "Read_Table" DISPLAY_HINT {table rows:4}
# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clk
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 1
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_addr address Input 6
add_interface_port csr csr_rd read Input 1
add_interface_port csr csr_rddata readdata Output 32
add_interface_port csr csr_wr write Input 1
add_interface_port csr csr_wrdata writedata Input 32
add_interface_port csr csr_waitrequest waitrequest Output 1
add_interface_port csr csr_rddatavalid readdatavalid Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point cmd_pck
# 
add_interface cmd_pck avalon_streaming start
set_interface_property cmd_pck associatedClock clk
set_interface_property cmd_pck associatedReset reset
set_interface_property cmd_pck dataBitsPerSymbol 32
set_interface_property cmd_pck errorDescriptor ""
set_interface_property cmd_pck firstSymbolInHighOrderBits true
set_interface_property cmd_pck maxChannel 0
set_interface_property cmd_pck readyLatency 0
set_interface_property cmd_pck ENABLED true
set_interface_property cmd_pck EXPORT_OF ""
set_interface_property cmd_pck PORT_NAME_MAP ""
set_interface_property cmd_pck CMSIS_SVD_VARIABLES ""
set_interface_property cmd_pck SVD_ADDRESS_GROUP ""

add_interface_port cmd_pck cmd_channel channel Output 2
add_interface_port cmd_pck cmd_eop endofpacket Output 1
add_interface_port cmd_pck cmd_ready ready Input 1
add_interface_port cmd_pck cmd_sop startofpacket Output 1
add_interface_port cmd_pck cmd_data data Output 32
add_interface_port cmd_pck cmd_valid valid Output 1


# 
# connection point rsp_pck
# 
add_interface rsp_pck avalon_streaming end
set_interface_property rsp_pck associatedClock clk
set_interface_property rsp_pck associatedReset reset
set_interface_property rsp_pck dataBitsPerSymbol 32
set_interface_property rsp_pck errorDescriptor ""
set_interface_property rsp_pck firstSymbolInHighOrderBits true
set_interface_property rsp_pck maxChannel 0
set_interface_property rsp_pck readyLatency 0
set_interface_property rsp_pck ENABLED true
set_interface_property rsp_pck EXPORT_OF ""
set_interface_property rsp_pck PORT_NAME_MAP ""
set_interface_property rsp_pck CMSIS_SVD_VARIABLES ""
set_interface_property rsp_pck SVD_ADDRESS_GROUP ""

add_interface_port rsp_pck rsp_channel channel Input 2
add_interface_port rsp_pck rsp_data data Input 32
add_interface_port rsp_pck rsp_eop endofpacket Input 1
add_interface_port rsp_pck rsp_ready ready Output 1
add_interface_port rsp_pck rsp_sop startofpacket Input 1
add_interface_port rsp_pck rsp_valid valid Input 1


# 
# connection point csr_addr
# 
add_interface addr_bytes_csr conduit end
set_interface_property addr_bytes_csr associatedClock clk
set_interface_property addr_bytes_csr associatedReset ""
set_interface_property addr_bytes_csr ENABLED true
set_interface_property addr_bytes_csr EXPORT_OF ""
set_interface_property addr_bytes_csr PORT_NAME_MAP ""
set_interface_property addr_bytes_csr CMSIS_SVD_VARIABLES ""
set_interface_property addr_bytes_csr SVD_ADDRESS_GROUP ""

add_interface_port addr_bytes_csr addr_bytes_csr addr_bytes_csr Output 32

# 
# connection point enable
# 
add_interface qspi_interface_en conduit end
set_interface_property qspi_interface_en associatedClock clk
set_interface_property qspi_interface_en associatedReset ""
set_interface_property qspi_interface_en ENABLED true
set_interface_property qspi_interface_en EXPORT_OF ""
set_interface_property qspi_interface_en PORT_NAME_MAP ""
set_interface_property qspi_interface_en CMSIS_SVD_VARIABLES ""
set_interface_property qspi_interface_en SVD_ADDRESS_GROUP ""

add_interface_port qspi_interface_en qspi_interface_en qspi_interface_en Output 1

proc elaboration {}     {
	set enable_chip_select [get_parameter_value CHIP_SELECT_EN]
    
    if { $enable_chip_select } {
        add_interface chip_select conduit end
        set_interface_property chip_select associatedClock clk
        set_interface_property chip_select associatedReset ""
        set_interface_property chip_select ENABLED true
        set_interface_property chip_select EXPORT_OF ""
        set_interface_property chip_select PORT_NAME_MAP ""
        set_interface_property chip_select CMSIS_SVD_VARIABLES ""
        set_interface_property chip_select SVD_ADDRESS_GROUP ""
        
        add_interface_port chip_select chip_select chip_select  Output  4
    }

    set common_op_offset            [get_parameter_value COM_ID]
    set common_op_name              [get_parameter_value COM_OPERATION]
    set common_op_opcode            [get_parameter_value COM_OPCODE]
    set common_op_addr_bytes        [get_parameter_value COM_ADDR_BYTES]
    set common_op_data_in_bytes     [get_parameter_value COM_DATA_IN_BYTES]
    set common_op_data_out_bytes    [get_parameter_value COM_DATA_OUT_BYTES]
    set common_op_dummy_bytes       [get_parameter_value COM_DUMMY_BYTES]

    # 6, 7, 8 are offset for ISR, IER, Chip select, add them here to make the offset continuos
    set reserved_op_offset            {6  7  8  9  10 11 12}
    set reserved_op_name              {isr ier chip_select status NA NA NA}
    set reserved_op_opcode            {00 00 00 00 00 00 00}
    set reserved_op_addr_bytes        {0  0  0  0  0  0  0}
    set reserved_op_data_in_bytes     {0  0  0  0  0  0  0}
    set reserved_op_data_out_bytes    {0  0  0  0  0  0  0}
    set reserved_op_dummy_bytes       {0  0  0  0  0  0  0}


    set misc_op_offset          [get_parameter_value MISC_ID]
    set misc_op_name            [get_parameter_value MISC_OPERATION]
    set misc_op_opcode          [get_parameter_value MISC_OPCODE]
    set misc_op_addr_bytes      [get_parameter_value MISC_ADDR_BYTES]
    set misc_op_data_in_bytes   [get_parameter_value MISC_DATA_IN_BYTES]
    set misc_op_data_out_bytes  [get_parameter_value MISC_DATA_OUT_BYTES]
    set misc_op_dummy_bytes     [get_parameter_value MISC_DUMMY_BYTES]

    # Common operation only use 9 offset, addpend with the reserved to make it continues
    set concat_op_offset         [concat $common_op_offset         $reserved_op_offset]
    set concat_op_name           [concat $common_op_name           $reserved_op_name]
    set concat_op_opcode         [concat $common_op_opcode         $reserved_op_opcode]
    set concat_op_addr_bytes     [concat $common_op_addr_bytes     $reserved_op_addr_bytes]
    set concat_op_data_in_bytes  [concat $common_op_data_in_bytes  $reserved_op_data_in_bytes]
    set concat_op_data_out_bytes [concat $common_op_data_out_bytes $reserved_op_data_out_bytes]
    set concat_op_dummy_bytes    [concat $common_op_dummy_bytes    $reserved_op_dummy_bytes]

    # Concat all to make a full list of all operation support
    set op_offset         [concat $concat_op_offset         $misc_op_offset]
    set op_name           [concat $concat_op_name           $misc_op_name]
    set op_opcode         [concat $concat_op_opcode         $misc_op_opcode]
    set op_addr_bytes     [concat $concat_op_addr_bytes     $misc_op_addr_bytes]
    set op_data_in_bytes  [concat $concat_op_data_in_bytes  $misc_op_data_in_bytes]
    set op_data_out_bytes [concat $concat_op_data_out_bytes $misc_op_data_out_bytes]
    set op_dummy_bytes    [concat $concat_op_dummy_bytes    $misc_op_dummy_bytes]


#    send_message {info text} "common_op_offset :            $common_op_offset"
#    send_message {info text} "common_op_name :              $common_op_name"
#    send_message {info text} "common_op_opcode :            $common_op_opcode"
#    send_message {info text} "common_op_addr_bytes :        $common_op_addr_bytes"
#    send_message {info text} "common_op_data_in_bytes :     $common_op_data_in_bytes"
#    send_message {info text} "common_op_data_out_bytes :    $common_op_data_out_bytes"
#    send_message {info text} "common_op_dummy_bytes :       $common_op_dummy_bytes"
#
#    send_message {info text} "reserved_op_offset :            $reserved_op_offset"
#    send_message {info text} "reserved_op_name :              $reserved_op_name"
#    send_message {info text} "reserved_op_opcode :            $reserved_op_opcode"
#    send_message {info text} "reserved_op_addr_bytes :        $reserved_op_addr_bytes"
#    send_message {info text} "reserved_op_data_in_bytes :     $reserved_op_data_in_bytes"
#    send_message {info text} "reserved_op_data_out_bytes :    $reserved_op_data_out_bytes"
#    send_message {info text} "reserved_op_dummy_bytes :       $reserved_op_dummy_bytes"
#
#    send_message {info text} "misc_op_offset :              $misc_op_offset"
#    send_message {info text} "misc_op_name :                $misc_op_name"
#    send_message {info text} "misc_op_opcode :              $misc_op_opcode"
#    send_message {info text} "misc_op_addr_bytes :          $misc_op_addr_bytes"
#    send_message {info text} "misc_op_data_in_bytes :       $misc_op_data_in_bytes"
#    send_message {info text} "misc_op_data_out_bytes :      $misc_op_data_out_bytes"
#    send_message {info text} "misc_op_dummy_bytes :         $misc_op_dummy_bytes"
#
#    send_message {info text} "op_offset :              $op_offset"
#    send_message {info text} "op_name :                $op_name"
#    send_message {info text} "op_opcode :              $op_opcode"
#    send_message {info text} "op_addr_bytes :          $op_addr_bytes"
#    send_message {info text} "op_data_in_bytes :       $op_data_in_bytes"
#    send_message {info text} "op_data_out_bytes :      $op_data_out_bytes"
#    send_message {info text} "op_dummy_bytes :         $op_dummy_bytes"



    set numb_common_op [llength $common_op_offset]
    set numb_misc_op [llength $misc_op_offset]
    set numb_op [llength $op_offset]
    #send_message {info text} "numb :        $numb_common_op"
    #send_message {info text} "name  :       [lindex $common_op_name 2]"
    #send_message {info text} "dec2bin  :        [dec2bin 256 2]"
    #set header ""
    #set header_full ""
    # Construct the information for each operation, (header)
    set op_info ""
    for { set i 0 } { $i < $numb_op } { incr i } {
        set opcode_hex      [lindex $op_opcode $i]
        set name            [lindex $op_name $i]
        set addr_bytes      [lindex $op_addr_bytes $i]
        set data_in_bytes   [lindex $op_data_in_bytes $i]
        set data_out_bytes  [lindex $op_data_out_bytes $i]
        set dummy_bytes     [lindex $op_dummy_bytes $i]
        #send_message {info text} "name of offset :        $name"

        binary scan [binary format H* $opcode_hex] B* opcode_bin
        #send_message {info text} "hex :        $opcode_hex"
        #send_message {info text} "bin :        $opcode_bin"
        set opcode $opcode_bin
        if {$addr_bytes eq 0} {
            set has_addr 0  
        } else {
            set has_addr 1  
        }
        if {$addr_bytes eq 4} {
            set 4bytes_addr 1   
        } else {
            set 4bytes_addr 0   
        }
        if {$data_in_bytes eq 0} {
            set has_data_in 0   
        } else {
            set has_data_in 1   
        }
        if {$data_out_bytes eq 0} {
            set has_data_out 0  
        } else {
            set has_data_out 1
        }
        if {$dummy_bytes eq 0} {
            set has_dummy 0 
        } else {
            set has_dummy 1 
        }
        # one operation either has data in (write) or data out (read)
        if {$has_data_in eq 0} {
            if {$has_data_out eq 1} {
                set data_bytes $data_out_bytes
            } else {
                set data_bytes 0
            }
        } else {
            if {$has_data_out eq 0} {
                set data_bytes $data_in_bytes
            } else {
                set data_bytes 0
            }
        }
        # convert data_bytes to binary
        set data_bytes_bin  [dec2bin $data_bytes 9]
        #set dummy_bytes_bin  [dec2bin $dummy_bytes 4]
        set dummy_bytes_bin  [dec2bin $dummy_bytes 5]
        #send_message {info text} "header data_bytes_bin :      $data_bytes_bin"
        #set reserved_bits   [dec2bin 0 6]
        set reserved_bits   [dec2bin 0 5]

       # send_message {info text} "header opcode :           $opcode_bin"
       # send_message {info text} "header has_addr :         $has_addr"
        #send_message {info text} "header has_data_in :      $has_data_in"
       # send_message {info text} "header has_data_out :     $has_data_out"
       # send_message {info text} "header has_dummy :        $has_dummy"
        set header  32'b$reserved_bits$data_bytes_bin$dummy_bytes_bin$has_dummy$has_data_out$has_data_in$4bytes_addr$has_addr$opcode_bin

        if { ! [ string equal "" $op_info ] } {
        set op_info "$op_info,${name}:${header}"
        } else {
        set op_info "${name}:${header}"
        }
    }
   # send_message {info text} "op_info  :        $op_info"
    set_parameter_value OP_INFO $op_info
}


proc synth_callback_procedure { output_name } {
    set this_dir      [ get_module_property MODULE_DIRECTORY ]
    set template_file [ file join $this_dir "altera_asmi2_csr_controller.sv.terp" ]

    set template_fh [ open $template_file r ]
    set template    [ read $template_fh ]
    close $template_fh

    set common_op_offset            [get_parameter_value COM_ID]
    set common_op_name              [get_parameter_value COM_OPERATION]
    set common_op_opcode            [get_parameter_value COM_OPCODE]
    set common_op_addr_bytes        [get_parameter_value COM_ADDR_BYTES]
    set common_op_data_in_bytes     [get_parameter_value COM_DATA_IN_BYTES]
    set common_op_data_out_bytes    [get_parameter_value COM_DATA_OUT_BYTES]
    set common_op_dummy_bytes       [get_parameter_value COM_DUMMY_BYTES]

    set misc_op_offset          [get_parameter_value MISC_ID]
    set misc_op_name            [get_parameter_value MISC_OPERATION]
    set misc_op_opcode          [get_parameter_value MISC_OPCODE]
    set misc_op_addr_bytes      [get_parameter_value MISC_ADDR_BYTES]
    set misc_op_data_in_bytes   [get_parameter_value MISC_DATA_IN_BYTES]
    set misc_op_data_out_bytes  [get_parameter_value MISC_DATA_OUT_BYTES]
    set misc_op_dummy_bytes     [get_parameter_value MISC_DUMMY_BYTES]
    set op_info                 [get_parameter_value OP_INFO]

    # Rea those extra operations if it support
    set extra_op_en       [get_parameter_value EXTRA_EN] 
    set extra_op_offset   [get_parameter_value EXTRA_ID]
    set extra_op_name     [get_parameter_value EXTRA_OPERATION]
    set enable_chip_select [get_parameter_value CHIP_SELECT_EN]

    set params(output_name)                 $output_name
    set params(op_info)                     $op_info
    set params(numb_common_op)              5
    set params(common_op_offset)            $common_op_offset
    set params(common_op_name)              $common_op_name
    set params(common_op_opcode)            $common_op_opcode
    set params(common_op_addr_bytes)        $common_op_addr_bytes
    set params(common_op_data_in_bytes)     $common_op_data_in_bytes
    set params(common_op_data_out_bytes)    $common_op_data_out_bytes
    set params(common_op_dummy_bytes)       $common_op_dummy_bytes
    set params(misc_op_offset)              $misc_op_offset
    set params(misc_op_name)                $misc_op_name
    set params(misc_op_opcode)              $misc_op_opcode
    set params(misc_op_addr_bytes)          $misc_op_addr_bytes
    set params(misc_op_data_in_bytes)       $misc_op_data_in_bytes
    set params(misc_op_data_out_bytes)      $misc_op_data_out_bytes
    set params(misc_op_dummy_bytes)         $misc_op_dummy_bytes
	set params(ctrl_registers)           	{isr ier chip_select status}
	set params(ctrl_registers_offset)       {6 7 8 9}
    set params(extra_op_name)               $extra_op_name
    set params(extra_op_offset)             $extra_op_offset
    set params(extra_op_en)                 $extra_op_en
    set params(en_chip_select)  			$enable_chip_select

    set result          [ altera_terp $template params ]
    set output_file     [ create_temp_file ${output_name}.sv ]
    set output_handle   [ open $output_file w ]

    puts $output_handle $result
    close $output_handle

    add_fileset_file ${output_name}.sv SYSTEM_VERILOG PATH ${output_file}

}

proc dec2bin {i {width {}}} {
    #returns the binary representation of $i
    # width determines the length of the returned string (left truncated or added left 0)
    # use of width allows concatenation of bits sub-fields
    set res {}
    if {$i<0} {
        set sign -
        set i [expr {abs($i)}]
    } else {
        set sign {}
    }
    while {$i>0} {
        set res [expr {$i%2}]$res
        set i [expr {$i/2}]
    }
    if {$res eq {}} {set res 0}
    if {$width ne {}} {
        append d [string repeat 0 $width] $res
        set res [string range $d [string length $res] end]
    }
    return $sign$res
}