# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Tue Apr 01 10:18:07 MYT 2014
# DO NOT MODIFY


# 
# altera_trace "Altera Trace Soft IP" v1.0
# Altera Corporation 2014.04.01.10:18:07
# This soft IP is used to export the trace interface from HPS out to FPGA pin
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module altera_trace
# 
set_module_property DESCRIPTION "This soft IP is used to export the trace interface from HPS out to FPGA IO pin"
set_module_property NAME altera_trace
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "HPS External Trace Core Intel FPGA IP"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_QUARTUS true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "proc_add_synth_file" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_trace
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

add_fileset SIM_VERILOG SIM_VERILOG "proc_add_sim_file" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_trace
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true

# 
# parameters
#

add_parameter 		   NUM_PIPELINE_REG INTEGER 1
set_parameter_property NUM_PIPELINE_REG DEFAULT_VALUE 1
set_parameter_property NUM_PIPELINE_REG DISPLAY_NAME NUM_PIPELINE_REG
set_parameter_property NUM_PIPELINE_REG TYPE INTEGER
set_parameter_property NUM_PIPELINE_REG UNITS None
set_parameter_property NUM_PIPELINE_REG ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20}
set_parameter_property NUM_PIPELINE_REG HDL_PARAMETER true

add_parameter			DEVICE_FAMILY STRING "Cyclone V" ""
set_parameter_property 	DEVICE_FAMILY DEFAULT_VALUE "Cyclone V"
set_parameter_property  DEVICE_FAMILY SYSTEM_INFO     "DEVICE_FAMILY"
set_parameter_property 	DEVICE_FAMILY ALLOWED_RANGES {"Cyclone V" "Arria V" "Arria 10" "Stratix 10"}
set_parameter_property 	DEVICE_FAMILY HDL_PARAMETER false
set_parameter_property  DEVICE_FAMILY VISIBLE false

add_parameter 		   IN_DWIDTH INTEGER 32
set_parameter_property IN_DWIDTH DEFAULT_VALUE 32
set_parameter_property IN_DWIDTH DISPLAY_NAME IN_DWIDTH
set_parameter_property IN_DWIDTH TYPE INTEGER
set_parameter_property IN_DWIDTH UNITS None
set_parameter_property IN_DWIDTH HDL_PARAMETER true
set_parameter_property IN_DWIDTH VISIBLE false

add_parameter 		   OUT_DWIDTH INTEGER 32
set_parameter_property OUT_DWIDTH DEFAULT_VALUE 32
set_parameter_property OUT_DWIDTH DISPLAY_NAME OUT_DWIDTH
set_parameter_property OUT_DWIDTH TYPE INTEGER
set_parameter_property OUT_DWIDTH UNITS None
set_parameter_property OUT_DWIDTH HDL_PARAMETER true
set_parameter_property OUT_DWIDTH ALLOWED_RANGES {"16" "32"}
set_parameter_property OUT_DWIDTH VISIBLE false

add_parameter 		   ADD_FEATURE BOOLEAN 1
set_parameter_property ADD_FEATURE DEFAULT_VALUE 1
set_parameter_property ADD_FEATURE DISPLAY_NAME ADD_FEATURE
set_parameter_property ADD_FEATURE TYPE BOOLEAN
set_parameter_property ADD_FEATURE DERIVED true
set_parameter_property ADD_FEATURE UNITS None
set_parameter_property ADD_FEATURE HDL_PARAMETER true
set_parameter_property ADD_FEATURE VISIBLE false

# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface 		   clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
add_interface_port 	   clock_sink h2f_tpiu_clock_out clk Input 1


# 
# connection point clock_source
# 
add_interface 		   trace_clk_out clock start
set_interface_property trace_clk_out associatedDirectClock clock_sink
set_interface_property trace_clk_out clockRate 0
set_interface_property trace_clk_out clockRateKnown false
set_interface_property trace_clk_out ENABLED true
set_interface_property trace_clk_out EXPORT_OF ""
set_interface_property trace_clk_out PORT_NAME_MAP ""
set_interface_property trace_clk_out CMSIS_SVD_VARIABLES ""
set_interface_property trace_clk_out SVD_ADDRESS_GROUP ""
add_interface_port 	   trace_clk_out trace_clkout clk Output 1


# 
# connection point reset_sink
# 
add_interface 		   reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
add_interface_port 	   reset_sink h2f_tpiu_reset_n reset_n Input 1


# 
# connection point h2f_tpiu
# 
add_interface 		   h2f_tpiu conduit end
set_interface_property h2f_tpiu associatedClock ""
set_interface_property h2f_tpiu associatedReset ""
set_interface_property h2f_tpiu ENABLED true
set_interface_property h2f_tpiu EXPORT_OF ""
set_interface_property h2f_tpiu PORT_NAME_MAP ""
set_interface_property h2f_tpiu CMSIS_SVD_VARIABLES ""
set_interface_property h2f_tpiu SVD_ADDRESS_GROUP ""
add_interface_port 	   h2f_tpiu h2f_tpiu_data 			data Input IN_DWIDTH
add_interface_port 	   h2f_tpiu f2h_tpiu_clock_out_ctl 	clk_ctl Output 1
add_interface_port 	   h2f_tpiu f2h_tpiu_clock_out 		clkin Output 1

# 
# connection point f2h_clk_in
# 
add_interface 		   f2h_clk_in conduit end
set_interface_property f2h_clk_in associatedClock ""
set_interface_property f2h_clk_in associatedReset ""
set_interface_property f2h_clk_in ENABLED true
set_interface_property f2h_clk_in EXPORT_OF ""
set_interface_property f2h_clk_in PORT_NAME_MAP ""
set_interface_property f2h_clk_in CMSIS_SVD_VARIABLES ""
set_interface_property f2h_clk_in SVD_ADDRESS_GROUP ""
add_interface_port 	   f2h_clk_in trace_clk_ctl 	clk_ctl input 1
add_interface_port 	   f2h_clk_in trace_clkin 		clk Input 1


# 
# connection point trace_out
# 
add_interface 		   trace_data_out conduit end
set_interface_property trace_data_out associatedClock ""
set_interface_property trace_data_out associatedReset ""
set_interface_property trace_data_out ENABLED true
set_interface_property trace_data_out EXPORT_OF ""
set_interface_property trace_data_out PORT_NAME_MAP ""
set_interface_property trace_data_out CMSIS_SVD_VARIABLES ""
set_interface_property trace_data_out SVD_ADDRESS_GROUP ""
add_interface_port 	   trace_data_out trace_dataout export Output OUT_DWIDTH

# 
# connection point output_gpio_conduit
# 
add_interface 		   data_gpio conduit end
add_interface_port 	   data_gpio data_gpio export Output OUT_DWIDTH*2

# 
# connection point clk_gpio
# 
add_interface 		   clk_gpio conduit end
add_interface_port 	   clk_gpio clk_gpio export Output 1

# 
# connection point reset_gpio
# 
add_interface 		   reset_gpio conduit end
add_interface_port 	   reset_gpio reset_gpio export Output 1
	
proc proc_add_synth_file { entity_name } {
    set device_family_param 	 [ get_parameter_value DEVICE_FAMILY ]
	
    add_fileset_file altera_trace.sv SYSTEM_VERILOG PATH altera_trace.sv TOP_LEVEL_FILE
	
	if {$device_family_param == "Cyclone V" || $device_family_param == "Arria V"} {
		add_fileset_file altddio.v VERILOG PATH altddio.v
	}
}

proc proc_add_sim_file { entity_name } {
    set device_family_param 	 [ get_parameter_value DEVICE_FAMILY ]

    add_fileset_file altera_trace.sv SYSTEM_VERILOG PATH altera_trace.sv TOP_LEVEL_FILE
	
	if {$device_family_param == "Cyclone V" || $device_family_param == "Arria V"} {
		add_fileset_file altddio.v VERILOG PATH altddio.v
	}
}

proc elaborate {} {
    set device_family_param 	 [ get_parameter_value DEVICE_FAMILY ]

    if {$device_family_param == "Cyclone V" || $device_family_param == "Arria V"} {
		set_parameter_value ADD_FEATURE 1
		
		set_interface_property trace_data_out 		ENABLED true
		set_interface_property data_gpio 			ENABLED false
		set_interface_property clk_gpio 			ENABLED false
		set_interface_property reset_gpio 			ENABLED false
    } else {
		set_parameter_value ADD_FEATURE 0
		
		set_interface_property trace_data_out 		ENABLED false
		set_interface_property data_gpio 			ENABLED true
		set_interface_property clk_gpio 			ENABLED true
		set_interface_property reset_gpio 			ENABLED true
    }
}
