// NiosV.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module NiosV (
		input  wire       clk_clk,        //     clk.clk
		output wire [7:0] pio_led_export, // pio_led.export
		input  wire [7:0] pio_sw_export,  //  pio_sw.export
		input  wire       reset_reset_n   //   reset.reset_n
	);

	wire  [31:0] niosv_data_manager_awaddr;                            // NiosV:data_manager_awaddr -> mm_interconnect_0:NiosV_data_manager_awaddr
	wire   [1:0] niosv_data_manager_bresp;                             // mm_interconnect_0:NiosV_data_manager_bresp -> NiosV:data_manager_bresp
	wire         niosv_data_manager_arready;                           // mm_interconnect_0:NiosV_data_manager_arready -> NiosV:data_manager_arready
	wire  [31:0] niosv_data_manager_rdata;                             // mm_interconnect_0:NiosV_data_manager_rdata -> NiosV:data_manager_rdata
	wire   [3:0] niosv_data_manager_wstrb;                             // NiosV:data_manager_wstrb -> mm_interconnect_0:NiosV_data_manager_wstrb
	wire         niosv_data_manager_wready;                            // mm_interconnect_0:NiosV_data_manager_wready -> NiosV:data_manager_wready
	wire         niosv_data_manager_awready;                           // mm_interconnect_0:NiosV_data_manager_awready -> NiosV:data_manager_awready
	wire         niosv_data_manager_rready;                            // NiosV:data_manager_rready -> mm_interconnect_0:NiosV_data_manager_rready
	wire         niosv_data_manager_bready;                            // NiosV:data_manager_bready -> mm_interconnect_0:NiosV_data_manager_bready
	wire         niosv_data_manager_wvalid;                            // NiosV:data_manager_wvalid -> mm_interconnect_0:NiosV_data_manager_wvalid
	wire  [31:0] niosv_data_manager_araddr;                            // NiosV:data_manager_araddr -> mm_interconnect_0:NiosV_data_manager_araddr
	wire   [2:0] niosv_data_manager_arprot;                            // NiosV:data_manager_arprot -> mm_interconnect_0:NiosV_data_manager_arprot
	wire   [1:0] niosv_data_manager_rresp;                             // mm_interconnect_0:NiosV_data_manager_rresp -> NiosV:data_manager_rresp
	wire   [2:0] niosv_data_manager_awprot;                            // NiosV:data_manager_awprot -> mm_interconnect_0:NiosV_data_manager_awprot
	wire  [31:0] niosv_data_manager_wdata;                             // NiosV:data_manager_wdata -> mm_interconnect_0:NiosV_data_manager_wdata
	wire         niosv_data_manager_arvalid;                           // NiosV:data_manager_arvalid -> mm_interconnect_0:NiosV_data_manager_arvalid
	wire         niosv_data_manager_bvalid;                            // mm_interconnect_0:NiosV_data_manager_bvalid -> NiosV:data_manager_bvalid
	wire         niosv_data_manager_awvalid;                           // NiosV:data_manager_awvalid -> mm_interconnect_0:NiosV_data_manager_awvalid
	wire         niosv_data_manager_rvalid;                            // mm_interconnect_0:NiosV_data_manager_rvalid -> NiosV:data_manager_rvalid
	wire  [31:0] niosv_instruction_manager_awaddr;                     // NiosV:instruction_manager_awaddr -> mm_interconnect_0:NiosV_instruction_manager_awaddr
	wire   [1:0] niosv_instruction_manager_bresp;                      // mm_interconnect_0:NiosV_instruction_manager_bresp -> NiosV:instruction_manager_bresp
	wire         niosv_instruction_manager_arready;                    // mm_interconnect_0:NiosV_instruction_manager_arready -> NiosV:instruction_manager_arready
	wire  [31:0] niosv_instruction_manager_rdata;                      // mm_interconnect_0:NiosV_instruction_manager_rdata -> NiosV:instruction_manager_rdata
	wire   [3:0] niosv_instruction_manager_wstrb;                      // NiosV:instruction_manager_wstrb -> mm_interconnect_0:NiosV_instruction_manager_wstrb
	wire         niosv_instruction_manager_wready;                     // mm_interconnect_0:NiosV_instruction_manager_wready -> NiosV:instruction_manager_wready
	wire         niosv_instruction_manager_awready;                    // mm_interconnect_0:NiosV_instruction_manager_awready -> NiosV:instruction_manager_awready
	wire         niosv_instruction_manager_rready;                     // NiosV:instruction_manager_rready -> mm_interconnect_0:NiosV_instruction_manager_rready
	wire         niosv_instruction_manager_bready;                     // NiosV:instruction_manager_bready -> mm_interconnect_0:NiosV_instruction_manager_bready
	wire         niosv_instruction_manager_wvalid;                     // NiosV:instruction_manager_wvalid -> mm_interconnect_0:NiosV_instruction_manager_wvalid
	wire  [31:0] niosv_instruction_manager_araddr;                     // NiosV:instruction_manager_araddr -> mm_interconnect_0:NiosV_instruction_manager_araddr
	wire   [2:0] niosv_instruction_manager_arprot;                     // NiosV:instruction_manager_arprot -> mm_interconnect_0:NiosV_instruction_manager_arprot
	wire   [1:0] niosv_instruction_manager_rresp;                      // mm_interconnect_0:NiosV_instruction_manager_rresp -> NiosV:instruction_manager_rresp
	wire   [2:0] niosv_instruction_manager_awprot;                     // NiosV:instruction_manager_awprot -> mm_interconnect_0:NiosV_instruction_manager_awprot
	wire  [31:0] niosv_instruction_manager_wdata;                      // NiosV:instruction_manager_wdata -> mm_interconnect_0:NiosV_instruction_manager_wdata
	wire         niosv_instruction_manager_arvalid;                    // NiosV:instruction_manager_arvalid -> mm_interconnect_0:NiosV_instruction_manager_arvalid
	wire         niosv_instruction_manager_bvalid;                     // mm_interconnect_0:NiosV_instruction_manager_bvalid -> NiosV:instruction_manager_bvalid
	wire         niosv_instruction_manager_awvalid;                    // NiosV:instruction_manager_awvalid -> mm_interconnect_0:NiosV_instruction_manager_awvalid
	wire         niosv_instruction_manager_rvalid;                     // mm_interconnect_0:NiosV_instruction_manager_rvalid -> NiosV:instruction_manager_rvalid
	wire         mm_interconnect_0_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:UART_avalon_jtag_slave_chipselect -> UART:av_chipselect
	wire  [31:0] mm_interconnect_0_uart_avalon_jtag_slave_readdata;    // UART:av_readdata -> mm_interconnect_0:UART_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_uart_avalon_jtag_slave_waitrequest; // UART:av_waitrequest -> mm_interconnect_0:UART_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_uart_avalon_jtag_slave_address;     // mm_interconnect_0:UART_avalon_jtag_slave_address -> UART:av_address
	wire         mm_interconnect_0_uart_avalon_jtag_slave_read;        // mm_interconnect_0:UART_avalon_jtag_slave_read -> UART:av_read_n
	wire         mm_interconnect_0_uart_avalon_jtag_slave_write;       // mm_interconnect_0:UART_avalon_jtag_slave_write -> UART:av_write_n
	wire  [31:0] mm_interconnect_0_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:UART_avalon_jtag_slave_writedata -> UART:av_writedata
	wire         mm_interconnect_0_ram_s1_chipselect;                  // mm_interconnect_0:RAM_s1_chipselect -> RAM:chipselect
	wire  [31:0] mm_interconnect_0_ram_s1_readdata;                    // RAM:readdata -> mm_interconnect_0:RAM_s1_readdata
	wire  [13:0] mm_interconnect_0_ram_s1_address;                     // mm_interconnect_0:RAM_s1_address -> RAM:address
	wire   [3:0] mm_interconnect_0_ram_s1_byteenable;                  // mm_interconnect_0:RAM_s1_byteenable -> RAM:byteenable
	wire         mm_interconnect_0_ram_s1_write;                       // mm_interconnect_0:RAM_s1_write -> RAM:write
	wire  [31:0] mm_interconnect_0_ram_s1_writedata;                   // mm_interconnect_0:RAM_s1_writedata -> RAM:writedata
	wire         mm_interconnect_0_ram_s1_clken;                       // mm_interconnect_0:RAM_s1_clken -> RAM:clken
	wire         mm_interconnect_0_pio_led_s1_chipselect;              // mm_interconnect_0:PIO_LED_s1_chipselect -> PIO_LED:chipselect
	wire  [31:0] mm_interconnect_0_pio_led_s1_readdata;                // PIO_LED:readdata -> mm_interconnect_0:PIO_LED_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_led_s1_address;                 // mm_interconnect_0:PIO_LED_s1_address -> PIO_LED:address
	wire         mm_interconnect_0_pio_led_s1_write;                   // mm_interconnect_0:PIO_LED_s1_write -> PIO_LED:write_n
	wire  [31:0] mm_interconnect_0_pio_led_s1_writedata;               // mm_interconnect_0:PIO_LED_s1_writedata -> PIO_LED:writedata
	wire  [31:0] mm_interconnect_0_pio_sw_s1_readdata;                 // PIO_SW:readdata -> mm_interconnect_0:PIO_SW_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_sw_s1_address;                  // mm_interconnect_0:PIO_SW_s1_address -> PIO_SW:address
	wire         rst_controller_reset_out_reset;                       // rst_controller:reset_out -> [NiosV:reset_reset, PIO_LED:reset_n, PIO_SW:reset_n, RAM:reset, UART:rst_n, mm_interconnect_0:NiosV_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                   // rst_controller:reset_req -> [RAM:reset_req, rst_translator:reset_req_in]

	NiosV_NiosV niosv (
		.clk                         (clk_clk),                           //                 clk.clk
		.reset_reset                 (rst_controller_reset_out_reset),    //               reset.reset
		.instruction_manager_awaddr  (niosv_instruction_manager_awaddr),  // instruction_manager.awaddr
		.instruction_manager_awprot  (niosv_instruction_manager_awprot),  //                    .awprot
		.instruction_manager_awvalid (niosv_instruction_manager_awvalid), //                    .awvalid
		.instruction_manager_awready (niosv_instruction_manager_awready), //                    .awready
		.instruction_manager_wdata   (niosv_instruction_manager_wdata),   //                    .wdata
		.instruction_manager_wstrb   (niosv_instruction_manager_wstrb),   //                    .wstrb
		.instruction_manager_wvalid  (niosv_instruction_manager_wvalid),  //                    .wvalid
		.instruction_manager_wready  (niosv_instruction_manager_wready),  //                    .wready
		.instruction_manager_bresp   (niosv_instruction_manager_bresp),   //                    .bresp
		.instruction_manager_bvalid  (niosv_instruction_manager_bvalid),  //                    .bvalid
		.instruction_manager_bready  (niosv_instruction_manager_bready),  //                    .bready
		.instruction_manager_araddr  (niosv_instruction_manager_araddr),  //                    .araddr
		.instruction_manager_arprot  (niosv_instruction_manager_arprot),  //                    .arprot
		.instruction_manager_arvalid (niosv_instruction_manager_arvalid), //                    .arvalid
		.instruction_manager_arready (niosv_instruction_manager_arready), //                    .arready
		.instruction_manager_rdata   (niosv_instruction_manager_rdata),   //                    .rdata
		.instruction_manager_rresp   (niosv_instruction_manager_rresp),   //                    .rresp
		.instruction_manager_rvalid  (niosv_instruction_manager_rvalid),  //                    .rvalid
		.instruction_manager_rready  (niosv_instruction_manager_rready),  //                    .rready
		.data_manager_awaddr         (niosv_data_manager_awaddr),         //        data_manager.awaddr
		.data_manager_awprot         (niosv_data_manager_awprot),         //                    .awprot
		.data_manager_awvalid        (niosv_data_manager_awvalid),        //                    .awvalid
		.data_manager_awready        (niosv_data_manager_awready),        //                    .awready
		.data_manager_wdata          (niosv_data_manager_wdata),          //                    .wdata
		.data_manager_wstrb          (niosv_data_manager_wstrb),          //                    .wstrb
		.data_manager_wvalid         (niosv_data_manager_wvalid),         //                    .wvalid
		.data_manager_wready         (niosv_data_manager_wready),         //                    .wready
		.data_manager_bresp          (niosv_data_manager_bresp),          //                    .bresp
		.data_manager_bvalid         (niosv_data_manager_bvalid),         //                    .bvalid
		.data_manager_bready         (niosv_data_manager_bready),         //                    .bready
		.data_manager_araddr         (niosv_data_manager_araddr),         //                    .araddr
		.data_manager_arprot         (niosv_data_manager_arprot),         //                    .arprot
		.data_manager_arvalid        (niosv_data_manager_arvalid),        //                    .arvalid
		.data_manager_arready        (niosv_data_manager_arready),        //                    .arready
		.data_manager_rdata          (niosv_data_manager_rdata),          //                    .rdata
		.data_manager_rresp          (niosv_data_manager_rresp),          //                    .rresp
		.data_manager_rvalid         (niosv_data_manager_rvalid),         //                    .rvalid
		.data_manager_rready         (niosv_data_manager_rready)          //                    .rready
	);

	NiosV_PIO_LED pio_led (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address    (mm_interconnect_0_pio_led_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_led_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_led_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_led_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_led_s1_readdata),   //                    .readdata
		.out_port   (pio_led_export)                           // external_connection.export
	);

	NiosV_PIO_SW pio_sw (
		.clk      (clk_clk),                              //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address  (mm_interconnect_0_pio_sw_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_sw_s1_readdata), //                    .readdata
		.in_port  (pio_sw_export)                         // external_connection.export
	);

	NiosV_RAM ram (
		.clk        (clk_clk),                             //   clk1.clk
		.address    (mm_interconnect_0_ram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze     (1'b0)                                 // (terminated)
	);

	altera_avalon_jtag_uart #(
		.readBufferDepth            (64),
		.readIRQThreshold           (8),
		.useRegistersForReadBuffer  (0),
		.useRegistersForWriteBuffer (0),
		.writeBufferDepth           (64),
		.writeIRQThreshold          (8),
		.printingMethod             (0),
		.FIFO_WIDTH                 (8),
		.WR_WIDTHU                  (6),
		.RD_WIDTHU                  (6),
		.write_le                   ("ON"),
		.read_le                    ("ON"),
		.HEX_WRITE_DEPTH_STR        (64),
		.HEX_READ_DEPTH_STR         (64),
		.legacySignalAllow          (0)
	) uart (
		.clk            (clk_clk),                                              //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                      //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         ()                                                      //               irq.irq
	);

	NiosV_mm_interconnect_0 mm_interconnect_0 (
		.NiosV_data_manager_awaddr               (niosv_data_manager_awaddr),                            //                NiosV_data_manager.awaddr
		.NiosV_data_manager_awprot               (niosv_data_manager_awprot),                            //                                  .awprot
		.NiosV_data_manager_awvalid              (niosv_data_manager_awvalid),                           //                                  .awvalid
		.NiosV_data_manager_awready              (niosv_data_manager_awready),                           //                                  .awready
		.NiosV_data_manager_wdata                (niosv_data_manager_wdata),                             //                                  .wdata
		.NiosV_data_manager_wstrb                (niosv_data_manager_wstrb),                             //                                  .wstrb
		.NiosV_data_manager_wvalid               (niosv_data_manager_wvalid),                            //                                  .wvalid
		.NiosV_data_manager_wready               (niosv_data_manager_wready),                            //                                  .wready
		.NiosV_data_manager_bresp                (niosv_data_manager_bresp),                             //                                  .bresp
		.NiosV_data_manager_bvalid               (niosv_data_manager_bvalid),                            //                                  .bvalid
		.NiosV_data_manager_bready               (niosv_data_manager_bready),                            //                                  .bready
		.NiosV_data_manager_araddr               (niosv_data_manager_araddr),                            //                                  .araddr
		.NiosV_data_manager_arprot               (niosv_data_manager_arprot),                            //                                  .arprot
		.NiosV_data_manager_arvalid              (niosv_data_manager_arvalid),                           //                                  .arvalid
		.NiosV_data_manager_arready              (niosv_data_manager_arready),                           //                                  .arready
		.NiosV_data_manager_rdata                (niosv_data_manager_rdata),                             //                                  .rdata
		.NiosV_data_manager_rresp                (niosv_data_manager_rresp),                             //                                  .rresp
		.NiosV_data_manager_rvalid               (niosv_data_manager_rvalid),                            //                                  .rvalid
		.NiosV_data_manager_rready               (niosv_data_manager_rready),                            //                                  .rready
		.NiosV_instruction_manager_awaddr        (niosv_instruction_manager_awaddr),                     //         NiosV_instruction_manager.awaddr
		.NiosV_instruction_manager_awprot        (niosv_instruction_manager_awprot),                     //                                  .awprot
		.NiosV_instruction_manager_awvalid       (niosv_instruction_manager_awvalid),                    //                                  .awvalid
		.NiosV_instruction_manager_awready       (niosv_instruction_manager_awready),                    //                                  .awready
		.NiosV_instruction_manager_wdata         (niosv_instruction_manager_wdata),                      //                                  .wdata
		.NiosV_instruction_manager_wstrb         (niosv_instruction_manager_wstrb),                      //                                  .wstrb
		.NiosV_instruction_manager_wvalid        (niosv_instruction_manager_wvalid),                     //                                  .wvalid
		.NiosV_instruction_manager_wready        (niosv_instruction_manager_wready),                     //                                  .wready
		.NiosV_instruction_manager_bresp         (niosv_instruction_manager_bresp),                      //                                  .bresp
		.NiosV_instruction_manager_bvalid        (niosv_instruction_manager_bvalid),                     //                                  .bvalid
		.NiosV_instruction_manager_bready        (niosv_instruction_manager_bready),                     //                                  .bready
		.NiosV_instruction_manager_araddr        (niosv_instruction_manager_araddr),                     //                                  .araddr
		.NiosV_instruction_manager_arprot        (niosv_instruction_manager_arprot),                     //                                  .arprot
		.NiosV_instruction_manager_arvalid       (niosv_instruction_manager_arvalid),                    //                                  .arvalid
		.NiosV_instruction_manager_arready       (niosv_instruction_manager_arready),                    //                                  .arready
		.NiosV_instruction_manager_rdata         (niosv_instruction_manager_rdata),                      //                                  .rdata
		.NiosV_instruction_manager_rresp         (niosv_instruction_manager_rresp),                      //                                  .rresp
		.NiosV_instruction_manager_rvalid        (niosv_instruction_manager_rvalid),                     //                                  .rvalid
		.NiosV_instruction_manager_rready        (niosv_instruction_manager_rready),                     //                                  .rready
		.CLK_clk_clk                             (clk_clk),                                              //                           CLK_clk.clk
		.NiosV_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                       // NiosV_reset_reset_bridge_in_reset.reset
		.PIO_LED_s1_address                      (mm_interconnect_0_pio_led_s1_address),                 //                        PIO_LED_s1.address
		.PIO_LED_s1_write                        (mm_interconnect_0_pio_led_s1_write),                   //                                  .write
		.PIO_LED_s1_readdata                     (mm_interconnect_0_pio_led_s1_readdata),                //                                  .readdata
		.PIO_LED_s1_writedata                    (mm_interconnect_0_pio_led_s1_writedata),               //                                  .writedata
		.PIO_LED_s1_chipselect                   (mm_interconnect_0_pio_led_s1_chipselect),              //                                  .chipselect
		.PIO_SW_s1_address                       (mm_interconnect_0_pio_sw_s1_address),                  //                         PIO_SW_s1.address
		.PIO_SW_s1_readdata                      (mm_interconnect_0_pio_sw_s1_readdata),                 //                                  .readdata
		.RAM_s1_address                          (mm_interconnect_0_ram_s1_address),                     //                            RAM_s1.address
		.RAM_s1_write                            (mm_interconnect_0_ram_s1_write),                       //                                  .write
		.RAM_s1_readdata                         (mm_interconnect_0_ram_s1_readdata),                    //                                  .readdata
		.RAM_s1_writedata                        (mm_interconnect_0_ram_s1_writedata),                   //                                  .writedata
		.RAM_s1_byteenable                       (mm_interconnect_0_ram_s1_byteenable),                  //                                  .byteenable
		.RAM_s1_chipselect                       (mm_interconnect_0_ram_s1_chipselect),                  //                                  .chipselect
		.RAM_s1_clken                            (mm_interconnect_0_ram_s1_clken),                       //                                  .clken
		.UART_avalon_jtag_slave_address          (mm_interconnect_0_uart_avalon_jtag_slave_address),     //            UART_avalon_jtag_slave.address
		.UART_avalon_jtag_slave_write            (mm_interconnect_0_uart_avalon_jtag_slave_write),       //                                  .write
		.UART_avalon_jtag_slave_read             (mm_interconnect_0_uart_avalon_jtag_slave_read),        //                                  .read
		.UART_avalon_jtag_slave_readdata         (mm_interconnect_0_uart_avalon_jtag_slave_readdata),    //                                  .readdata
		.UART_avalon_jtag_slave_writedata        (mm_interconnect_0_uart_avalon_jtag_slave_writedata),   //                                  .writedata
		.UART_avalon_jtag_slave_waitrequest      (mm_interconnect_0_uart_avalon_jtag_slave_waitrequest), //                                  .waitrequest
		.UART_avalon_jtag_slave_chipselect       (mm_interconnect_0_uart_avalon_jtag_slave_chipselect)   //                                  .chipselect
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
