# Module name strings
HWTCL_MODULE_DISPLAY_NAME = Arria 10 External Memory Interfaces
HWTCL_MODULE_DESCRIPTION = Arria 10 External Memory Interfaces

HWTCL_MODULE_A10_HPS_DISPLAY_NAME = Arria 10 External Memory Interfaces for HPS
HWTCL_MODULE_A10_HPS_DESCRIPTION = Arria 10 External Memory Interfaces for HPS

HWTCL_MODULE_S10_DISPLAY_NAME = Stratix 10 External Memory Interfaces
HWTCL_MODULE_S10_DESCRIPTION = Stratix 10 External Memory Interfaces

HWTCL_MODULE_S10_HPS_DISPLAY_NAME = Stratix 10 External Memory Interfaces for HPS
HWTCL_MODULE_S10_HPS_DESCRIPTION = Stratix 10 External Memory Interfaces for HPS

# GUI tab names
TAB_PHY_NAME = General
TAB_IO_NAME = FPGA I/O
TAB_MEM_PARAMS_NAME = Memory
TAB_MEM_IO_NAME = Mem I/O
TAB_MEM_TIMING_NAME = Mem Timing
TAB_BOARD_TIMING_NAME = Board
TAB_CONTROLLER_NAME = Controller
TAB_DIAGNOSTICS_NAME = Diagnostics
TAB_EXAMPLE_DESIGN_NAME = Example Designs

# GUI group names
GRP_PROTOCOL_NAME = Memory Protocol
GRP_PHY_FPGA_NAME = FPGA
GRP_PHY_IF_NAME = Interface
GRP_PHY_CLKS_NAME = Clocks
GRP_PHY_HPS_NAME = HPS Options
GRP_PHY_IO_NAME = FPGA I/O Settings
GRP_PHY_AC_IO_NAME = Address/Command
GRP_PHY_CK_IO_NAME = Memory Clock
GRP_PHY_DATA_IO_NAME = Data Bus
GRP_PHY_FPGA_IO_NAME = PHY Inputs

GRP_MEM_TOPOLOGY_NAME = Topology
GRP_MEM_LATENCY_NAME = Latency and Burst
GRP_MEM_IO_NAME = Memory I/O Settings
GRP_MEM_MRS_NAME = Mode Register Settings
GRP_MEM_CRS_NAME = Configuration Register Settings
GRP_MEM_RLRDIMM_SPD_NAME = RDIMM/LRDIMM Serial Presence Detect (SPD) Data
GRP_MEM_ODT_NAME = ODT Activation

GRP_MEM_TIMING_SPEEDBIN = Parameters dependent on Speed Bin
GRP_MEM_TIMING_SPEEDBIN_FREQ_PAGESIZE = Parameters dependent on Speed Bin, Operating Frequency, and Page Size
GRP_MEM_TIMING_DENSITY_TEMP = Parameters dependent on Density and Temperature

GRP_CTRL_AVALON_NAME = Avalon Interface
GRP_CTRL_LOW_POWER_NAME = Low Power Mode
GRP_CTRL_EFFICIENCY_NAME = Efficiency
GRP_CTRL_ERROR_HANDLING_NAME = Configuration, Status and Error Handling
GRP_CTRL_BUS_TURNAROUND_NAME = Data Bus Turnaround Time

GRP_BOARD_SLEW_RATES_NAME = Slew Rates
GRP_BOARD_ISI_NAME = Intersymbol Interference/Crosstalk
GRP_BOARD_SKEWS_NAME = Board and Package Skews

GRP_DIAGNOSTICS_SIM_NAME = Simulation Options
GRP_DIAGNOSTICS_CAL_DEBUG_NAME = Calibration Debug Options
GRP_DIAGNOSTICS_EX_DESIGN_NAME = Example Design
GRP_DIAGNOSTICS_TRAFFIC_GENERATOR_NAME = Traffic Generator
GRP_DIAGNOSTICS_PERFORMANCE_NAME = Performance
GRP_DIAGNOSTICS_MISC_NAME = Miscellaneous
GRP_DIAGNOSTICS_INTERNAL_NAME = Internal Settings

GRP_EX_DESIGN_AVAIL_DESIGNS_NAME = Available Example Designs
GRP_EX_DESIGN_FILES_NAME = Example Design Files
GRP_EX_DESIGN_HDL_FORMAT_NAME = Generated HDL Format
GRP_EX_DESIGN_TARGET_DEV_KIT_NAME = Target Development Kit
GRP_EX_DESIGN_SETTINGS_NAME = Example Design Settings

# DDR3/DDR4 RDIMM/LRDIMM Display Item Names
DDR3_RDIMM_TXT_NAME = DDR3 RDIMM TXT
DDR3_LRDIMM_TXT_NAME = DDR3 LRDIMM TXT
DDR4_RDIMM_TXT_NAME = DDR4 RDIMM TXT
DDR4_LRDIMM_TXT_NAME = DDR4 LRDIMM TXT

TXT_IO_RECOMMENDATION = <html>You should use Hyperlynx or similar simulators to determine the best settings for your board.

TXT_DESIGN_FILES_GUIDE = <html>The example design supports generation, simulation, and Quartus compilation flows for any selected device. To use the<br>example design for simulation, select the 'Simulation' option above. To use the example design for compilation and<br>hardware, select the 'Synthesis' option above.

TXT_EX_DESIGN_GUIDE = <html>Select a development kit preset from the 'Presets' panel to configure the example design for testing on a specific<br>development kit. If you are not generating your example design for a development kit (i.e. developing on a custom<br>board), please select 'none' from the drop-down menu above.

TXT_EX_DESIGN_DEVKIT_NONE = Apply a development kit preset in the Presets panel to configure the example design for development kit testing.

###############################################################################
# Protocol-Agnostic Parameters
###############################################################################

GRP_PLL_EXTRA_CLKS = Additional core clocks
GRP_PLL_EXTRA_CLK0 = pll_extra_clk_0
GRP_PLL_EXTRA_CLK1 = pll_extra_clk_1
GRP_PLL_EXTRA_CLK2 = pll_extra_clk_2
GRP_PLL_EXTRA_CLK3 = pll_extra_clk_3

TXT_WARN_PLL_EXTRA_CLKS = <html><b>IMPORTANT:</b> Clock signals generated by this option must be treated as <b>asynchronous</b> to the memory<br/>interface core clock domains. Proper clock-domain-crossing techniques must be employed when<br/>transferring data between them. The additional core clocks are synchronous to each other.
