# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# $Id: //acds/rel/18.1std/ip/sld/trace/monitors/altera_trace_adc_monitor/altera_trace_adc_monitor_driver_hw.tcl#1 $
# $Revision: #1 $
# $Date: 2018/07/18 $
# $Author: psgswbuild $

# TCL File Generated by Component Editor 14.1
# Tue Sep 23 13:37:34 PDT 2014
# DO NOT MODIFY


# 
# altera_trace_adc_monitor_driver "altera_trace_adc_monitor_driver" v1.0
#  2014.09.23.13:37:34
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module altera_trace_adc_monitor_driver
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_trace_adc_monitor_driver
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME altera_trace_adc_monitor_driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_trace_adc_monitor_driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_trace_adc_monitor_driver.sv SYSTEM_VERILOG PATH altera_trace_adc_monitor_driver.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_trace_adc_monitor_driver
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_trace_adc_monitor_driver.sv SYSTEM_VERILOG PATH altera_trace_adc_monitor_driver.sv


# 
# parameters
# 
add_parameter PERIOD_US FLOAT 1
set_parameter_property PERIOD_US DISPLAY_NAME PERIOD_US
set_parameter_property PERIOD_US TYPE INTEGER
set_parameter_property PERIOD_US ENABLED true
set_parameter_property PERIOD_US UNITS MICROSECONDS
set_parameter_property PERIOD_US UNITS None
set_parameter_property PERIOD_US HDL_PARAMETER false
set_parameter_property PERIOD_US AFFECTS_ELABORATION true

add_parameter PERIOD_COUNTER_WIDTH INTEGER 16
set_parameter_property PERIOD_COUNTER_WIDTH DEFAULT_VALUE 16
set_parameter_property PERIOD_COUNTER_WIDTH DISPLAY_NAME PERIOD_COUNTER_WIDTH
set_parameter_property PERIOD_COUNTER_WIDTH TYPE INTEGER
set_parameter_property PERIOD_COUNTER_WIDTH ENABLED false
set_parameter_property PERIOD_COUNTER_WIDTH UNITS None
set_parameter_property PERIOD_COUNTER_WIDTH HDL_PARAMETER true
set_parameter_property PERIOD_COUNTER_WIDTH AFFECTS_ELABORATION true

add_parameter PERIOD_CYCLES INTEGER 50 ""
set_parameter_property PERIOD_CYCLES DEFAULT_VALUE 50
set_parameter_property PERIOD_CYCLES DISPLAY_NAME PERIOD_CYCLES
set_parameter_property PERIOD_CYCLES WIDTH ""
set_parameter_property PERIOD_CYCLES TYPE INTEGER
set_parameter_property PERIOD_CYCLES ENABLED false
set_parameter_property PERIOD_CYCLES UNITS None
set_parameter_property PERIOD_CYCLES ALLOWED_RANGES 0:65535
set_parameter_property PERIOD_CYCLES DESCRIPTION ""
set_parameter_property PERIOD_CYCLES HDL_PARAMETER true
set_parameter_property PERIOD_CYCLES DERIVED true
set_parameter_property PERIOD_CYCLES AFFECTS_ELABORATION true

add_parameter ST_CHANNEL_WIDTH INTEGER 5
set_parameter_property ST_CHANNEL_WIDTH DEFAULT_VALUE 5
set_parameter_property ST_CHANNEL_WIDTH DISPLAY_NAME ST_CHANNEL_WIDTH
set_parameter_property ST_CHANNEL_WIDTH TYPE INTEGER
set_parameter_property ST_CHANNEL_WIDTH ENABLED false
set_parameter_property ST_CHANNEL_WIDTH UNITS None
set_parameter_property ST_CHANNEL_WIDTH HDL_PARAMETER true
set_parameter_property ST_CHANNEL_WIDTH AFFECTS_ELABORATION true

add_parameter ST_DATA_WIDTH INTEGER 12
set_parameter_property ST_DATA_WIDTH DEFAULT_VALUE 12
set_parameter_property ST_DATA_WIDTH DISPLAY_NAME ST_DATA_WIDTH
set_parameter_property ST_DATA_WIDTH TYPE INTEGER
set_parameter_property ST_DATA_WIDTH ENABLED false
set_parameter_property ST_DATA_WIDTH UNITS None
set_parameter_property ST_DATA_WIDTH HDL_PARAMETER true
set_parameter_property ST_DATA_WIDTH AFFECTS_ELABORATION true

add_parameter CLOCK_FREQ LONG
set_parameter_property CLOCK_FREQ DEFAULT_VALUE 0
set_parameter_property CLOCK_FREQ DISPLAY_NAME CLOCK_FREQ
set_parameter_property CLOCK_FREQ VISIBLE 0
set_parameter_property CLOCK_FREQ AFFECTS_ELABORATION 1
set_parameter_property CLOCK_FREQ HDL_PARAMETER 0
set_parameter_property CLOCK_FREQ SYSTEM_INFO {clock_rate clk}
set_parameter_property CLOCK_FREQ SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property CLOCK_FREQ SYSTEM_INFO_ARG {clock}

# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_read read Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_address address Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_write write Input 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point adc
# 
add_interface adc avalon_streaming start
set_interface_property adc associatedClock clock
set_interface_property adc associatedReset reset
set_interface_property adc dataBitsPerSymbol 12
set_interface_property adc errorDescriptor ""
set_interface_property adc firstSymbolInHighOrderBits true
set_interface_property adc maxChannel 31
set_interface_property adc readyLatency 0
set_interface_property adc ENABLED true
set_interface_property adc EXPORT_OF ""
set_interface_property adc PORT_NAME_MAP ""
set_interface_property adc CMSIS_SVD_VARIABLES ""
set_interface_property adc SVD_ADDRESS_GROUP ""

add_interface_port adc adc_valid valid Output 1
add_interface_port adc adc_channel channel Output ST_CHANNEL_WIDTH
add_interface_port adc adc_data data Output ST_DATA_WIDTH
add_interface_port adc adc_startofpacket startofpacket Output 1
add_interface_port adc adc_endofpacket endofpacket Output 1

proc elaborate {} {
  set clock_rate [ get_parameter_value CLOCK_FREQ ]
  if { $clock_rate == 0 } {
    send_message warning "Unknown clock rate; assuming 50MHz."
    set clock_rate 50000000
  }
  set period_us [ get_parameter_value PERIOD_US ]

  if { $period_us < 0 || $period_us > 1000 } {
    send_message error "PERIOD_US must be between 0 and 1000 (is: $period_us)"
  }

  set period_cycles [ expr $period_us * $clock_rate / 1000000 ]
  set period_counter_width [ expr ceil(log($period_cycles) / log(2)) ]

  set actual_period_counter_width [ get_parameter_value PERIOD_COUNTER_WIDTH ] 
  if { $period_counter_width > $actual_period_counter_width } {
    send_message error "Calculated period counter width is $period_counter_width is larger than maximum ($actual_period_counter_width)"
  }
  if { $period_cycles < 1 } {
    set $period_cycles 1
  }
  set_parameter_value PERIOD_CYCLES $period_cycles

  set clock_rate_MHz [ expr $clock_rate / 1000000 ]
  send_message info "clock rate: $clock_rate_MHz MHz; period: $period_us us; period cycles: $period_cycles"
}

