# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# $Id: //acds/rel/18.1std/ip/sld/trace/monitors/altera_trace_adc_monitor/altera_trace_adc_monitor_wa_hw.tcl#1 $
# $Revision: #1 $
# $Date: 2018/07/18 $
# $Author: psgswbuild $

# TCL File Generated by Component Editor 14.1
# Tue Aug 19 11:36:05 PDT 2014
# DO NOT MODIFY


# 
# altera_trace_adc_monitor_wa "altera_trace_adc_monitor_wa" v1.0
#  2014.08.19.11:36:05
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 13.0


# 
# module altera_trace_adc_monitor_wa
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_trace_adc_monitor_wa
set_module_property VERSION 18.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera Trace ADC Monitor Width Adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_trace_adc_monitor_wa
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_trace_adc_monitor_wa.sv SYSTEM_VERILOG PATH altera_trace_adc_monitor_wa.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_trace_adc_monitor_wa
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_trace_adc_monitor_wa.sv SYSTEM_VERILOG PATH altera_trace_adc_monitor_wa.sv


# 
# parameters
# 
add_parameter IN_DATA_WIDTH INTEGER 12
set_parameter_property IN_DATA_WIDTH DEFAULT_VALUE 12
set_parameter_property IN_DATA_WIDTH DISPLAY_NAME IN_DATA_WIDTH
set_parameter_property IN_DATA_WIDTH TYPE INTEGER
set_parameter_property IN_DATA_WIDTH ENABLED false
set_parameter_property IN_DATA_WIDTH UNITS None
set_parameter_property IN_DATA_WIDTH HDL_PARAMETER true
add_parameter OUT_DATA_WIDTH INTEGER 8
set_parameter_property OUT_DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property OUT_DATA_WIDTH DISPLAY_NAME OUT_DATA_WIDTH
set_parameter_property OUT_DATA_WIDTH TYPE INTEGER
set_parameter_property OUT_DATA_WIDTH ENABLED false
set_parameter_property OUT_DATA_WIDTH UNITS None
set_parameter_property OUT_DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

# 
# connection point synchronous_reset
# 
add_interface synchronous_reset conduit end
set_interface_property reset associatedClock clock
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port synchronous_reset sync_reset conduit Input 1

# 
# connection point beat0_rem
# 
add_interface beat0_rem avalon_streaming start
set_interface_property beat0_rem associatedClock clock
set_interface_property beat0_rem associatedReset reset
set_interface_property beat0_rem dataBitsPerSymbol 0
set_interface_property beat0_rem errorDescriptor ""
set_interface_property beat0_rem firstSymbolInHighOrderBits true
set_interface_property beat0_rem maxChannel 0
set_interface_property beat0_rem readyLatency 0
set_interface_property beat0_rem ENABLED true
set_interface_property beat0_rem EXPORT_OF ""
set_interface_property beat0_rem PORT_NAME_MAP ""
set_interface_property beat0_rem CMSIS_SVD_VARIABLES ""
set_interface_property beat0_rem SVD_ADDRESS_GROUP ""

add_interface_port beat0_rem beat0_rem_valid valid Output 1

# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 12
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink in_valid valid Input 1
add_interface_port sink in_data data Input IN_DATA_WIDTH


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source out_valid valid Output 1
add_interface_port source out_data data Output OUT_DATA_WIDTH
add_interface_port source out_ready ready Input 1

