# Module name strings
HWTCL_MODULE_DISPLAY_NAME = External Memory Interfaces Debug Component
HWTCL_MODULE_DESCRIPTION = This component must be connected to one of the EMIF cores in an I/O column in order to access it using the External Memory Interface Debug Toolkit.

PARAM_ADDR_WIDTH_NAME = Address Width
PARAM_ADDR_WIDTH_DESC = Address Width

# Enable/disable JTAG Avalon Master for debug toolkit
PARAM_ENABLE_JTAG_AVALON_MASTER_NAME = Enable JTAG Avalon Master
PARAM_ENABLE_JTAG_AVALON_MASTER_DESCRIPTION = Enable JTAG Avalon Master for External Memory Interface Debug Toolkit access

# NUM_AVALON_INTERFACES display name and description
PARAM_NUM_AVALON_INTERFACES_NAME = Number of Avalon-MM Slave Interfaces
PARAM_NUM_AVALON_INTERFACES_DESCRIPTION = The number of Avalon-MM slave interfaces to create

# Enable/disable JTAG Avalon Master for debug toolkit
PARAM_JTAG_MASTER_NAME_NAME = JTAG Avalon Master target
PARAM_JTAG_MASTER_NAME_DESCRIPTION = Name for the JTAG Avalon Master.  "colmaster" should be used for EMIF debug interfaces.  "tgmaster" should be used for Traffic Generator configuration interfaces.
